### ISSUE TITLE
Incorrect Description of available settings 

### ISSUE THREAD

**Issue by cking22001** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10026]
Teams Admin Center under Teams Update Policies does not have a user can choose but setting to Enabled instead does not seem to work either.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Version Independent ID: 1d50c2e0-d6d3-ec3f-5e99-acaa2a6868d5
* Content: [The new Microsoft Teams desktop client - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/new-teams-desktop-admin?tabs=teams-admin-center)
* Content Source: [Teams/new-teams-desktop-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/new-teams-desktop-admin.md)
* Service: **msteams**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @cking22001, thank you for your feedback.

I can see "Users can choose" in a demo tenant:
![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/33589238/e0b00b19-b0ad-44c9-8a44-364aa137b6af)

**Comment by cking22001** [comment]
![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/10732022/69e91b74-ad62-44ae-a51f-1f875b5cc08b)
We must have different versions of Office 365 Teams Admin Center or something.

**Comment by cking22001** [comment]
Right, my point is I do not see a Use new Teams client dropdown. Sorry, I was editing my original reply so maybe you missed that. Thanks.

**Comment by dariomws** [comment]
I have verified in 4 tenants and I have the dropdown menu with Users can choose. In this case, the best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information provided at [Get support](https://docs.microsoft.com/microsoft-365/business-video/get-help-support). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
