### ISSUE TITLE
Error in running CreateSrsMedia.ps1 script - Skype Room Systems v2 console

### ISSUE THREAD

**Issue by dmonti79** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1003]
Running Windows 10 Enterprise 1803

I see where there error reported is that I'm missing an update, however, when I try to manually install it from the Windows Update Catalog, I'm told its not applicable. 

Any help would be appreciated.
Reference:
https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/console#Prep_Media

**********************
Windows PowerShell transcript start
Start time: 20181031150258
Username: DESKTOP-VDFH13P\Music Laptop
RunAs User: DESKTOP-VDFH13P\Music Laptop
Configuration Name: 
Machine: DESKTOP-VDFH13P (Microsoft Windows NT 10.0.17134.0)
Host Application: C:\WINDOWS\system32\WindowsPowerShell\v1.0\PowerShell_ISE.exe
Process ID: 3076
PSVersion: 5.1.17134.228
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17134.228
BuildVersion: 10.0.17134.228
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\CMC IT\Documents\PowerShell_transcript.DESKTOP-VDFH13P.ZrTE3heR.20181031150258.txt
Script version 1.4.1
Downloading CreateSrsMedia...
done
Validating signature for update.ps1...
success.

What type of customer are you?
Please make sure you have all of the following available:

1. A USB drive with sufficient space (16GB+).
   The contents of this drive WILL BE LOST!
2. Windows 10 Enterprise media that matches your SRSv2 deployment kit.
   Enterprise customers can access Windows 10 Enterprise media from the Volume Licensing Service Center:
   http://www.microsoft.com/licensing/servicecenter
3. Any language pack (LP and/or LIP) files to be included.
   MPSA customers:         http://go.microsoft.com/fwlink/?LinkId=125893
   Other volume licensees: http://www.microsoft.com/licensing/servicecenter

Please do not continue until you have all these items in order.

Found deployment kit already downloaded.
Validating signature for SRSDeploymentKit-4.0.31.0.msi...
success.
Extracting the deployment kit...
done.
PS>TerminatingError(ConvertFrom-Json): "Invalid object passed in, ':' or '}' expected. (1982): {
    "MinimumCreateSrsMediaVersion":"1.4.0",
    "RequiredUpdates":{
        "KB4340917":"http://download.windowsupdate.com/d/msdownload/update/software/updt/2018/07/windows10.0-kb4340917-x64_ed5f586fa9d7064d61e45c523f20ba7fc1ff142a.msu"
    },
    "Drivers":{
        "MenuItems":{
            "Surface Pro 4":{
                "Action":"Download",
                "Targets":["https://download.microsoft.com/download/6/A/C/6ACB37C4-E4C1-4E0E-BBAE-AC7A0C303593/SurfacePro4_Win10_16299_1803301_1.msi"]
            },
            "Surface Pro (2017)":{
                "Action":"Download",
                "Targets":["https://download.microsoft.com/download/4/C/7/4C7DA85D-03DE-4B89-B8E0-386437331C46/SurfacePro_Win10_16299_1806007_3.msi"]
            },
            "Surface Pro Dock":{
                "Action":"Menu",
                "Targets":["Surface Pro 4", "Surface Pro (2017)"]
            },
            "Logitech SmartDock":{
                "Action":"Redirect",
                "Target":"Surface Pro Dock"
            },
            "Crestron SR":{
                "Action":"Redirect",
                "Target":"Surface Pro Dock"
            },
            "Polycom MSR":{
                "Action":"Redirect",
                "Target":"Surface Pro Dock"
            },
            "Lenovo Hub 500":{
                "Action":"Warn",
                "Message":"The Lenovo Hub 500 does not have a driver pack for this SRSv2 build. Continuing with no pre-installed drivers."
            },
            "SMART Room System":{
                "Action":"Warn",
                "Message":"The SMART Room System does not have a driver pack for this SRSv2 build. Continuing with no pre-installed drivers."
            },
            "Crestron RL 200":{
                "Action":"Warn",
                "Message":"The Crestron RL 200 does not have a driver pack for this SRSv2 build. Continuing with no pre-installed drivers."
            "HP Slice 2.0":{
                "Action":"Warn",
                "Message":"The HP Slice 2.0 does not have a driver pack for this SRSv2 build. Continuing with no pre-installed drivers."
            },
            "None":{
                "Action":"Warn",
                "Message":"Generating an image that will not pre-install drivers, by explicit request."
            },
            "LRS":{
                "Action":"Menu",
                "Targets":["SMART Room System", "Crestron RL 200"],
                "Variables":{"BIOS":true}
            }

        },
        "RootItem":{
            "Action":"Menu",
            "Targets":["Logitech SmartDock", "Crestron SR", "Polycom MSR", "Lenovo Hub 500", "LRS", "HP Slice 2.0", "None"]
        }
    }
}"
**********************
Windows PowerShell transcript end
End time: 20181031150316
**********************

**Comment by Travis-Snoozy** [comment]
Thanks for the report, and our apologies for the inconvenience. This issue should now be mitigated -- please re-run the script.

**Comment by Travis-Snoozy** [comment]
As an additional note -- please do not use PowerShell ISE to run the script. Future versions of the script will have an explicit check in place to prevent being run from PowerShell ISE (and in other ways that can lead to strange behaviors). For now, please either use a normal (64-bit, elevated) PowerShell prompt, or invoke the normal (64-bit) PowerShell.exe from an elevated context, supplying only the full or relative path to CreateSrsMedia.ps1.

**Comment by AndreaBarr** [comment]
@dmonti79 Did what Travis suggest fix this issue?

**Comment by dmonti79** [comment]
Unfortunately, no it didn't. What we had to do to get around it was add -raw when running the ConvertFrom-Json command.

as outlined here: https://github.com/janegilring/PSVersion/issues/1

Additionally, we also had to comment out most of the partitioning commands as we continued to get the following error as well:

Set-Disk : Not Supported

This was run on a Windows 10 1709 OS running Powershell Version 5.

**Comment by Travis-Snoozy** [comment]
Very well, I'll start from the start by downloading the script from its source, putting it in an empty directory, running it, and verifying the current functionality or lack thereof. Please stay tuned for steps and outcome.

**Comment by Travis-Snoozy** [comment]
And to reiterate: **do not use PowerShell ISE** to run CreateSrsMedia. If you have transcripts of other failures, that would be helpful, but only if those transcripts are for the original (completely unmodified, as-downloaded) CreateSrsMedia script. :)

**Comment by Travis-Snoozy** [comment]
I have verified that the original fault (the inability to parse the config.json) is not present when running the unmodified, currently-published script. Once the run is complete, I will publish the transcript and set of (non-)repro steps here. In the meantime, however, please delete any local modifications you have made to the script, download a fresh copy from the origin, and try again. If the problem persists for you, please publish the corresponding transcript to aid in my diagnostics. Thank you!

**Comment by Travis-Snoozy** [comment]
Aside from my poor Internet connection, I did not have any issues running the script.

1. Ensure that no copies of the script exist in my current Downloads folder
2. Download the script (https://go.microsoft.com/fwlink/?linkid=867842)
3. Open an elevated, 64-bit CMD prompt
4. Change to the download directory (in my case, "cd c:\users\v-trsnoo\Downloads")
5. Make a new directory for the download script (in my case, "mkdir CreateSrsMedia")
6. Move the script into that empty directory (in my case, "move CreateSrsMedia.ps1 CreateSrsMedia")
7. Change into the target directory (in my case, "cd CreateSrsMedia")
8. Run the script ("powershell .\CreateSrsMedia.ps1")
9. Answer the questions in order...
9.a. In response to OEM vs. Enterprise, "Enterprise"
9.b. In response to drivers to use, "5" (none, but any selection set should work)
9.c. In response to creating an image with no extra languages, "YES"
9.d. In response to which device to put the image on, in my case "0" (select whichever USB stick you actually want to use that's plugged into your system)
9.e. In response to where my Windows media is, in my case "e:" (select whichever driver or virtual drive holds the Windows 10 Enterprise source media you're using. The script will indicate what, if anything, is wrong with the source media, if it does not match what's needed).

Please find the transcript for the session below.

> **********************
> Windows PowerShell transcript start
> Start time: 20181102080639
> Username: REDMOND\v-trsnoo
> RunAs User: REDMOND\v-trsnoo
> Configuration Name: 
> Machine: SNOOZY-SP3 (Microsoft Windows NT 10.0.17134.0)
> Host Application: powershell .\CreateSrsMedia.ps1
> Process ID: 22012
> PSVersion: 5.1.17134.228
> PSEdition: Desktop
> PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17134.228
> BuildVersion: 10.0.17134.228
> CLRVersion: 4.0.30319.42000
> WSManStackVersion: 3.0
> PSRemotingProtocolVersion: 2.3
> SerializationVersion: 1.1.0.1
> **********************
> Transcript started, output file is C:\Users\v-trsnoo\Documents\PowerShell_transcript.SNOOZY-SP3.tKEiyu+X.20181102080639.txt
> Script version 1.4.1
> Downloading CreateSrsMedia...
> done
> Validating signature for update.ps1...
> success.
> 
> What type of customer are you?
> Please make sure you have all of the following available:
> 
> 1. A USB drive with sufficient space (16GB+).
>    The contents of this drive WILL BE LOST!
> 2. Windows 10 Enterprise media that matches your SRSv2 deployment kit.
>    Enterprise customers can access Windows 10 Enterprise media from the Volume Licensing Service Center:
>    http://www.microsoft.com/licensing/servicecenter
> 3. Any language pack (LP and/or LIP) files to be included.
>    MPSA customers:         http://go.microsoft.com/fwlink/?LinkId=125893
>    Other volume licensees: http://www.microsoft.com/licensing/servicecenter
> 
> Please do not continue until you have all these items in order.
> 
> Found deployment kit already downloaded.
> Validating signature for SRSDeploymentKit-4.0.27.0.msi...
> success.
> Extracting the deployment kit...
> done.
> This deployment kit is built for Windows build 10.0.17134.1.
> This deployment kit draws its drivers from %configsetroot%\AutoUnattend_Files\DistShare\Out-of-Box Drivers.
> 
> Please indicate what drivers you wish to use with this installation.
> [ 0] Logitech SmartDock
> [ 1] Crestron SR
> [ 2] Polycom MSR
> [ 3] Lenovo Hub 500
> [ 4] LRS
> [ 5] None
> Selected option 5.
> WARNING: Generating an image that will not pre-install drivers, by explicit request.
> Identifying language packs...
> ... done identifying language packs.
> Found update KB4340917 already downloaded.
> Validating signature for windows10.0-kb4340917-x64_ed5f586fa9d7064d61e45c523f20ba7fc1ff142a.msu...
> success.
> WARNING: THIS IS YOUR ONLY CHANCE TO PRE-INSTALL LANGUAGE PACKS.
> Because you are pre-installing an update, you will NOT be able to pre-install language packs to the image at a later point.
> You are currently building an image with NO pre-installed language packs.
> Are you ABSOLUTELY SURE this is what you intended?
> WARNING: PROCEEDING TO GENERATE SLIPSTREAM IMAGE WITH NO PRE-INSTALLED LANGUAGE PACKS.
> 
> Reminder: all data on the drive you select will be lost!
> 
> [ 0] SanDisk Cruzer Glide 3.0
> Selected option 0.
> 
> Creating Enterprise media.
> 
> Creating UEFI-compatible media.
> 
> Using SRSv2 kit:       C:\Users\v-trsnoo\Downloads\CreateSrsMedia\SRSDeploymentKit-4.0.27.0.msi
> Using driver pack:
> Using Windows media:   e:
> Using language packs:
> Using updates:
>     C:\Users\v-trsnoo\Downloads\CreateSrsMedia\windows10.0-kb4340917-x64_ed5f586fa9d7064d61e45c523f20ba7fc1ff142a.msu
> Writing stick:         SanDisk Cruzer Glide 3.0
> 
> Formatting and partitioning the target drive...
> PS>TerminatingError(New-Partition): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Not enough available capacity
> Activity ID: {f5034291-2fd8-4ad1-a320-9ac7edae012b}"
> done.
> Copying Windows...
> done.
> Copying the installation image...
> done.
> Mounting the installation image...
> done.
> Applying language packs...
> done.
> Applying updates...
> done.
> Cleaning up the installation image...
> Cleaning up the installation image...
> Cleaning up the installation image...
> done.
> Unmounting the installation image...
> done.
> Splitting the installation image...
> done.
> Injecting drivers...
> done.
> Copying Rigel build...
> done.
> Configuring unattend files...
> done.
> Selecting image...
> done.
> Cleaning up...
> done.
> 
> Please safely eject your USB stick before removing it.
> WARNING: DO NOT PRE-INSTALL LANGUAGE PACKS AFTER THIS POINT
> WARNING: You have applied a Windows Update to this media. Any pre-installed language packs must be added BEFORE Windows updates.
> **********************
> Windows PowerShell transcript end
> End time: 20181102095450
> **********************
> 

Once again, if you are able to repro an issue with an _unmodified_ version of the script, please post the corresponding transcript and I will attempt to repro the problem. **Do not** use PowerShell ISE to run the script, it will not work.

**Comment by dmonti79** [comment]
Hi Travis,

I was successful when following the directions in your last post. It should be noted that the steps outlined here: [Prepare the installation media](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/console#prepare-the-installation-media) are extremely vague in comparison. 

No where in there does it mention not using Powershell ISE or even to use cmd prompt rather than Powershell.  

Either way, we were able to create a clean installation media. 

Thank you for your help.

**Comment by yogkumgit** [comment]
@dmonti79  Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link https://www.youtube.com/watch?v=puuOy0sEg1Y

We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with your valuable piece of information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by MaksymLazorenko** [comment]
HI 

Could help me with this error. This error occurs when I try to prepare the installation media.

I do everything indicated in the instructions.

PS>TerminatingError(Invoke-Native): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Command '& robocopy /mir 'd:\SW\SW2\SW_DVD5_Win_Pro_Ent_Edu_N_10_1803_64BIT_English_-2_MLF_X21-79647' 'F:\' /R:0 /xf install.wim' failed test '$_ -lt 8 -and $_ -ge 0' with code '11'."

See the LOG below:
**********************
Windows PowerShell transcript start
Start time: 20190604152529
Username: 
RunAs User: Administrator
Configuration Name: 
Machine: PC (Microsoft Windows NT 10.0.17134.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 39944
PSVersion: 5.1.17134.590
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17134.590
BuildVersion: 10.0.17134.590
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\Administrator\Documents\PowerShell_transcript.ICGUA-PC-541.xCBluz0D.20190604152529.txt
Script version 1.4.3
Downloading CreateSrsMedia...
done
Validating signature for update.ps1...
success.

919C06207B8A9C6B71423B7916AB61D3F6EF6DC7BD04AD4EC9CB172053B3317991E8274D1DC0F6335D27B8F4E299F7336FEE6F5966624F2A5815A7EB8293884E
68308

What type of customer are you?
What type of customer are you?
Please make sure you have all of the following available:

1. A USB drive with sufficient space (16GB+).
   The contents of this drive WILL BE LOST!
2. Windows 10 Enterprise media that matches your SRSv2 deployment kit.
   Enterprise customers can access Windows 10 Enterprise media from the Volume Licensing Service Center:
   http://www.microsoft.com/licensing/servicecenter
3. Any language pack (LP and/or LIP) files to be included.
   MPSA customers:         http://go.microsoft.com/fwlink/?LinkId=125893
   Other volume licensees: http://www.microsoft.com/licensing/servicecenter

Please do not continue until you have all these items in order.

Found deployment kit already downloaded.
Validating signature for SRSDeploymentKit-4.0.85.0.msi...
success.
Extracting the deployment kit...
done.
This deployment kit is built for Windows build 10.0.17134.1.
This deployment kit draws its drivers from %configsetroot%\AutoUnattend_Files\DistShare\Out-of-Box Drivers.

Please indicate what drivers you wish to use with this installation.
[ 0] Logitech SmartDock
[ 1] Crestron SR
[ 2] Polycom MSR
[ 3] Lenovo Hub 500
[ 4] LRS
[ 5] HP Slice 2.0
[ 6] Crestron Flex
[ 7] None
Selected option 0.
[ 0] Surface Pro 4
[ 1] Surface Pro (2017)
[ 2] Surface Pro 6
Selected option 2.
Downloading driver...
done
Validating signature for SurfacePro6_Win10_17134_1808507_3.msi...
success.
Extracting SurfacePro6_Win10_17134_1808507_3.msi...
done.
Identifying language packs...
... done identifying language packs.
Found update KB4340917 already downloaded.
Validating signature for windows10.0-kb4340917-x64_ed5f586fa9d7064d61e45c523f20ba7fc1ff142a.msu...
success.
WARNING: THIS IS YOUR ONLY CHANCE TO PRE-INSTALL LANGUAGE PACKS.
Because you are pre-installing an update, you will NOT be able to pre-install language packs to the image at a later point.
You are currently building an image with NO pre-installed language packs.
Are you ABSOLUTELY SURE this is what you intended?
WARNING: PROCEEDING TO GENERATE SLIPSTREAM IMAGE WITH NO PRE-INSTALLED LANGUAGE PACKS.

Reminder: all data on the drive you select will be lost!

[ 0] KINGSTON SA400S37240G
[ 1] JetFlash Transcend 16GB
Selected option 0.

Creating Enterprise media.

Creating UEFI-compatible media.

Using SRSv2 kit:       C:\Users\administrator\Downloads\SRSDeploymentKit-4.0.85.0.msi
Using driver packs:
    C:\Users\administrator\Downloads\SurfacePro6_Win10_17134_1808507_3.msi
Using Windows media:   d:\SW\SW2\SW_DVD5_Win_Pro_Ent_Edu_N_10_1803_64BIT_English_-2_MLF_X21-79647
Using language packs:
Using updates:
    C:\Users\administrator\Downloads\windows10.0-kb4340917-x64_ed5f586fa9d7064d61e45c523f20ba7fc1ff142a.msu
Writing stick:         KINGSTON SA400S37240G

Formatting and partitioning the target drive...
done.
Copying Windows...
PS>TerminatingError(Invoke-Native): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Command '& robocopy /mir 'd:\SW\SW2\SW_DVD5_Win_Pro_Ent_Edu_N_10_1803_64BIT_English_-2_MLF_X21-79647' 'F:\' /R:0 /xf install.wim' failed test '$_ -lt 8 -and $_ -ge 0' with code '11'."
>> TerminatingError(Invoke-Native): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Command '& robocopy /mir 'd:\SW\SW2\SW_DVD5_Win_Pro_Ent_Edu_N_10_1803_64BIT_English_-2_MLF_X21-79647' 'F:\' /R:0 /xf install.wim' failed test '$_ -lt 8 -and $_ -ge 0' with code '11'."
>> TerminatingError(Invoke-Native): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Command '& robocopy /mir 'd:\SW\SW2\SW_DVD5_Win_Pro_Ent_Edu_N_10_1803_64BIT_English_-2_MLF_X21-79647' 'F:\' /R:0 /xf install.wim' failed test '$_ -lt 8 -and $_ -ge 0' with code '11'."
**********************
Windows PowerShell transcript end
End time: 20190604152908
**********************

**Comment by URONVN** [comment]
@Travis-Snoozy 
Currently, can you run the CreateSrsMedia.ps1 script on Windows 10?
It didn't work for me.
