### ISSUE TITLE
The shortcut doesn't work ctrl+shift+alt+1

### ISSUE THREAD

**Issue by Patryk-beep** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10057]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97d5e6d3-b7e0-d79f-0dea-ed423186a157
* Version Independent ID: ec6e68aa-552f-ab45-3c8e-92eff526b173
* Content: [Configure log files for monitoring and troubleshooting in Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/log-files)
* Content Source: [Teams/log-files.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/log-files.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @Patryk-beep, thank you for your feedback.

This is a well-known keyboard shortcut. I've tried it in the old and new client and it works. The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information provided at [Get support](https://docs.microsoft.com/microsoft-365/business-video/get-help-support). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
