### ISSUE TITLE
No Admin menu when creating new Team

### ISSUE THREAD

**Issue by thunem** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1008]
I got a azure runbook that are provisioning teams. But when creating new Teams I do not get the "owner" menu. I've checked the group and I'm owner of that group. 

The only menu I got is this.
![image](https://user-images.githubusercontent.com/8638891/47906356-59022a00-de89-11e8-955b-729fb0383740.png)

Is there a delay or something because I created alot of teams yesterday and today I got the admin menu

**Comment by AndreaBarr** [comment]
@thunem Thank you for this inquiry. 

It could be that there is a delay or something but I am not sure. Let me get this over to the Teams team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by CrystalThomasMS** [comment]
After discussing this with the team, it is expected that it can take up to 2 hours for changes to group membership to reflect in Teams, and that is dependent on there being some activity in that team... so I hope your issue was resolved soon after your posted it. If you can point us to the location in our documentation where you were reading about this feature or hoping to find answers about your issue, we can add a note about delays that might occur.
