### ISSUE TITLE
Explain first the setup policies

### ISSUE THREAD

**Issue by geektocore** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10307]
I found a good explanation of this policies with examples at https://learn.microsoft.com/en-us/microsoftteams/app-policies#app-setup-policies . This article doens't have it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91604a-35b0-dfbb-55b2-b601cb0841b0
* Version Independent ID: 84bcd0d7-b4ed-f13e-c84b-2ec6a7661ae9
* Content: [Manage app setup policies in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-app-setup-policies)
* Content Source: [Teams/teams-app-setup-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/teams-app-setup-policies.md)
* Service: **msteams**
* Sub-service: **teams-apps**
* GitHub Login: @ashishguptaiitb
* Microsoft Alias: **guptaashish**

**Comment by ashishguptaiitb** [comment]
Thanks @scanum for triaging. I'm self-assigning as I have some related updates already made.

Thanks @geektocore . **Current resolution**: We are adding the concepts upfront, in the otherwise prescriptive article. To do so, we are adding a one-paragraph description + a backlink to the above article.
**Future consideration**: In addition, we are considering one of the two options: 1. Just have a one-para description and backlink while retaining the conceptual article linked above OR 2. Remove the conceptual article and move the explanations to the individual articles about the 2 policies. We aren't taking any call just yet but will do some A/B tests to verify what works best for all of our readers. 

Thanks again. We appreciate you sharing your opinion and initiating this discussion. For now, I'm closing this issue with the current consideration. I shall keep you posted on the future changes on this topic, if any.

**Comment by ashishguptaiitb** [comment]
We've already implement the approach number 1. Need further consideration before we implement the second approach that I mentioned above.

**Comment by geektocore** [comment]
Thanks for the update.
