### ISSUE TITLE
Ambigious information provided

### ISSUE THREAD

**Issue by KennethMLdk** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10425]
In the section https://learn.microsoft.com/en-us/microsoftteams/direct-routing-plan#microsoft-365-office-365-and-office-365-gcc-environments the following is stated:
The FQDNs sip.pstnhub.microsoft.com, sip2.pstnhub.microsoft.com, and sip3.pstnhub.microsoft.com are resolved to IP addresses from the following subnets:

- 52.112.0.0/14
- 52.122.0.0/15

In the section https://learn.microsoft.com/en-us/microsoftteams/direct-routing-plan#microsoft-365-office-365-and-office-365-gcc-environments-1 the following is stated:
In the Microsoft 365, Office 365, and Office 365 GCC environments, the IP address ranges are:

- 52.112.0.0/14 (IP addresses from 52.112.0.0 to 52.115.255.255)
- 52.120.0.0/14 (IP addresses from 52.120.0.0 to 52.123.255.255)

According to Office 365 URLs and IP Addresses (https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#skype-for-business-online-and-microsoft-teams), 52.122.0.0/15 is correct and 52.120.0.0/14 is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d964547-6b38-cc5f-6b2b-7a50a1c7dae9
* Version Independent ID: fa5850f9-1b92-9727-c344-bcffc227cbd6
* Content: [Plan Direct Routing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/direct-routing-plan)
* Content Source: [Teams/direct-routing-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/direct-routing-plan.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @KennethMLdk 

I checked internally and I was let known that _the PSTN ranges used won’t exactly match up with the other Office client ranges. This is why we need the full 52.120.0.0/14 in the documentation. The Teams client or any customer will only connect directly to endpoints in the 52.122.0.0/15 range, but the customer-hosted backend components (SBCs) will need to be able to talk to the whole 52.120.0.0/14 range – so that is the correct one and should be left in the documentation as is._

Thank you,
