### ISSUE TITLE
Page is outdated and missing key information

### ISSUE THREAD

**Issue by michaelblumenthal** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10655]
This page does not explain the various settings of the Use New Teams Client drop down.
This page is linked from https://admin.teams.microsoft.com/policies/updatemanagement
The policy values for that drop down are explained in https://learn.microsoft.com/en-us/microsoftteams/new-teams-deploy-using-policies?tabs=teams-admin-center , which is listed in the Related Topics section, but it's not obvious when you are on the "Microsoft Teams Public preview" page that you need to go to the other page to learn about the options for the Use New Teams Client dropdown.
Given that this page is about the public preview, and New Teams is Generally Available, this page is obsolete and should probably just redirect to https://learn.microsoft.com/en-us/microsoftteams/new-teams-deploy-using-policies?tabs=teams-admin-center#set-the-policies-to-upgrade-to-the-new-teams-client

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-US/microsoftteams/public-preview-doc-updates?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
