### ISSUE TITLE
Wrong Limitation in Text for max. Teams Channels (old 200 | new 1,000)

### ISSUE THREAD

**Issue by PhilvdHeide** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10658]
In the last paragraph, it says: "The 30 private channel limit is in addition to the 200 standard channel limit per team."
[Text Anker](https://learn.microsoft.com/en-us/microsoftteams/private-channels#private-channel-limitations
)
This is the wrong limiation since Oktober 2023 or something: it is 1,000 now
Source: https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-and-channels

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce34b12b-aa50-608b-bbfa-a1fb4bb79f8d
* Version Independent ID: 9ddeb6f4-f30a-1e72-fc94-ae66def91f40
* Content: [IT Admins - Private channels in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/private-channels)
* Content Source: [Teams/private-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/private-channels.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
