### ISSUE TITLE
Incorrect SkuID for ENTERPRISEPACK_STUDENT

### ISSUE THREAD

**Issue by ci3n** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#10662]
It appears that the last character is missing from the `ENTERPRISEPACK_STUDENT` SkuID.

On this page it is `8fc2205d-4e51-4401-97f0-5c89ef1aafb`, while it should be `8fc2205d-4e51-4401-97f0-5c89ef1aafbb` according to [O365-EDU-Tools/EDU Storage Contributions/Microsoft-EDU-Storage-Entitlements-by-SKU.csv](https://github.com/OfficeDev/O365-EDU-Tools/blob/4d6525bc312523a415b765451ff0907747bd9ad7/EDU%20Storage%20Contributions/Microsoft-EDU-Storage-Entitlements-by-SKU.csv#L141).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae22e4df-3f88-8c54-c55e-a3cd4f720cbc
* Version Independent ID: 3be05aac-9860-e78c-aca7-c62de044c48b
* Content: [Education SKU reference - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/sku-reference-edu)
* Content Source: [Teams/sku-reference-edu.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/public/Teams/sku-reference-edu.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
