### ISSUE TITLE
Post Upgrade expectations

### ISSUE THREAD

**Issue by Derek-SST** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1092]
Our organization was just upgraded to Team from S4B, and none of our contacts were migrated from S4B.  It appears I can only add internal contacts for Chat (in AD) and cannot add external contacts.  Is this the expected functionality?  Very disappointed in this 'upgrade'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7b32af2-59db-a872-6ed4-fc7b4cd910b3
* Version Independent ID: 38fd3a1a-ee6d-dd63-0de9-5f726d7419cf
* Content: [Skype for Business to Microsoft Teams upgrade](https://docs.microsoft.com/en-US/MicrosoftTeams/journey-skypeforbusiness-teams?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/Journey-SkypeforBusiness-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Journey-SkypeforBusiness-Teams.md)
* Service: **msteams**
* GitHub Login: @dearbeen
* Microsoft Alias: **dearbeen**

**Comment by LolaJacobsen** [comment]
@dearbeen - how to respond?

**Comment by dearbeen** [comment]
Where is this question being asked @LolaJacobsen? They should open a support ticket or work with their account team on these issues. If they didnt enable federation they would not be able to add external contacts... It's hard to address without looking in more detail. A support ticket is the best way to go

**Comment by RabidNinjaGerbil** [comment]
Good afternoon, I'm having a similar issue on multiple accounts I have.  For instance, if I right-click on the "..." next to a group name and select "Add a contact to this group" and type-in an external email address it displays "We didn't find any matches.  Talk to your IT admin about expanding the scope of your search."  No more.  I can instantiate an external conversation by using the new message button, but it displays only the full email address, not a conical name associated with the GAL, as it would in SfB - or in my local address book.

Further, I can't add a contact to a list directly from the chat window as I could in SfB.  I *can* add external contacts to favorites by clicking the "..." and selecting "Add to favorite contacts" - noting that SfB offered a list of the groups I'd like to otherwise add the contact to.

More over, if an external contact is a Teams-only user, their presence information is *not* displayed in Skype.  They appear as offline.  You can start and continue chats with them, but they report as "offline", always.

I can't add images to external chats.  That's annoying.  I can't provide on-the-fly images or photos with external contacts.  That's been a basic chat feature since the 90's...  (Please tell me there isn't a "Millennium Edition" of Teams coming out soon...).

As Derek said, kind of disappointing.  A lot of basic features that existed in Skype for Business, Lync, and Communicator, do not exist in Teams.  Understandably, the backend with Teams is more complicated; but as folks are forced onto the new platform these little issues are going to cause great noise.

**Comment by RabidNinjaGerbil** [comment]
Also, as a point-of-reference, External Access is enabled on *both* entities; both "External access" and "Users can communicate with external Skype users".  Most noteworthy, this all worked, and continues to work in SfB, just not Teams.

**Comment by reinoutD** [comment]
As time goes one, in IT you have to adapt changes of course, however I really think it is a mistake to leave Skype and make Teams the new skype. In skype you are reachable and can easily share screens etc, even if someone isn't in your contact lists at that moment. In Teams I first need to add someone into the team before I can talk to that person.. This is bad! I do not want only see conversations in the team i'm currently on, I want to be able to get reached if someone needs me( Or when I need someone else, I just want to send him/her a message). No I have to constantly change from team to team to see if I missed messages... What a disappointment... Don't mistake I work on O365 since BPOS time, and I always loved to work with it, and actively spread the services to others, but im not so sure about this...

**Comment by Derek-SST** [comment]
UPDATE:  I did submit a support ticket on this issue, and received this response:

"Contact migration is actually supported from Skype for Business to MS Teams. **However, only internal contacts are migrated to MS Teams leaving behind all federated/pic contacts. External/Federated contact migration is not supported yet and will come in future.**

Apologies for any inconvenience this may have caused you. You may also vote about having this option in our User voice page. See link below.  (https://microsoftteams.uservoice.com/forums/555103-public/suggestions/33116188-import-groups-contacts-from-skype-for-business)"

My reply was:  While I understand your response, it is still disappointing and frankly a bit misleading when I am being told that I can switch from S4B to Teams “and your contacts will be there”.  There should be an upfront explicit disclosure that only internal contacts are migrated and not external.  This seems like Teams was forced upon us before it was ‘fully baked’ with existing S4B functionality.  You can close the ticket, but I am not pleased.

**Comment by scnbwy** [comment]
经过我的测试需要在Office365的Teams管理控制中心手动添加要与外部通信的域名，在S4B Online中默认是可以和其余所有Office365外部域名进行通信的，但是Teams看起来不支持。

**Comment by get-itips** [comment]
Hi @Derek-SST thanks for your feedback, we really appreciate it.
It seems that your question is more suitable to Support services, @yogkumgit will gently direct you to that resource.
Thank you

**Comment by yogkumgit** [comment]
@Derek-SST  Thank you very much for posting this issue. Considering the nature of the issue  and as advised by @get-itips please open one more service ticket in your tenant and follow with them for the resolution. We understand your disappointment but support is the right platform for this issue. Also appreciate your concluding remark that this issue can be closed.

However,   we will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
