### ISSUE TITLE
Two Tenants Both In Teams Only Mode

### ISSUE THREAD

**Issue by dawander** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1284]
Should tenants be able to communicate externally (all settings are on to allow) between teams only tenants?  We can't get this to work and support says "it's like this right now" with not much else to offer.  It used to work between S4B tenants but no longer in teams only mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53d0cb0-90a6-5932-f78e-7de6fcc4d481
* Version Independent ID: 3d468027-cc37-5199-32ec-819bf62b2caa
* Content: [Understand coexistence and interoperability of Skype for Business and Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability)
* Content Source: [Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md)
* Service: **msteams**
* GitHub Login: @lsOmi
* Microsoft Alias: **lsomi**

**Comment by zx3-at** [comment]
To our horror, we too discovered that Teams does NOT allow chat from federated (external domain added and allowed) external tenant! You would have to "switch" login from YOUR tenant to your partner/customer tenant in order to even be aware that the external user was trying to chat with you; this is a deal-breaker, and a renders Teams as useless when compared to Skype (where we can chat with ANYONE of our external clients/partners without need to "switch"). FYI: "switching" in Teams is a deceptive terms which actually means "we're going to sign you OUT of your organization's tenant and sign you IN to your chosen partner/customer tenant" - and your visibility will show as "unavailable" in every Team tenant EXCEPT the one you're currently signed in to! Madness by design, and it will be the ultimate downfall of Teams. Sad.

**Comment by dariomws306** [comment]
Hi @dawander and @zx3-at , thank you four your comment.

It's true, as you can see in a note in next article it's still not supported:
https://docs.microsoft.com/en-us/microsoftteams/let-your-teams-users-communicate-with-other-people

Please consider votting on user voice about this:
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/20566714-federation
https://microsoftteams.uservoice.com/forums/555103-public/suggestions/33925849-federation

Thank you!

**Comment by yogkumgit** [comment]
@dawander  Thank you very much for your kind feedback. As @dariomws306 advised please visit the given User voice links. Concerning team will evaluate and take the appropriate action, as per their schedule. Thanks again for taking out some time and sharing your feedback
