### ISSUE TITLE
Broadcast meeting hybrid supported modalities

### ISSUE THREAD

**Issue by ThomasBIDAULT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1339]
Could you please precise which role are supported with meeting broadcast and a user homed On-premises in the environment described in the article. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98aadf85-9538-d253-04e8-6731aa91f443
* Version Independent ID: a9bc7b52-ccde-6be1-4742-51692a0da938
* Content: [Configure your on-premises deployment for Skype Meeting Broadcast](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/configure-skype-meeting-broadcast)
* Content Source: [Skype/SfbServer/deploy/configure-skype-meeting-broadcast.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/configure-skype-meeting-broadcast.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws306** [comment]
Hi @ThomasBIDAULT , thank you for your feedback.

Could you elaborate further on this issue? Thanks!

**Comment by scanum** [comment]
@ThomasBIDAULT  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by ThomasBIDAULT** [comment]
> Hi @ThomasBIDAULT , thank you for your feedback.
> Could you elaborate further on this issue? Thanks!

In this article, there is no clear statement about the supported role for user homed on-premises using broadcast Meeitng. For instance, is it supported for an on-premises user to organize a broadcast meeting ? Is it supported for an on-premises user to produce or present a broadcast meeting ?

**Comment by dariomws306** [comment]
@ThomasBIDAULT Do you find some limitations for onpremises users?

Skype Meeting Broadcast service should be the same for online and onpremises users. Both should enter to the portal and they should have the same experience:
https://support.office.com/en-us/article/what-is-a-skype-meeting-broadcast-c472c76b-21f1-4e4b-ab58-329a6c33757d?ui=en-US&rs=en-US&ad=US

Enable it for online are onpremises are similar:
https://docs.microsoft.com/SkypeForBusiness/set-up-your-network-for-skype-meeting-broadcast/set-up-your-network-for-skype-meeting-broadcast?redirectSourcePath=%252fen-US%252farticle%252fSet-up-Skype-for-Business-Online-for-Skype-Meeting-Broadcast-dfa736b9-4920-4f48-b8c0-b5487ec6086f
Both don't specify limitations or features because both have me same features you can see in the first article.

Hope this answer your question.

**Comment by scanum** [comment]
@ThomasBIDAULT  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
