### ISSUE TITLE
CAP licence doesn't include Teams

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1341]
The CAP SKU doesn't include a Teams licence, only Skype for Business Online (Plan 2). Is this going to be updated to include a Teams licence?
Either way, I think the documentation should make this point clear

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ab5215-f24f-75cf-bb92-16ac0ff5e5ca
* Version Independent ID: 701cc58f-d2ea-cbb6-f5fc-47b9fbfb1119
* Content: [Set up the Common Area Phone license for Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/set-up-common-area-phones)
* Content Source: [Teams/set-up-common-area-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-common-area-phones.md)
* Service: **msteams**
* GitHub Login: @lolaj
* Microsoft Alias: **lolaj**

**Comment by dariomws306** [comment]
Hi @thommck , thank you for your feedback.

CAP license doesn't include Teams license neither SfBO license. It's a special license for CAP wich include Phone System license and you need to add calling plans.

**Comment by thommck** [comment]
That's not accurate. We are using the CAP bundle on all our SRS bundle  (this approach was recommended by our Microsoft rep at the time). Anyway, in answer to my own question, Teams got included in CAP earlier in the month

**Comment by dariomws306** [comment]
Hi @thommck , it includes the SfBO/Teams services to connect a CAP to Office 365 but it's not a standard SfBO/Teams license that you can assign to users. That is the reason why I think I cannot add something like "it includes a SfBO/Teams license".
Let me double check with the author or product group.

Also I see that SRS articles should be updated to include the new "Meeting Room System Licence".

**Comment by dariomws306** [comment]
Hi @lolaj, Could you kindly help us with this? Thanks in advance!

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@LolaJacobsen Hi Lola any updated on this?

**Comment by tonysmit** [comment]
@jambirk as an fyi.

So, this is a little complicated, because it all depends on the scenario and the "other licenses" you will need per room device. For all scenarios, a single certified room device you create a user account and assign Meeting Room license (which includes SFBO Plan 2, Microsoft Teams, Phone System and Audio Conferencing plus Intune for managing the device). Then it branches out into these scenarios.

Notice that these are NOT Teams users that are dialing in, meaning they aren't using the Teams or Skype for Business app.

**Scenario 1:** You have users that want to dial in using a phone into a meeting. In this case, each user (the device already has an A/C license) that organizes a meeting will need assigned an Audio Conferencing license. Phone numbers (shared and dedicated) from the conferencing bridge will be included and put in the invite to the meeting. A user uses a phone and dials the PSTN number (coordinates) on the invite to connect to the meeting.
**Scenario 2.** A user wants to be able to call into the room using their phone and connect to the meeting room's PSTN phone number so they can join the meeting. In this case, additionally you need a Calling Plan and a phone number to be assigned to the user for the device.
**Scenario 3.** You want to dial out on the device to a PSTN number to add a user on their phone to a meeting. In this case, if the calls goes to a work number that's been assigned, they will need a Calling Plan and a phone number to be assigned to them If it's a call to a mobile/cell phone, the Calling Plan isn't required because it's a call directly to their mobile/cell.
**Scenario 4.** You have a user that wants dial in using their phone but then dial out to another person's phone number to attend the meeting.  In this case, additionally you need a Calling Plan for the person initiating the call and a phone number to be assigned to them as well.

** Note: ** In all cases when a Calling Plan is required, you should (highly recommended) assign a Communication Credits license to them and add money to your balance.

You were directed to use the CAP license because at the time we didn't have a Meeting Room license. And that was the only way you could have a phone number for the device was doing it the "CAP way". Now, the CAP license should not be used for certified meeting devices, instead use the new Meeting Room license. However, it kinda works the same way. The Meeting Room license includes Phone System license, but if you want people to connect using their phone (not the Teams app), you will need Calling Plan and assign the phone number.

To be clear, the "SFB services" is not a license type and "Teams services" are added now. The reason SFB 2 (and Teams) is part of this is Meeting Room license is because this license is required for Skype for Business users that have a Phone System and a Calling Plan.

CAP is a special license that includes a Phone System license but doesn't include a Calling Plan (domestic or domestic and international). So you need to create a single active user,  buy a single CAP license and a Calling Plan for the user and assign those licenses to that active user. Then you must also assign a phone number to user that has the correct licenses.

**Comment by scanum** [comment]
@thommck Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
