### ISSUE TITLE
Outdated information, and a bit confusing text

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1371]
Hi,
This page seems to be very much like outdated. Skype service name is not anymore "Skype for Business Server". The new name seems to be "**Skype for Business Online**". Same goes to Exchange, it is not anymore "Exchange 2013". but most likely "**Office 365 Exchange Online**"

Also this sounds a bit strange: "_...If you later need to delete that certificate..._". Would be nice to see some examples when it should be removed, like renewing the cert? And is it actually **a certificate** you delete? CMDLet at least is: Remove-**MsolServicePrincipalCredential**

Could you please also explain how to check what is the current certificate in use? It is very hard if I cannot verify the current certficate like it seems with Exchange: 
`PS C:\> Get-MsolServicePrincipalCredential -AppPrincipalId 00000002-0000-0ff1-ce00-000000000000

cmdlet Get-MsolServicePrincipalCredential at command pipeline position 1
Supply values for the following parameters:
ReturnKeyValues:

Type      : Asymmetric
Value     :
KeyId     : 0ddff294-2fcb-48f7-8b07-e41b7532af40
StartDate : 6.12.2014 10:03:57
EndDate   : 10.11.2019 10:03:57
Usage     : Verify
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 263b9c6e-b581-5b51-0bce-76fa12437e4f
* Version Independent ID: be5c7725-f60d-3727-9602-c3df4957be71
* Content: [Configure server-to-server authentication for a Skype for Business Server hybrid environment](https://docs.microsoft.com/en-us/skypeforbusiness/manage/authentication/configure-a-hybrid-environment?toc=/SkypeForBusiness/toc.json&bc=/SkypeForBusiness/breadcrumb/toc.json)
* Content Source: [Skype/SfbServer/manage/authentication/configure-a-hybrid-environment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/authentication/configure-a-hybrid-environment.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hi @Petri-X thanks for your feedback.
We really appreciate it.
We will improve the article based on your comments.
Thanks!

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Petri-X** [comment]
One additional proposal for your processes. Keep these issues open until they are really fixed. It would be much easier for you to just close the case and like never finalizing the updates. Also it would be easier to show Microsoft management that there are not so many issues open when you are closing these without fix.

**Comment by scanum** [comment]
@Petri-X  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue with details on what information is missing.

**Comment by Petri-X** [comment]
@scanum 
The document says; 
"_11/14/2018 4 minutes to read Contributors_"
So I believe the document has not change at all yet, or correct me if I'm wrong.

If you say the document has not been updated yet, then how you could say "**the issue has been resolved**"?

**Comment by get-itips** [comment]
@Petri-X How are you? Hope you are doing good! As my reply in this thread says, _we appreciate your feedback and we will improve this article based on your comments_, I already created a pull request yesterday to clarify the information on this article based on your feedback (That's why @scanum consider this as resolved), but it takes time for these changes to go on the live version of the article. 

Hope this info has clarified the reason for the state of this issue.

**Comment by Petri-X** [comment]
@get-itips 
Yes, that clarifies the case and I have heard same explanation from other issues as well. But step on my shoes: Until your process has finalized and the "pull request" has pushed something out, the issue is not solved for your customers.

This is much more of philosophic question than a real technical issue :) If you keep this issue open till updates are done, you make this much more transparent for us. Today it is so, that you say: to be fixed and case closed, but still after six months the issue is still there.  Yes, I know the queues are extremely long, but still it makes not transparency for your customers of the progress. Also when next customer reads this article, she or he is unable see if the fixes has been done to the content already.

And as I wrote, this was only a proposal for improving the transparently of the issues.

**Comment by kenwith** [comment]
@Petri-X - this is great feedback for improving transparency. My mission is to open source these docs and make process fully transparent. We are making progress. :)

To get any updates the community makes to 'live' site on docs.microsoft.com there is one more step. There is a private GitHub repository (it is just the same repository with the -pr at the end of name but you have to be on Microsoft corp net to see it). The original reason for this one is that there is a review.docs.microsoft.com site that loads content from it. There isn't really a reason it should be 'private' but that site needs login to get access and I am not a fan of the private anyways and am trying to just use the public repository. But at any rate that private repository is there so someone has to go to that repository and merge the 'master' branch to the 'live' branch and then it goes live on docs.microsoft.com. At this point everyone just uses the public repo but there is still that step so that is why there is some delay. My goal is to get the docs.microsoft.com to pull directly from the public repo so that we don't have that step and avoid this confusion and increase transparency. As you can imagine it is taking me some time in a large company though but we will get there. I see the teams that own those systems making the progress on it and trying to make the changes it just takes time because so many other orgs and teams use them. 

Hope that helps and keep up the great feedback. It is appreciated!

**Comment by kenwith** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/1829

**Comment by kenwith** [comment]
I merged and as soon as sync happens with that private repo I will merge master to live and it should go to docs.microsoft.com and date should update with new publish.

**Comment by Petri-X** [comment]
@kenwith 
Oh ! That was amazing reply! Big thanks to share it. And yes, I know the troubles on large companies =)
Thumps up and lets make the world a bit better place step by step!

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Petri-X  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
