### ISSUE TITLE
CQD regional network metrics

### ISSUE THREAD

**Issue by mgarza1812** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#139]
Does CQD take into account regional site metrics listed above? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e291cc-5a58-f435-d6c3-b8ba4973f13a
* Version Independent ID: 9ba1e56d-54b2-05d6-fe15-95677e2c0967
* Content: [Media Quality and Network Connectivity Performance](https://docs.microsoft.com/en-us/SkypeForBusiness/optimizing-your-network/media-quality-and-network-connectivity-performance)
* Content Source: [Skype/SfbOnline/optimizing-your-network/media-quality-and-network-connectivity-performance.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/optimizing-your-network/media-quality-and-network-connectivity-performance.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by tonysmit** [comment]
@williamlooney can you assist on this? Thanks, Tony

**Comment by williamlooney** [comment]
@mgarza1812 - Hi Mark. I don't understand your question
- Which metrics are you referring to?
- What do you mean by "take into account"?

**Comment by williamlooney** [comment]
CQD does not cover the exact same measurements as covered in this doc. This doc outlines requirements for the network performance to the edge of Microsoft network. CQD is based on data collected for real calls which has E2E network metrics and does not segment the traffic to the edge of Microsoft network.

**Comment by williamlooney** [comment]
The targets for measuring to Azure VMs are provided because some customers are leveraging solutions to assess network performance can not test directly to the Microsoft Network Edge site and instead need an entity in VM to test against.  If you are using a solution that tests against the Microsoft Network Edge site directly, the VM targets are not applicable. I believe this is described in the text in "Measuring Network Performance using Azure VMs" section.

There is no direct correlation to the Azure VM testing and what you would see in CQD or other tools.

**Comment by mgarza1812** [comment]
Thanks

"The greater the resolve, the greater the result." -mg

4077165066
