### ISSUE TITLE
Shows up as "Program" under Startup tab of Task Manager

### ISSUE THREAD

**Issue by MelQL** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1529]
If you install the machine based teams installer, it adds this to the registry: value name = TeamsMachineInstaller, value data = %ProgramFiles%\Teams Installer\Teams.exe --checkInstall --source=default to Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run.  That causes an entry just called "Program" under the Task Manager Startup tab.  It would be helpful if Teams could be properly identified under the Task Manager Startup tab instead of just "Program".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Microsoft Teams using MSI via SCCM](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @Lester-Hewett
* Microsoft Alias: **lehewe**

**Comment by thedrum808** [comment]
Agreed! I've noticed this on a few machines, and it's quite unnerving to see "Program" listed there.

**Comment by scanum** [comment]
@officedocsbot unassign @yogkumgit

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@MelQL Thank you for reaching out and helping improve MS Docs.  I'll have the team look into this.

**Comment by scanum** [comment]
@MelQL  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by dwiller11** [comment]
Any update on this? I'm not able to escalate this as a tenant because I don't have tenant access. Seems like an issue with the installer, not a tenant-specific issue. It's a bit sloppy for the teams installer to be leaving this behind. Also, the path it leaves is not even valid because the files no longer exist but also because it puts double quotes right after the c:\program in the path

"C:\Program" Files\Teams Installer\Teams.exe --checkInstall --source=PROPLUS

**Comment by Hillbi11y** [comment]
I just found this on daughters PC.   It's still there.  It's hard not to say bad things about MS...

**Comment by mattou07** [comment]
I was about to submit my own issue but will add my contribution to this thread:

![image](https://user-images.githubusercontent.com/11179749/79730112-429f9680-82e8-11ea-9c18-f0b4c715b940.png)
Is this a valid Start up entry for Microsoft Teams seems a little odd to me? Especially the misplaced " in the path.

Additionally its targeting the wrong program files folder, when I look on disk its located in the (x86) folder:
![image](https://user-images.githubusercontent.com/11179749/79730193-606cfb80-82e8-11ea-9538-ef27967a2936.png)

**Comment by ddawson100** [comment]
Adding the Command line column in Task Manager finally gave me a bit of peace of mind that this was a legitimate "Program" but it would certainly be nice to have this fixed. Really wondering how this happened with a Microsoft application.

![Program](https://user-images.githubusercontent.com/14896790/84789151-ef7f5280-afbd-11ea-92a5-0285220ad27b.PNG)

I found how to correct this manually so it appears correctly in the Startup tab. Just change the reg entry in HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run 

from: %ProgramFiles%\Teams Installer\Teams.exe --checkInstall --source=PROPLUS 
to: %ProgramFiles(x86)%\Teams Installer\Teams.exe --checkInstall --source=PROPLUS

![Program](https://user-images.githubusercontent.com/14896790/84790483-649f5780-afbf-11ea-8630-27835d165023.PNG)

**Comment by Toomber** [comment]
I have this and I never even purposefully downloaded Teams, I think my other office products tried to do it for me.

**Comment by TrutzS** [comment]
I just found this issue on my machine with Windows + O365 C2R Office installed in September 2020 and with a Teams installer dating back to August 2020. When changing the registry entry to the correct path, the "Program" is listed as "Teams". Strange that this issue is more than a year old, but no progress has been made on resolving it.

**Comment by dlong500** [comment]
This should be a ridiculously simple thing for Microsoft to fix.  It's basically a typo in the config, but the end result (as stated above) is a suspicious entry in the task manager.

**Comment by lindspea** [comment]
@dlong500 thank you for reaching out. Not sure if this has been fixed yet as I see the article was update two days ago. Please let me know if the typo is still there and I can have it fixed.

**Comment by dlong500** [comment]
@lindspea I just installed Office 2021 LTSC (which includes Teams) using the Office Deployment Tool on a clean install of Windows 10 21H2 and the issue is present.  Not sure if the there is any difference from the O365 versions, but Office 2021 is as new as it gets for the perpetual versions.  Thanks for looking into this.
