### ISSUE TITLE
Windows 10 enterprise trial version.

### ISSUE THREAD

**Issue by mistermon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#158]
Does evaluation Windows 10 Enterprise on this page support Skype room systems v2?
https://www.microsoft.com/en-us/evalcenter/evaluate-windows-10-enterprise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 515e5db8-20be-f979-5de9-3998713518dd
* Version Independent ID: a284fee3-f324-2984-431e-df14d3c4bd2d
* Content: [Skype Room Systems v2 requirements](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/requirements#required-software-downloads)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/requirements.md)
* Service: **unspecified**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by jambirk** [comment]
the link points to Creator's Update, which is supported on the latest Updates for SRSv2. 
The currently recommended process uses a powershell script that does compatibility checking for the OS and the drivers and app, so let the script do the worrying for you!

**Comment by Travis-Snoozy** [comment]
I would tend to agree with James to let the script worry about these things for you. However, to save a bit of of bandwidth and time, the build at the link provided is not supported for two reasons:

1. Evaluation Windows 10 Enterprise is not supported by SRSv2 in general, and
2. The current SRSv2 package requires Windows version 16299 ("Fall Creator's Update"), whereas the evaluation version being served is 17134 ("April 2018 Update")

If you were to run the script against the evaluation ISO, at time of writing, you would receive an exception saying "There is no matching image." This is due to the Evaluation version having a different image naming convention than normal, non-evaluation media.
