### ISSUE TITLE
Controlling "Users" that shouldn't appear in Teams

### ISSUE THREAD

**Issue by DFLiddle** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1684]
Hi! Hopefully this page is an appropriate one to add my observations and questions ...

– I've noticed that 'non-human' objects (e.g. a mailbox used for printers) show up in Teams, such as in the "Suggested" list in the Chat view.
– I've noticed that resources (i.e. rooms and equipment) and shared mailboxes are visible in Teams, too.
– What are the effects of opening a chat with objects that will not respond?
– How can administrators render non-responding objects invisible in Teams?

I'd like to avoid as much confusion among my colleagues as I possibly can so that it doesn't cloud their opinions of Teams. Thank you for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b434530-6bf2-6e00-6eae-6fa043d022ce
* Version Independent ID: caab785f-e3a4-831a-87d8-26934a9f834f
* Content: [Use Microsoft Teams admin roles to manage Teams](https://docs.microsoft.com/en-us/microsoftteams/using-admin-roles)
* Content Source: [Teams/using-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/using-admin-roles.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@DFLiddle  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

Also, since there are certain things regarding feedback. I know the product teams are always looking for user feedback and how to make Skype for Business better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://www.skypefeedback.com.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
