### ISSUE TITLE
How about Teams federated with pure on premise SfB?

### ISSUE THREAD

**Issue by HaasHe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1849]
Hi Team, according to this article, almost covered all scenario, not sure about the specific scenario when Teams user get federated with their partner who is still using SfB On Premise ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169a20a6-ebf7-1093-3cb1-fb438b9b7e13
* Version Independent ID: b2074fd8-724e-75fa-bafb-a0f7966bf593
* Content: [Coexistence with Skype for Business](https://docs.microsoft.com/en-us/MicrosoftTeams/coexistence-chat-calls-presence#feedback)
* Content Source: [Teams/coexistence-chat-calls-presence.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/coexistence-chat-calls-presence.md)
* Service: **msteams**
* GitHub Login: @jambirk
* Microsoft Alias: **francoid**

**Comment by jambirk** [comment]
@FrancoiD can you answer that?

**Comment by FrancoiD** [comment]
@HaasHe, as mentioned in the article, you need to be more specific in that question. The article is very clear on what information you need in order to determine the routing.

The TeamsUpgrade mode of the recipient
The client used by the sender
Whether the conversation is new, or part of an existing thread
Whether the conversation is in-tenant or federated
Whether the conversation is possible 

In your case you say "Teams user", I imagine that means an originator using the Teams client.
You say federated.
You do not say what the mode of the recipient is.
You do not say if the originator is homed online or on-prem.

You need these parameters to get your answer from the tables.

**Comment by scanum** [comment]
@HaasHe  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
