### ISSUE TITLE
Table of Contents Bug!

### ISSUE THREAD

**Issue by kenwith** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1861]
When I am in the Skype for Business Server 2019 Table of Contents (TOC) and I click an article sometimes I automatically go to the 2015 TOC.

I know this is a known issue that is being worked on but I wanted to open an issue to track it.

@shanehoey - thanks for the great MVP feedback today and great to meet you in person! If you know the GitHub alias of the other MVP's feel free to add them here. I will talk with Serdar and try to get this TOC problem figured out.

**Comment by kenwith** [comment]
Here is my understanding of bug, if anyone can add on that would be appreciated:

There is a serious bug in the Skype for Business TOC. The issue is that the TOC jumps from 2015 content to 2019 content TOC. 

This can be reproduced many different ways, but one way: Go to the 2015 content set: https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-server-2015  -> Click the 4th link in the TOC "Skype for Business downloads and updates" -> you are in 2019 content and it is not clear how to get back to the 2015 content or if it applies to both 2015 and 2019 at same time.

**Comment by shanehoey** [comment]
@kenwith  thanks for having a session with us, we all enjoyed it, I've reached out to a couple of the MVP's  /cc @StaleHansen

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by SerdarSoysal** [comment]
Currently investigating a possible solution.

**Comment by scanum** [comment]
@SerdarSoysal Hi Serdar, sounds good please let me know any updates on this. Thanks!

**Comment by scanum** [comment]
@SerdarSoysal Following up on this issue. Please let me know if there are any updates. Thanks!

**Comment by scanum** [comment]
@SerdarSoysal Following up on this issue. Thanks.

**Comment by scanum** [comment]
@SerdarSoysal Following up on this issue. Thanks.

**Comment by SerdarSoysal** [comment]
@scanum This is going to require substantial rework on the backend. It is something that's on our backlog, but it keeps getting postponed due to higher priority work around Teams. Let's sync again by the end of February.

**Comment by scanum** [comment]
@SerdarSoysal Thanks for letting me know I will send a follow-up email at the end of February.

**Comment by scanum** [comment]
@SerdarSoysal @MicrosoftHeidi Following up on this issue. Thanks.

**Comment by scanum** [comment]
@SerdarSoysal Hi! Following up on this issue, wondering if there are any updates. Thanks!

**Comment by scanum** [comment]
@SerdarSoysal Hi! Following up on this issue, wondering if there are any updates. Thanks!

**Comment by scanum** [comment]
@SerdarSoysal Hi! Following up on this issue, wondering if there are any updates. Thanks!

**Comment by scanum** [comment]
v

**Comment by scanum** [comment]
@SerdarSoysal Hi! Following up on this issue, wondering if there are any updates. Thanks!

**Comment by scanum** [comment]
@SerdarSoysal Hi! Following up on this issue, wondering if there are any updates. Thanks!

**Comment by scanum** [comment]
@SerdarSoysal Hi! Following up on this issue, wondering if there are any updates. Thanks!

**Comment by SerdarSoysal** [comment]
We finally were able to address this issue. As you navigate the TOC in SkypeforBusiness 2019, you will no longer fall out and land in the 2015 content set. All the clicks on the TOC will keep you in the correct TOC. Clicks within an article also will keep you in context (previously intra-topic bookmarks also landed you in 2015 TOC)

The one issue that remains is that when you click on a link inside an article that links out to another article which was dual-purpose (applies to both 2015 and 2019) you will land on the 2015 TOC. The reason for this is that those topics were initially created in the 2015 content set. Fixing that issue requires a significant reorganization and rewrite of both 2015 and 2019 content. 

Because there is substantial cost to implementing that, and we have a large backlog of higher priority work, we will not be undertaking that effort. Even though this issue isn't full resolved, we are closing it as no further work is planned for this.
