### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by oldkingcolemsscna** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#1876]
Documentation above says "You configure Cloud Voicemail as the hosting provider on the Edge Server by using the New-CsHostingProvider cmdlet with the following parameters:"

This is incorrect. You configure the hosting provider on a FE server, not Edge. Edge PS cannot configure any aspect of the S4B infrastructure other than its own services

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8b8afb-b9ca-8136-b907-5bbff4c9dcf1
* Version Independent ID: d4f68818-6fe6-5bb7-f108-e26a643f2cc7
* Content: [Configure Cloud Voicemail service](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-cloud-voicemail)
* Content Source: [Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @oldkingcolemsscna thanks for your feedback. I created a PR to correct the article.

Thank you

**Comment by scanum** [comment]
@oldkingcolemsscna  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by oradcliffe** [comment]
It still says to do this on the Edge server..

**Comment by J-Fedor** [comment]
Now the ExchangeUM is "dead" and we're all on Cloud Voicemail, something doesn't seem right with this setup.  In a hybrid configuration, we perform the HostedVoiceMail, and test, works fine - have voicemail.  Then less than 30 minutes later....the setting is blank.  This is because of Azure AD connect.  It is synchronizing the UM status of the user back on-prem.  So, we need to go to 365, enable UM, assign it a policy and extension that is irrelevant now.  Then once that is done, the setting rolls back down onto the on-prem user setting.   Don't recall seeing anything about needing to perform those steps still, or setting up filtering of the attribute, etc.  Something seems missed in the steps that are provided (or hidden and I haven't found it).  Thanks.
