### ISSUE TITLE
'how to buy' information not complete.

### ISSUE THREAD

**Issue by DaveVernon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2017]
The 'how to see prices and buy add-on licenses' section refers you to "See your plan under "License options based on your plan" for more details about which licenses to buy and how to see prices and purchase add-on licenses."

At least for the EDU section, the linked page does not contain information on either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abae7324-861d-7ca7-7239-a5df8fd927d5
* Version Independent ID: 8a30bd2f-9bc3-a0a8-8b31-d53836ead4d0
* Content: [Microsoft Teams add-on licensing](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/microsoft-teams-add-on-licensing)
* Content Source: [Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/microsoft-teams-add-on-licensing.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @DaveVernon 
Thanks for your feedback, we appreciate it.

The blog post link that should give you more information was broken and fixed in a PR 

https://github.com/nenonix/OfficeDocs-SkypeForBusiness/commit/9aad9d0ecd340617f498ee9d7228da686f5358ae

also related to an issue you opened

Here is the link https://www.microsoft.com/en-us/microsoft-365/blog/2017/01/17/advanced-office-365-capabilities-now-available-to-u-s-government-community-customers/

but it will take time to go live and published. Is that the information you are looking for?

Thank you.

**Comment by scanum** [comment]
@DaveVernon Hi Dave, this issue has been resolved. We appreciate your feedback and encourage you to keep making the docs better.

**Comment by scanum** [comment]
@officedocsbot close
