### ISSUE TITLE
Note about Mac users

### ISSUE THREAD

**Issue by mhunsberger** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2097]
According to this article, https://support.office.com/en-gb/article/teams-meeting-button-is-missing-in-outlook-for-mac-0d6608c7-96a5-4dba-9dc1-55f724ecb543 the Teams Meeting button in Outlook for Mac will appear in the Outlook for Mac ribbon if Outlook is running Production Build 16.20 and later. The note may need to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e10f52-d726-d29a-e0a8-93729a32dfae
* Version Independent ID: 83555f80-a8ca-ee85-c1fc-e39891029758
* Content: [Use the Microsoft Teams Meeting add-in in Outlook](https://docs.microsoft.com/en-us/microsoftteams/teams-add-in-for-outlook)
* Content Source: [Teams/Teams-add-in-for-Outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Teams-add-in-for-Outlook.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@mhunsberger Thank you for pointing that out and helping improve MS Docs.  I've added the change.

**Comment by kkrine** [comment]
Hi, all! Sorry if I've missed this somewhere.  I can successfully add a Teams meeting to an Outlook for Mac 2016 meeting.  However, I have not been able to find out how to remove a Teams meeting without deleting and recreating the Outlook meeting request (which is problematic, because I'm using this meeting request for a recurring meeting for which I've reserved a room, and I risk losing the room reservation if I delete the meeting). Have I missed this somewhere? Thank you for the help!

**Comment by lindspea** [comment]
@LolaJacobsen

**Comment by scanum** [comment]
@kkrine - thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
