### ISSUE TITLE
Misleading Information on external access prefix

### ISSUE THREAD

**Issue by jupfeiff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2268]
The article first clearly states "External access prefix isn't currently supported." but just below it says something that contradicts to this statement in my eyes:
"You can specify an external access prefix of up to four characters (#, *, and 0-9) if users need to dial one or more additional leading digits (for example, 9) to get an external line.
Note
If you specify an external access prefix, you don't need to create an additional normalization rule to accommodate the prefix."
It's not supported but the option is clearly there and you describe how to use it? (also see https://docs.microsoft.com/en-us/powershell/module/skype/new-cstenantdialplan?view=skype-ps). 
The support statement seems to be wrong but in oder to being able to judge better, it would be great to know, what the external access prefix in a dialplan actually does. The article is missing this information for sure and should be added as well.
Happy to contribute - please let me know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 847c0505-3441-b5db-1f81-c7759bffd1e3
* Version Independent ID: 3c6b3820-349f-caf5-c510-a771a3b7a770
* Content: [What are dial plans?](https://docs.microsoft.com/en-us/microsoftteams/what-are-dial-plans#feedback)
* Content Source: [Teams/what-are-dial-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-dial-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@jupfeiff Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@jupfeiff Thank for reaching out, I will investigate further.

**Comment by TokyoScarab** [comment]
Hello @jupfeiff and thank you for bringing up this issue!  I can elaborate a little bit on the external access prefix(EAP).  While it might seem like a contradiction, the documentation is correct.  The EAP is not currently available for use but the documentation goes on to show how one would go about using it if it were currently enabled.  The documentation also goes on to sort of describe what it does, but this only helps if you're familiar with the concept to begin with.  The EAP is basically the same idea as what one usually sees in an office building or other such environment on their phone system where any dialing is done to local numbers within the building's phone network.  These types of setups always have a number or set of numbers that one presses so that they can make a phone call outside the office network.  Most places it tends to be 9.  So if you wanted to make a phone call across town, you have to first press 9 (which in this case would be the EAP) and then that would allow you to then have access to the national phone system and make that call.  I hope that makes sense.  If you have any other questions, feel free to comment them down below, thanks!

**Comment by jupfeiff** [comment]
Hi there,
thanks for getting back. I know exactly what an EAP is but it confuses not only me but also colleagues and customers that it first says that it’s not supported and then goes on to describe how to implemented that not-supported feature.
What’s the idea behind that?
All my customers have EAP in their PBXes configured today. Some of them I can talk out of that concept, some few insist of carry that dialing habit forward. Is Teams / Phone System with EAP supported for the latter type of customers? If yes, I assume the statement about non-supportability needs to go. If no, then the instructions of how to use it need to go.
Thanks,
Jürgen

**Comment by jupfeiff** [comment]
Hello,

does this mean this how it can look like in the future but is still in development?

Similar how the documentation for MMS was provided in advance? Said it is still in TAP but will work like described for TAP users and once it is GA?

Thanks for clarification.

Manuela

Outlook für Android<https://aka.ms/ghei36> herunterladen

________________________________
From: Juergen Pfeiffer
Sent: Friday, May 31, 2019 8:45:21 AM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness; MicrosoftDocs/OfficeDocs-SkypeForBusiness
Cc: Mention; Manuela Kretschmer
Subject: RE: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Misleading Information on external access prefix (#2268)

Hi there,
thanks for getting back. I know exactly what an EAP is but it confuses not only me but also colleagues and customers that it first says that it’s not supported and then goes on to describe how to implemented that not-supported feature.
What’s the idea behind that?
All my customers have EAP in their PBXes configured today. Some of them I can talk out of that concept, some few insist of carry that dialing habit forward. Is Teams / Phone System with EAP supported for the latter type of customers? If yes, I assume the statement about non-supportability needs to go. If no, then the instructions of how to use it need to go.
Thanks,
Jürgen

**Comment by TokyoScarab** [comment]
@jupfeiff Thanks for commenting back.  I decided to remove the note as I can see how it would be confusing and also incorrect.

**Comment by scanum** [comment]
@jupfeiff Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
