### ISSUE TITLE
the doc describes features and settings that don't exist in our instance

### ISSUE THREAD

**Issue by gregorvilkner** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2317]
user level: step 3 - there is no such thing in the admin center. a screenshot would help.
group level: the one money check box with the red box around it does not exist. the neighbors do.
org level: step 2 - org wide app settings don't exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d51bb7b1-801e-6801-dcaf-afa3e38e6941
* Version Independent ID: d8e726a1-cbf2-53c7-da4d-cc155b48612b
* Content: [Manage custom app policies and settings in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-custom-app-policies-and-settings#feedback)
* Content Source: [Teams/teams-custom-app-policies-and-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-custom-app-policies-and-settings.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@gregorvilkner Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by BeigeBadger** [comment]
We also have this issue with our instance. Any ETA?

**Comment by gregorvilkner** [comment]
hmmm... first sentence on the page says: This article describes a Microsoft Teams feature that hasn't yet been released.

Further - walkthroughs like this one (https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio) do work, and the app studio is very useful in helping to craft a manifest file. But instead of install in the last step (this doesn't work yet apparently) - you need to download the zip and install it the old way (https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-upload). this requires an admin account.
cheers, Gregor

**Comment by BeigeBadger** [comment]
Ah I didn't see that. Thanks I've got it published through App Studio thank you. 👍

**Comment by Reeced40** [comment]
@gregorvilkner Thank you for reaching out, please confirm if @BeigeBadger has answered your questions.

**Comment by gregorvilkner** [comment]
Reece, it would be nice to get acknowledgement of the issue and get users a heads-up. Matt asked for an ETA - I second that. When is this feature coming? You have a Nov 2018 walkthrough that uses this workflow (get-started-dotnet-app-studio). Matt, did you use the "Install" feature in app studio to publish your app? We couldn't get this to work even with admin creds - that's why we export the zip with the manifest and upload the app old-school. Kind regards, Gregor

**Comment by BeigeBadger** [comment]
@Reeced40 it has "resolved" my issue in that the app was able to be uploaded to Team via a Teams Administrator. The ideal solution would be to user the User Policies so that developers could upload the app themselves because they may not be Team Administrators (global admins). As @gregorvilkner pointed out the documentation has mentioned the User Policies for over 6 months now (even with the warning - perhaps it should be in a note section so that it stands out more), it seems like this feature isn't a priority for the product team which is a shame.

@gregorvilkner I used the Install feature to test the bot in teams (loaded it against my user only after the admin enabled side-loading for this purpose). Once I was happy with the functionality I used the download feature in App Studio to generate a package which a Teams Admin was able to install to the tenant app catalog following [this guide](https://docs.microsoft.com/en-us/microsoftteams/tenant-apps-catalog-teams#publish-an-app-to-the-tenant-apps-catalog-from-the-teams-client).

**Comment by Reeced40** [comment]
@gregorvilkner @BeigeBadger thank for you your valuable help with this issue so far.  Let me check with the team and I'll revert soonest.

**Comment by Reeced40** [comment]
@gregorvilkner @BeigeBadger I'm still investigating with the team and also trying to find out an ETA for the feature release.  In the meantime, to make it more user friendly and for clarification is there any note you would recommend to add to the article in the meantime while this is under investigation? Should I perhaps add a note with the link you recommended for App Studio? Any help is appreciated.

**Comment by BeigeBadger** [comment]
@Reeced40 The app studio link would be fine. Like @gregorvilkner said most of issue is with the fact that the documentation has been live for so long without the functionality that it talks about actually existing. I'm not quite sure how to fix it because there is already the note that mentions the current way of managing apps. The issue I have with the current way - especially when trying to get it enable by clients is the security hole that allowing sideloading opens up and their reluctance to enable it without documentation on the security issues that it introduces - which from my searches doesn't exist.

**Comment by scanum** [comment]
@gregorvilkner Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
