### ISSUE TITLE
Teams encryption documentation

### ISSUE THREAD

**Issue by NickElniff** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#236]
Teams should be called out more clearly statements in this article.

Example: All Skype for Business traffic is encrypted with Transport Layer Security (TLS) and the media workloads are encrypted with Secure Real Time Protocol (SRTP). Signaling is encrypted with TLS and the media workloads are encrypted with SRTP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aea4c9d-38f4-f660-65e0-164cacab0c82
* Version Independent ID: a417c7ad-5f9f-3941-98dd-c6bae93d8940
* Content: [Optimizing your network](https://docs.microsoft.com/en-us/skypeforbusiness/optimizing-your-network/optimizing-your-network)
* Content Source: [Skype/SfbOnline/optimizing-your-network/optimizing-your-network.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/optimizing-your-network/optimizing-your-network.md)
* Service: **skype-for-business-online**
* Product: **unspecified**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@NickElniff - sorry for the delay on this one. Thank you for the feedback though, it is greatly appreciated. 

There is a section on Teams security and compliance. Here is a link: https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview 


However, looking through that node in the table of contents I don't see anything in particular about encryption. I am going to put in a request for documentation on Teams similar to this article you link for Skype for Business Online. 

Based on your comment I think you are an expert in this area and have a wealth of knowledge. It would be awesome if you were willing to contribute a Pull Request for the Teams content based on your knowledge. You would get contributor credit. Anyways, it is just an idea since the docs are open source now. At any rate, I am going to get this request submitted internally. Thank you for the feedback!
