### ISSUE TITLE
Unable to login to skype for business prompted prompted with untrusted certificate. 

### ISSUE THREAD

**Issue by sufi1321** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2431]
![Skype error](https://user-images.githubusercontent.com/30462591/59369590-0a7f0d00-8d41-11e9-8416-6eeab73e6528.jpg)
Hello Team, 

We have some wearied issue, we are using on prem SFB and where one of the users is been prompted with untrusted certificate after entering the login credential on skype for business app (iOS and Android).  

Below are the logs what we have collected. Could you help us to understand why and how this certificate has been pushed to the user however this certificate is not provided by our CA. 

For security reasons i have changed the customer name with XXXXX
I have attached the SFB app logs below

[app_log_all.log](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/files/3282306/app_log_all.log)

**Comment by sufi1321** [comment]
@scanum can you support me with this please.

**Comment by scanum** [comment]
Hi @sufi1321 thank you for submitting feedback.

Since this is not related to documentation and it is to product use. I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
