### ISSUE TITLE
Skype for business web app is not available on macOS any more

### ISSUE THREAD

**Issue by kiranpradeep** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2459]
Skype for Business Web App is no more available on macOS any more. The page lists web app as available on mac OS. Is that intentional? I use mac OS 10.13.4, with Chrome/Safari on an Intel Core i5 processor. Even if I select (Try Skype web app) link in a meeting invite, the page only lists desktop client for download. It doesn't list the webapp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ce7a531-5b1f-f404-50a3-58eb285a0a1a
* Version Independent ID: 61d27af3-cfd6-ed7f-102c-072721db0209
* Content: [Plan for Meetings clients (Web App and Meetings App)](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/clients-and-devices/meetings-clients)
* Content Source: [Skype/SfbServer/plan-your-deployment/clients-and-devices/meetings-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/clients-and-devices/meetings-clients.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by kiranpradeep** [comment]
To leave no room of doubt, I tried from different macOS system to see that skype for business web app is not available for download. You may as well try the same.

**Comment by scanum** [comment]
@kiranpradeep Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by TokyoScarab** [comment]
@kiranpradeep Thank you for posting this question!  I can't seem to find anything to suggest that the Skype for Business Web App is discontinued.  I think it would be beneficial to open a support ticket with [Microsoft Support](https://support.microsoft.com) and report back on their findings.  If what they find is relevant to updating the documentation, I will be happy to do that.

**Comment by kiranpradeep** [comment]
@TokyoScarab This is a Microsoft article which speaks of discontinuity. https://techcommunity.microsoft.com/t5/Skype-for-Business-Blog/Skype-for-Business-desktop-app-on-Mac-to-replace-Skype-Meetings/ba-p/357958

**Comment by TokyoScarab** [comment]
@kiranpradeep That is very helpful, thank you!  I will update the documentation appropriately to reflect these changes.

**Comment by PhillipGarding** [comment]
Skype for Business 2015 Web App is still available from on-premises SfB 2015 server.  However, you can configure the 2015 server so that instead of the SfBWA, users will download the Skype Meetings App on Windows or Skype for Business for Mac desktop app on Mac instead.  This document refers to the fact that SfB for Mac desktop is the replacement for SfBWA on Mac.  It doesn't state that Skype Meetings App will run on Mac.  (SMA used to be supported on Mac, but it is not supported any longer.)  I hope this clarifies the issue.

**Comment by kiranpradeep** [comment]
@PhillipGarding No. It doesn't. Pardon me. To bring clarity: this ticket was never about  Skype Meetings App on Windows or Skype for Business for Mac desktop app. This ticket is only about SFB **web app** on macOS. **Original Question:** Is Skype for Business web app supported on macOS any more?  If yes, where can an end user download it from? If no, then the document might need an update.

**Comment by PhillipGarding** [comment]
The Skype for Business 2015 Web App is available for download only when joining a meeting that is hosted on a SfB 2015 Server that is configured to offer the web app (instead of the Skype Meetings App or SfB for Mac desktop).  When so configured, the download URL is from the SfB Server and not our online CDN.  The end user never has a choice for where to download or to download the app independently of joining a meeting.
