### ISSUE TITLE
Supported Browser version for Teams

### ISSUE THREAD

**Issue by naminakao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#26]
Based on the following bugs, Teams support the current version and two previous versions for most browsers.

 https://domoreexp.visualstudio.com/MSTeams/_workitems?id=205548&_a=edit
 https://domoreexp.visualstudio.com/MSTeams/_workitems?id=202889&_a=edit

However the following content says we support older versions. 
 https://docs.microsoft.com/en-us/microsoftteams/get-clients

I think most Teams users use other Office 365 services as well. Based on the following content, O365 supports the latest version for most browsers.
 https://products.office.com/en-us/office-system-requirements/#Browsers-section

So would you update content for Teams to say we support the latest versions for browsers like Office 365?

**Comment by tonysmit** [comment]
@LolaJacobsen - I was here. Not sure if you seen this.

**Comment by LolaJacobsen** [comment]
Thanks, @tonysmit. We've been discussing how to update the get-clients topic - whether we should switch to the more generic "current version + 2 previous versions" verbiage. I have hesitated to update the Teams content because, until recently, there were exceptions. I'm talking with the PM to ensure there are no longer any exceptions (any delta between browsers supported for Teams vs. Office 365). 

Thanks for your comment.
Lola Jacobsen
Microsoft

**Comment by karuanag** [comment]
@LolaJacobsen  do we have an ETA on this update?  I concur about updated the language all up

**Comment by alihirsch** [comment]
Per mail w/lolaj, issue resolved: "“current + 2 previous” is the final verbiage we agreed on."  Topic (get-clients) updated and published.
