### ISSUE TITLE
Scope is not clear

### ISSUE THREAD

**Issue by JorgeALeitao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2719]
Microsoft Teams has two models within Phone Systems.
1) Calling Plans where Microsoft is the Telco Service Provider - only available in a limited number of countries
2) Direct Routing where a local TSP provides the service.

It appears to me that the article only applies to the situation where the customer have acquired a Calling Plan, however as this is not explicitly stated it may confuse the reader.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f74116db-b4a0-8a58-7e52-0d961e35ed99
* Version Independent ID: 2334f49e-54fb-4d2b-ed4a-dab8b399b45e
* Content: [Getting service phone numbers](https://docs.microsoft.com/en-us/microsoftteams/getting-service-phone-numbers)
* Content Source: [Teams/getting-service-phone-numbers.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/getting-service-phone-numbers.md)
* Service: **skype-for-business-online**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@JorgeALeitao  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@JorgeALeitao there is a note that explains all you need, see below

For you to see the Voice option in the left navigation in the Skype for Business admin center, you must first buy at least one Enterprise E5 license, one Phone System add-on license, or one Audio Conferencing add-on license.

**Comment by dplotnikov** [comment]
@JorgeALeitao so I would say this article is okay

**Comment by JorgeALeitao** [comment]
I beg to disagree, this article is an orientation even for customer that haven't purchase licenses or services from Microsoft.

However if you move the whole Phone Number section to under Calling Plans then it would give reader the proper context as 85% to 90% of it applies only to Calling Plans.

Please remember that US is not the only region were we deliver services.

**Comment by CarolynRowe** [comment]
Hello,
@JorgeALeitao has made a valid point.  We also received feedback that we should separate Phone numbers from Calling Plans because the node had become too large and hard to peruse.  But it is important to indicate when articles apply only to Microsoft Calling Plans.  We will consider how best to rectify this issue.

**Comment by tonysmit** [comment]
@dplotnikov - That note doesn't apply in Teams. Only in SFBO. We follow a different model entirely. 

@JorgeALeitao - Calling plans are used with subscriber numbers and not necessarily service numbers (unless you have outbound call routing to a PSTN number. And Service numbers are a function of AA, CQs and Audio Conferencing. All can use them. They are available with Phone Systems, not calling plans. Subscriber numbers do have a direct relationship to subscriber numbers because they must have outbound calling to make calls to the PSTN. So, I don't agree that your solution is the correct one here.  Thanks, Tony

**Comment by dplotnikov** [comment]
@tonysmit so do you suggest closing the issue then?

**Comment by tonysmit** [comment]
@JorgeALeitao - you good? If you need more info, let me know. Closing for now unless you need something more.
