### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2803]
Can you please rephrase the below and make it clearer:

"By default, Teams chat, channel, and files data are retained forever. A user can delete something, but in the absence of retention policies, Teams data is always archived into Exchange online mailboxes (user and group) and stays there for eDiscovery."

This leaves the impression that data is preserved immutably, without the need for holds. Which is not the case, users can certainly delete records from the TeamChats folder in their own mailboxes, thus making the corresponding records NOT available for eDiscovery.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c52a5-5841-b9c9-1607-2013dc3f2e20
* Version Independent ID: 16d93458-5e01-646f-dac5-31306cc7f3fb
* Content: [Microsoft Teams retention policies FAQ](https://docs.microsoft.com/en-us/microsoftteams/retention-policies-faq#what-is-the-default-retention-policy)
* Content Source: [Teams/retention-policies-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies-faq.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by michevnew** [comment]
Oh, and the same remarks apply to the https://docs.microsoft.com/en-us/microsoftteams/retention-policies article. "retained forever by default" is hardly 100% true.

**Comment by scanum** [comment]
@michevnew Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@michevnew thank you for pointing this out and helping improve MS Docs.  I'll look into rephrasing the sentences for better clarity.

**Comment by LolaJacobsen** [comment]
@Ansuman777 could you look at this issue and advise on what changes we should make to the 2 Data Retention articles pleas?

**Comment by LolaJacobsen** [comment]
Ping'd new PM, Praveen Vijayaraghavan.

**Comment by LolaJacobsen** [comment]
PM Praveen Vijayaraghavan is planning updates to both articles. It'll take a couple of weeks to finalize, but I'm closing this issue.

**Comment by anwara-ms** [comment]
the language in the article has been updated since, there has been a feedback on the changed version-> https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4591. we can track it there.

**Comment by Jmartinez589** [comment]
Ok. there is still ambiguity. For example, say someone sign-ups for a Teams license only. Now it does not have a mailbox. The question is if the Teams chat (1:1 or 1:N), is kept (retained) forever, where exactly is it kept? If then the assumption is that a mailbox is required, and then one does not exist, then it is not retained. Is that correct?

**Comment by anwara-ms** [comment]
Hi Martinez
This statement is for situation when a chat exists (which implies that there is a mailbox, or a storage somewhere) and it says that the chat wont be deleted (automatically)  unless there is a user or admin initiated attempt to delete it. The new text is ""By default, Teams chat, channel, and files data are retained forever, unless there is an attempt to delete the content via retention policies, user deletes, admin deletes etc...."

The scenario e.g. someone has a teams license only (I am assuming they still get a mailbox, but they cant login into it) - still the chats wont be deleted, wherever they are stored. Because the statement is not about where chats are stored, the statement is that the chats are not going to be automatically deleted, wherever they are stored.

If the situation is that a mailbox is required and one does not exist, then no Teams chat exist. The article about when Teams chat exists.


But, if you think the statement can be improved further, please send over new text, we can review.


Thank you!

 --

Anwar Ali | PM @ TEAMS | LinkedIn<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fanwarali&data=04%7C01%7CAli.Anwar%40microsoft.com%7C61a24ee754db4b1493e408d6b4dc7b41%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636895256392090042%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=KpQ4z1jxZOc8s8IWXAYS3oVAbqKpT94E%2BzEB%2FLypv2c%3D&reserved=0>

Security and Compliance Team

<https://www.linkedin.com/in/anwarali>
<https://www.linkedin.com/in/anwarali>
________________________________
