### ISSUE TITLE
Syncing on-prem CsHybridApplicationEndpoint does not create CsOnlineApplicationInstance

### ISSUE THREAD

**Issue by oradcliffe** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2852]
To create a call queue or AA online, you must have a CsOnlineApplicationInstance to use.  When I first create a CsHybridApplicationEndpoint on-prem, using ApplicationID "ce933385-9390-45d1-9512-c8d228074e07" (for online auto attendant), and then AADSync, I never get the corresponding CsOnlineApplicationInstance.  Should I?  Is there something wrong with ApplicationID?  All I see is a synced user, but I cannot assign that user as the resource account for the online AA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0703860-c3db-c723-317f-7fab164c006d
* Version Independent ID: c6384e2b-ac37-265d-8c33-f004eca97673
* Content: [Configure a resource account in Skype for Business Server 2019](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-onprem-ra#feedback)
* Content Source: [Skype/SfbHybrid/hybrid/configure-onprem-ra.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-onprem-ra.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by oradcliffe** [comment]
@jambirk just checking in to see if you have had a chance to review my questions.  Thank you!

**Comment by jambirk** [comment]
@oradcliffe  

The documentation was developed in close reference with the feature developers, who have successfully created many implementations in developing the feature. If you're unable to create a call queue or auto attendant and link it to a resource account homed onprem, there is a problem that requires a support ticket. The documentation is not the issue here, it reflects the process as intended and tested.

For what it's worth, there are a lot of changes coming soon on the creation process for Auto attendants, call queues, and resource accounts. The process is being simplified and will be more automated. The articles in this area will all have to be rewritten to reflect these changes.

**Comment by oradcliffe** [comment]
@jambirk - an online Auto Attendant requires a CsOnlineApplicationInstance to exist, and that is what is selected when assigning a resource account.

Syncing a CsHybridApplicationEndpoint from on-prem does not create the CsOnlineApplicationInstance.  It creates a _user_ online.  This cannot be selected as the AA resource account.

Not sure what else can be said - the process as it is written does not work and I have yet to find anyone who has successfully deployed it this way, and MS support has thus far not been helpful.  If you can point me to someone who has gotten this to work I would be appreciative (and a bit surprised).

**Comment by scanum** [comment]
@oradcliffe Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
