### ISSUE TITLE
USB Peripherals not on Certified List

### ISSUE THREAD

**Issue by dabato** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#2973]
Can non certified USB peripherals be used? For example; can I use an analog audio to USB device to bring external microphones into the Teams Room System? I've tested with several products and it seems to work fine, but do I have to worry about future updates possibly breaking the functionality?

**Comment by scanum** [comment]
@dabato Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
@dabato   

Peripheral devices that are certified for Teams were either built to a spec shared by Microsoft with partner companies, or were tested and found to meet that spec. The best results and continuing support happens when these are the devices you choose and use. 

There is a reasonable sized gray area: Stuff that wasn't tested and certified but there's no immediate and obvious reason to say it not going to work, though perhaps it won't work as well as you need it to even though subjectively it seems fine for a call or two. If you try it and decide it works to your liking, we certainly can't stop you. You do need to understand that your implementation is in what's considered an unsupported state, and if you create a support ticket the tech is correct to tell you to bring it into a supported state before their troubleshooting can continue. You don't want to hear that after dropping huge amounts of money on non-certified gear, but that is exactly where you put yourself.

Also: if you're running into system stability or video/audio quality issues and you need to use Call Analytics or Call Quality Dashboard to sort out the problem, your unsupported devices are usually one of the first things you should be suspecting as the root cause of your problems.

**Comment by scanum** [comment]
@dabato Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by dabato** [comment]
@jambirk

Is there any support product that will allow injection of audio  onto the PC; analog to USB adapter? We're trying to integrate these systems into larger spaces with integrated microphones and there's not product on the certified list that will allow this type of design.

**Comment by jambirk** [comment]
@dabato  

See the "gray area" discussion above. This isn't an officially supported scenario, I can't make suggestions about how to make it "work." If you find a way to make it "work," you'll still be putting your implementation in an unsupported state, so you do so at a very significant risk and it may not scale the way you want it to.
