### ISSUE TITLE
License requirements

### ISSUE THREAD

**Issue by meshkerila** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3071]
The article mentions the requirement of Phone System add-on license (if it's not already included in the current SKU available on the tenant). 

Can we also use the free "Phone System - Virtual User" add-on license for Voicemail, in a scenario where callqueues outside of the business hours would redirect callers to a  generic (virtual) user's voicemail.

Neither the current article, nor the "Phone System - Virtual User License" article (https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/virtual-user) mention anything about the virtual user and voicemail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8228f9b2-a7de-abb4-6f41-70db0b3af155
* Version Independent ID: 8fd9fafb-dd76-59a8-e609-56f06d539a31
* Content: [Set up Cloud Voicemail](https://docs.microsoft.com/en-us/microsoftteams/set-up-phone-system-voicemail#feedback)
* Content Source: [Teams/set-up-phone-system-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/set-up-phone-system-voicemail.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@meshkerila  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jambirk** [comment]
@meshkerila Phone System - Virtual user licenses are only for use with resource accounts that are linked to call queues and auto attendants.  They are not full-feature user accounts that can have a voicemail box, so if you configured an auto attendant or call queue to forward to voicemail after hours, the destination voicemail box needs to be for an account that has a normal user license.  

Omissions like this are often deliberate: it's not possible to describe everything that's not supported so we only describe what we're sure is supported. I'm confident that's not a supported use of that license.  @waseemhashem can correct me if that's not the case.

**Comment by dewaltk** [comment]
I've am trying to get a SfB 2015 environment to make use of Cloud Voicemail instead of using Exchange Online UM but cannot get cloud voicemail working for my onprem homed accounts. Hybrid is setup and working, the accounts have E3 and phone system licenses assigned and the hosting provider for Exchange Online is in place.

When the accounts are homed onprem I get the error "ms-diagnostics-public: 15621;source="MW2PR16CA0018.namprd16.prod.outlook.com";reason="The specified mailbox is not enabled for Unified Messaging." which it isn't since I am trying to make use of Cloud Voicemail not UM online.

When I enable the same account for UM Online voicemail works fine to the Exchange Online UM service. When I disable EXCHO UM and move the account to SfB Online voicemail works with the Cloud Voicemail service, but when I move the account back to the onprem pool the Cloud Voicemail service stops working.

The Technet documentation says that Cloud Voicemail is supported with SfB2015 but I just cannot seem to get this working.

**Comment by waseemhashem** [comment]
Until its retired in Feb 2020, Exchange UM Online is the default voicemail service for SFB 2015 and 2013. To migrate your deployment to CVM instead, please check the Opt-in instructions in this article: https://docs.microsoft.com/en-us/SkypeForBusiness/plan/exchange-unified-messaging-online-migration-support

**Comment by scanum** [comment]
@meshkerila Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
