### ISSUE TITLE
Error re-running SRSv2 CreateSrsMedia.ps1 Script / 1.4.5

### ISSUE THREAD

**Issue by pyoungberg** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3128]
If the script CreateSrsMedia.ps1 fails for any reason, re-running the script in the same PowerShell session will cause any downloads in the script to timeout. 

Workaround is closing the PowerShell windows and launching a fresh session before running the script again.

Scripting fix outline here: https://www.reddit.com/r/PowerShell/comments/80dfs2/systemnetwebclient_downloadfile_method_only_works/

**Comment by jambirk** [comment]
@Travis-Snoozy  I hadn't heard this before, sounds like it's worth noting in the console creation article. Do you agree?

**Comment by pyoungberg** [comment]
Sure thing, at least until there's a coding fix in 1.7.6+.

**Comment by jambirk** [comment]
note could be placed in this section:   
https://docs.microsoft.com/en-us/MicrosoftTeams/room-systems/console#prepare-the-installation-media

**Comment by Travis-Snoozy** [comment]
Thank you for not only the report, but the analysis of where the fault came in. If you could include the transcript file generated by your faulting run(s), that would still be helpful for me to verify exactly how/in what context the script was executed.

The way I'm likely to resolve this is to further restrict the means by which this script is run to more closely match how it's tested. In testing, this is only really ever invoked as `powershell -executionpolicy Unrestricted .\CreateSrsMedia.ps1` (with a 64-bit powershell executable, on an elevated prompt -- usually, CMD, but sometimes from within PowerShell). That means of invocation does not hit this problem, very likely because each invocation of the PowerShell executable creates a new PSSession to work under. I do not test this script in direct form from the PowerShell prompt (e.g., `.\CreateSrsMedia.ps1` with the unrestricted policy pre-set), but rather I assumed that that invocation _should_ have behaved identically. I assume that the "short form" above is what you were using, and if so, it's troubling to hear that it isn't completely isolated from its prior runs. It's also troubling that a nominally GC'd language isn't cleaning up after itself when a self-contained script finishes executing, let alone when an object that was never assigned to a variable goes out of scope. It is also somewhat perplexing that, given the WebClient objects in that script are _never_ (explicitly) disposed, that multiple downloads in a single session regularly works without fault.


I'll also see about changing the various fault messages the script gives when invoked in ways it does not like to also output a more prescriptive "run this exact command" message.

Again, thank you for the report and the reference to a concise analysis.

**Comment by pyoungberg** [comment]
Unfortunately I'm not sure I can repo the issue, I didn't have tracing turned on. But yes, I was using the dot sourced method when I got the initial error, and my execution policy was set to RemoteSigned. Thanks for the follow up!

**Comment by scanum** [comment]
@pyoungberg Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
