### ISSUE TITLE
Teams Only, Outlook addin for Skype disappears

### ISSUE THREAD

**Issue by Erdem-Oz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3225]
Hi,

We have an issue where users complain that the outlook button to schedule meetings disappears with the click to run version. They are in Teams Only mode (forced upgrade) with their tenant, but they have onprem Skype for Business with Enterprise Voice. The button and the Addin is gone, is this implemented in the installer of Teams? What is the best way to restore this function?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53d0cb0-90a6-5932-f78e-7de6fcc4d481
* Version Independent ID: 3d468027-cc37-5199-32ec-819bf62b2caa
* Content: [Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability)
* Content Source: [Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-and-skypeforbusiness-coexistence-and-interoperability.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Erdem-Oz Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Erdem-Oz** [comment]
i have noticed that only the addin gets disabled within outlook. It can be re-enabled.

**Comment by lindspea** [comment]
@Erdem-Oz Thank you for reaching out and helping improve MS Docs. Did you solve the issue or is there more investigating needed from our side to help?

**Comment by Erdem-Oz** [comment]
Yes the issue is solved, but it is good that it will be mentioned in the migration documentation that the outlook addin for SFB gets disabled and you can easily enable it. Maybe build an option in the Teams tenant not to disable the addin? Most companies have also their onprem deployment and are testing with Teams. So when an tenant gets migrated in Office365 from SFBO to Teams Only that their button gets disabled in outlook.

**Comment by lindspea** [comment]
Thanks @Erdem-Oz. Is this the article you are suggesting having a note added to about the addin? https://docs.microsoft.com/MicrosoftTeams/migration-interop-guidance-for-teams-with-skype

**Comment by Erdem-Oz** [comment]
Yes correctly

**Comment by kenwith** [comment]
@Erdem-Oz - I see that the issue was resolved and I appreciate your feedback on this. 

For others that might be in the same situation: I reached out to the PM that owns this area, @bjwhalen , and we think it would be best to open a ticket and bring in a support engineer. I can understand the confusion and in TeamsOnly mode the add-in is meant to be hidden. I am going to close the PR of @lindspea as that note could cause problems in some scenarios. 

For anyone else that comes across this discuss and has a similar problem feel free to email me directly (email on GitHub profile) and I can work with you and the PM that owns this area and the support engineer to make sure your specific scenario is addressed when upgrading to Teams.

@Erdem-Oz - again, really appreciate your engagement and sharing your experience and I know it will help others.

**Comment by lordmafi** [comment]
I would like to repoen this, as the "Teams Only" Mode does disable the SfB Addon always and with every start we are running into the issue that we have a special setup where two identities are present on one computer. A SfB Onprem enviroment and a Teams only enviroment which causes the SfB one to be unsable in Outlook. My question would be how this control works technically and how we can disable with Teams Only mode that Teams is interferring with Outlook. Is there a registry key which can be set?

**Comment by tonyc76** [comment]
hi @lordmafi - im seeing the same issue in my env. all these years later, did you ever get an official fix for this issue ? 
any help or info would be appreciated - thanks

**Comment by lordmafi** [comment]
> hi @lordmafi - im seeing the same issue in my env. all these years later, did you ever get an official fix for this issue ? any help or info would be appreciated - thanks

Hay Tony, with the ongoing changes the Teams settings went through up to not having the choice anymore for the mode we decided to change the Environment to only operate with one tool. We found a registry key which controls this behavior:  

Key: HKEY_CURRENT_USER\Software\Microsoft\Office\Outlook\Addins\UcAddin.LyncAddin.1
DWORD: LoadBehavior
Value: 3 = add-in is enabled, 2 = add-in is not enabled

But because Teams automatically sets following KEY: 
HKEY_CURRENT_USER\Software\IM Providers -> DefaultIMApp to TEAMS

This automatically caused the Addin to disappear and also to show presence information from Teams not from Skype for Business....

Changing the Keys was only effective until reboot as the Teams client changed them back...

We never found a valid solution for this.

@kenwith : FYI :)

**Comment by lordmafi** [comment]
Now I see a new Checkbox maybe this could do the job:

![teams-chat-app-defaultimapp](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/11151288/3556ecd5-b4e4-4994-80f5-63a557c383a2)
