### ISSUE TITLE
SQL Requirements

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3246]
The page has some conflicting information regarding SQL Server 2017 support. While earlier it is stated that SQL Server 2017 is only supported for SfBS 2019, later there seems not to be a limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f91216e8-0b6c-88b1-635a-401529556f78
* Version Independent ID: 0b0e068d-b870-bbd2-550d-07917ec63926
* Content: [Plan for Call Quality Dashboard for Skype for Business Server](https://docs.microsoft.com/en-us/SkypeForBusiness/management-tools/call-quality-dashboard/plan#feedback)
* Content Source: [Skype/SfbServer/management-tools/call-quality-dashboard/plan.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/management-tools/call-quality-dashboard/plan.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@b-i-n-d-e-r Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello if you refer to what it says [here](https://docs.microsoft.com/en-us/SkypeForBusiness/management-tools/call-quality-dashboard/plan#infrastructure-requirements-for-cqd):

> For CQD 2019 |  
Supported SQL Server | SQL Server 2017, SQL Server 2019

It's because CQD 2019 works with 

Microsoft Lync Server 2013
Skype for Business Server 2015
Skype for Business Server 2019

[Source ](https://www.microsoft.com/en-us/download/details.aspx?id=57510)

**Comment by get-itips** [comment]
@scanum no further user response, this can be closed, thanks

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
