### ISSUE TITLE
External NAT Address

### ISSUE THREAD

**Issue by tmaheshwar** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3578]
In case of E911 with Direct Routing, when a user works from Home or outside, which will indicate that External NAT Address is not matching with the Corporate office, will still E911 calls be routed as location of the user will be unknown

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634810fc-7a47-f794-7803-9f3941d664dd
* Version Independent ID: 52587955-5054-a003-6d03-948ce02838dd
* Content: [Plan emergency calling, emergency addresses, emergency call routing, dynamic emergency calling - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-emergency-locations-addresses-and-call-routing)
* Content Source: [Teams/what-are-emergency-locations-addresses-and-call-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-emergency-locations-addresses-and-call-routing.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@tmaheshwar Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@tmaheshwar  Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@tmaheshwar You should be able to set up a separate policy for anyone working remotely from home if that is a concern. Would you be able to go into a little more detail about the "or outside" area of your question? Are you referring to someone using a cell phone? Want to make sure I can address your question fully and hope to back from you on this, thanks!

**Comment by tmaheshwar** [comment]
Hi, Outside I am referring to working from Home, Airport, Starbucks
Is it supported for all Client types e.g. Teams on Desktop, or Mobile or via web browser. 
so is it supported when "Outside" the corporate/office subnet, 
Thanks!

**Comment by TokyoScarab** [comment]
@tmaheshwar For users working remotely from home, you could set up a site / location for that user's address. These emergency addresses and locations cannot be dynamically changed with a user's cell phone or laptop data, for example. It is recommended in those situations where you are outside the emergency address in your corporate/office subnet, to make the call instead directly from either a cell phone or landline device. @CarolynRowe I don't know if you have anything you can add to this. Since the subject matter is highly important, I would appreciate any extra input you could provide on this issue. Thanks!

**Comment by scanum** [comment]
@tmaheshwar Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
