### ISSUE TITLE
Incomplete and misleading information about configuring Pay-per-minute

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3581]
Hi!
We are trying to configure audio conferencing pay-per-minute. This article states that "If you have Audio Conferencing pay-per-minute licenses, you don't have to assign Communications Credits licenses separately to each user specifically for Audio Conferencing usage". The article it leads to in point 3 https://docs.microsoft.com/en-us/microsoftteams/set-up-communications-credits-for-your-organization tells to add both communication credits license and audio conferencing license to user. This article https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-pay-per-minute states "Pay-per-minute requires your organization to have Communications Credits enabled with a license assigned to each user in order for Audio Conferencing to work." but it does not say which licenses.
When we try to setup audio conferencing for users in Teams admin panel https://docs.microsoft.com/en-us/MicrosoftTeams/manage-the-audio-conferencing-settings-for-a-user-in-teams then we do not see audio conferencing settings. When we try to add the communication credits to users in Office 365 license panel then we get error that we also need to assign audio conferencing license which we do not have as this is licensing not per user but per communication credits.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c6c2e6-a1c7-dd0c-dbe3-0072497282d5
* Version Independent ID: 1b09ca3d-f45e-5540-40b4-8c3b7176fc81
* Content: [Try or purchase Audio Conferencing in Office 365 for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/try-or-purchase-audio-conferencing-in-office-365-for-teams)
* Content Source: [Teams/try-or-purchase-audio-conferencing-in-office-365-for-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/try-or-purchase-audio-conferencing-in-office-365-for-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@Larryngolog  Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@tonysmit Being the page author for this piece of documentation, I feel you might have a more detailed knowledge about this issue that could prove to be helpful.

**Comment by tonysmit** [comment]
@TokyoScarab - I've been out of the content side for a while. I do probably have additional information, but things change very quickly. I've added the PM to see if he can help with this.

@ruizoscar - can you answer their question here please?

**Comment by scanum** [comment]
@ruizoscar - Any updates on this? Thanks

**Comment by scanum** [comment]
@ruizoscar - Any updates on this? Thanks

**Comment by scanum** [comment]
@ruizoscar - Any updates on this? Thanks

**Comment by VNJoe** [comment]
@ruizoscar - Any updates on this?  The world would like to understand this and it is completely unintelligible at the moment.  Clicking any link in the docs for the pricing for Teams calling leads you to the Teams main page which only states $4 for Audio Conferencing and no mention of Communications Credits.  I think it's time to be transparent on this item.  People don't mind paying if they know up front, but this is very confusing and unanswered for months.

**Comment by scanum** [comment]
@ruizoscar - Any updates on this? Thanks

**Comment by tonysmit** [comment]
I'm checking with the PMs on this. Please hold and I will report back here. @fafan @ruizoscar

**Comment by TokyoScarab** [comment]
@tonysmit Were you able to find anything from the PMs?

**Comment by tonysmit** [comment]
@TokyoScarab @Larryngolog - sorry about the long delay here. Honestly, I lost track of this issue. It's true that Communication Credits are required for Pay-per-minute usage scenarios. We need to update this doc to align correctly. 

Communication Credits is a separate license **(requires no payment)** that must be assigned to any AC user to support these scenarios:
1. User has an Audio Conferencing license assigned. Communication Credits are required for a meeting participant to dial out to someone else and have them join the meeting.
2. User has a Pay-per-minute license. Communication Credits are required for this because it's how we charge customers for this service.
3. Communication Credits are required when you have a toll free phone number that has been ported over or purchased by Microsoft for an organization.

So for Pay-per-minute scenarios, you must do the following:
1. Create a conferencing bridge with a phone number for dial-in (or use a shared number). Note - if you have a toll free number, Communications credits must be set up but you don't have to assign any licenses to users.
2. Set up Communication Credits for your org. Add credit card details and number of minutes. Also can set thresholds.
3. Get the Pay-per-minute licenses from an account rep, and assign this license to any user that will be using PPM.
4. Assign a Communications Credits license to the same user that will be using PPM.

**Comment by tonysmit** [comment]
Update: I updated the content below to reflect the issues you have above:
https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-pay-per-minute 
https://docs.microsoft.com/en-us/microsoftteams/try-or-purchase-audio-conferencing-in-office-365-for-teams

These changes should be live in a few hours.
