### ISSUE TITLE
Use dpkg -i for .deb file not apt install or yum install on Ubuntu

### ISSUE THREAD

**Issue by Joel-fogue** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3598]
On Ubuntu, to install .deb, use the following commands: 

sudo dpkg -i &lt;teams_1.2.00.32451_amd64.deb&gt;

Thanks for making this available on Linux!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6457d204-d229-9154-28fd-ca9bbb4bddcd
* Version Independent ID: f5d82846-41cb-3548-6997-ce23bd8f89c6
* Content: [Get clients for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/get-clients#feedback)
* Content Source: [Teams/get-clients.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-clients.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Joel-fogue Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@Joel-fogue  Thank you for raising this issue! I'll be looking into it!

**Comment by TokyoScarab** [comment]
@Joel-fogue The reason apt / yum are used in the documentation instead of dpkg -i (dpkg) is because using dpkg will only install the package file but not handle any other dependency or package installation that might be needed in the installation of the original package file. The apt / yum commands will perform those tasks. I hope this answers your question, feel free to follow up if you had any other questions, thanks!

**Comment by scanum** [comment]
@Joel-fogue Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
