### ISSUE TITLE
Change page to descending sort

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3694]
In the point of view of a reader it makes more sense to have the latest updates first and the oldest updates at the end of page. Thus December 2019 should be first, November 2019 last.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3081f70c-d927-ce5d-d957-ca7ba7e07a55
* Version Independent ID: 17704162-7ff9-015c-30a1-1cbc078f0782
* Content: [Microsoft Teams content updates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-updates#feedback)
* Content Source: [Teams/teams-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-updates.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@GiantCrocodile Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @GiantCrocodile, thank you for your feedback.

I'm agree with you but this file is generated automatically each week and I don't have permissions to change the process.

**Comment by GiantCrocodile** [comment]
Hi @dariomws306! Do you know who has necessary permissions and can do this? You might mention the person here or provide the person with a link to this. Thank you!

**Comment by dariomws306** [comment]
Hi @GiantCrocodile, sorry but I couldn't find the author.

**Comment by GiantCrocodile** [comment]
Is this something you can help with @scanum @mypil @LolaJacobsen? I really appreciate it. Thank you!

**Comment by dariomws306** [comment]
To be honest, I'm agree that it makes more sense but I think it's not something critical. It's more "looks better" than something to fix.

**Comment by GiantCrocodile** [comment]
Well, my own experience with Microsoft docs isn't too great and many customers spent many hours on wasting their time with issues with the docs so if I report stuff, I at least hope it gets improved for the future, especially for such pages which are likely to be checked regularly. Right now, I think there is quite some struggle about the docs according to what other customers say/face.

**Comment by dariomws306** [comment]
We respect and consider all the feedback. In this case I am totally agree with you but I understand that it's a small improvement and I don't have the tools to update it.

@LolaJacobsen could you kindly review the process to check if you can see how to change the order?

**Comment by scanum** [comment]
@LolaJacobsen could you kindly review the process to check if you can see how to change the order?

**Comment by dstrome** [comment]
hi @GiantCrocodile @dariomws306 The readability of the topic could definitely be improved by switching the order of the information. It's been a known issue for quite a while. Unfortunately it's not an easy change. The system that processes all the data to generate this topic does so in real time as changes are published live. Due to the way the data is stored, reversing the data when the weekly output is generated isn't a trivial task.

This is definitely something we're aware of and something I'd love to fix. Unfortunately, it's also fairly low priority so I haven't had the opportunity to work on it. But rest assured, this is definitely on my radar and it *will* get fixed...I just don't know when. :)

thanks for your feedback!
David.
