### ISSUE TITLE
部分内容无法显示图片

### ISSUE THREAD

**Issue by areway** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3768]
例如文中的：
:::image type="content" source="media/migrate-slack-to-teams-image3.png" alt-text="从 Slack 迁移到 Teams 的部署规划概述。":::

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7a81e1e5-3fd5-ff19-4f13-30bc2dd4389e
* Version Independent ID: e90e3618-95e7-7dc6-d020-2d0f75fcb6ff
* Content: [从 Slack 迁移到 Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/zh-cn/microsoftteams/migrate-slack-to-teams#feedback)
* Content Source: [Teams/migrate-slack-to-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migrate-slack-to-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officeglobal Could you please check the following? Thanks!

**Comment by OfficeGlobal** [comment]
Investigating

**Comment by OfficeGlobal** [comment]
@scanum it seems, the problem is in the source file, I can see ::: notation there as well
![image](https://user-images.githubusercontent.com/47977325/72713348-2d8e5c80-3b6d-11ea-8418-92469dfafe54.png)
(https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migrate-slack-to-teams.md)

Could you please update the source to "**!\[** ImageDescription **\]\(** ImagePath **\)**" ?

**Comment by scanum** [comment]
@areway Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
