### ISSUE TITLE
YouTube video links are broken...

### ISSUE THREAD

**Issue by gregmilligan** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3780]
All three videos are "null"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e640245-6d25-2165-3792-9bb386a73184
* Version Independent ID: 28951938-7e00-16fd-c216-a569ba94b041
* Content: [Videos - Audio Conferencing in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/audio-conferencing-videos)
* Content Source: [Teams/audio-conferencing-videos.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-videos.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@gregmilligan  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@gregmilligan thank you for reaching out and helping improve MS Docs. @LolaJacobsen please can you assist. It seems the videos are 'private'. Please can you make them public. Thanks.

**Comment by lindspea** [comment]
@LolaJacobsen please could you assist as the videos are still marked as 'private'.

**Comment by scanum** [comment]
@LolaJacobsen Can you please help on this issue? Thanks!

**Comment by SerdarSoysal** [comment]
Thank you for reporting this issue.

It looks like these videos were out of date and retired, but were not removed properly from YouTube. We will redirect this page to the main audio conferencing page (https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-in-office-365) for now. If/when we create new videos, we will augment that page instead of maintaining a separate page like this one.
