### ISSUE TITLE
Insert QoS markers setting

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3821]
Could you please add some clarification as to why the Teams Admin Portal&gt;Meeting settings setting: "Insert QoS markers for real-time traffic" is off by default? 
Also, when this setting should not be turned on and reasoning why?
Why is this setting under "Meetings setting" and not Org-wide settings&gt;Teams settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76c2487c-044d-1349-708a-5841fcb21ab8
* Version Independent ID: b7033454-1a9c-48d4-8004-78415c5feb89
* Content: [Implement Quality of Service in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/qos-in-teams)
* Content Source: [Teams/QoS-in-Teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/QoS-in-Teams.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@SvenBell Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by rimroot** [comment]
I have the same question. Looking forward to get more details.

**Comment by get-itips** [comment]
Hello @SvenBell How are you? Hope you are doing good. 👍 

I am afraid we can not help you on the reason behind design decisions taken by the product team, as to why some settings are under specific menus or why would you disable QoS*, as this issue resource is specifically to report issues in documentation like for example wrong steps or missing parameter descriptions. I recommend in this case you kindly visit [Microsoft Teams User Voice](https://microsoftteams.uservoice.com/) to propose an idea to be heard by the Product Team.

_About Disabling QoS I can give you my field experience, sometimes I would want this for troubleshooting scenarios or because there are already other devices on the network that prioritize packets and you do not want to redundantly add this markings, however that is just my thoughts_

Hope I could help you on your inquiry. Have a great day.

**Comment by get-itips** [comment]
Hello @scanum Manuela please close this thread.

**Comment by scanum** [comment]
@SvenBell Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
