### ISSUE TITLE
wrong PowerShell cmd in Assign a hosted voicemail policy

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3844]
The following example is incorrect:
Get-CsUser -Identity "User1" | Grant-CsHostedVoicemailPolicy -Identity "Tag:CloudVoiceMailUsers"

Correct version:
Get-CsUser -Identity "User1" | Grant-CsHostedVoicemailPolicy -PolicyName "Tag:CloudVoiceMailUsers"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec8b8afb-b9ca-8136-b907-5bbff4c9dcf1
* Version Independent ID: d4f68818-6fe6-5bb7-f108-e26a643f2cc7
* Content: [Configure Cloud Voicemail service for on-premises users - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-cloud-voicemail)
* Content Source: [Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-cloud-voicemail.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by FrankCarius** [comment]
Why was this feedback closed? the doc is still wrong.

In Addition. I tried to "pipeline" the "Get-CSUser" into "Grant-cshostedVoicMailPolicy and got a 
"Grant-CsHostedVoicemailPolicy : The input object cannot be bound to any
parameters for the command either because the command does not take pipeline
input or the input and its properties do not match any of the parameters that
take pipeline input."

Bit it works with Grant-CSHostedVoicemailPolicy -identity "User1" - PolicyName "Tag:CloudVoiceMailUsers"
