### ISSUE TITLE
Microsoft Teams Meeting Length limit?

### ISSUE THREAD

**Issue by erictechtips** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3920]
How long can a Microsoft Teams meeting be?  This page should specify the maximum length (duration) a Teams meeting can be in hours.  You have this specified for live events, but not a regular Teams meeting. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#meetings-and-calls)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@erictechtips  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@erictechtips thank you for reaching out and helping improve MS Docs. It seems the article has been updated in the interim with the various meeting types and their time limits. Please can you have another look and let me know if you have any further questions.

**Comment by erictechtips** [comment]
Is meeting expiration of 60 days the same as Teams meeting length limit?

**Comment by lindspea** [comment]
@erictechtips are you referring to the meet now in Teams?  In that instance it will be 8 hours as per the article. All the others are 60 days from start time.

**Comment by erictechtips** [comment]
No, I am not referring to meet now.  I am referring to a traditional Microsoft Teams meeting that you create from Outlook.  https://support.office.com/en-us/article/schedule-a-teams-meeting-from-outlook-883cc15c-580f-441a-92ea-0992c00a9b0f

**Comment by lindspea** [comment]
@erictechtips thank you for clarifying that. I work on the writing side of the articles, improving the articles where we can, to help other users. This is not relating to the original article in question, so I'll tag @LolaJacobsen and see if she can help answer your question. Otherwise we will have to direct you to support.

**Comment by erictechtips** [comment]
Just to be clear, I could create a Microsoft Teams Meeting and have that Teams meeting stay open/running without interruption for 60 days?  We are trying to determine how long a Teams meeting can stay open without interruption.  In the past with Skype for Business there was a 90 minute limit we experienced. Some people have told us 4 hours is the limit for a Teams meeting, but this Microsoft document says 60 days is the limit, and that is why we are trying to get clarification.

**Comment by davidplesinger** [comment]
I'm just testing - now have open relation for 6 hours and it is still running - what amazing! (and still recording!)

**Comment by leegaupp** [comment]
would love to see an answer on how long a normal Teams meeting, not recorded, can be. Folks in my company are asking me.

**Comment by davidplesinger** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Hi, 7H30 works surelly - last weekend tested;-)                                                                                                                                                                                                                                                                                                                         Od: notifications@github.comOdesláno: 26. března 2020 22:43Komu: OfficeDocs-SkypeForBusiness@noreply.github.comOdpověď komu: reply@reply.github.comKopie: david.plesinger@gmail.com; comment@noreply.github.comPředmět: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Microsoft Teams Meeting Length limit? (#3920)  
would love to see an answer on how long a normal Teams meeting, not recorded, can be. Folks in my company are asking me.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by LolaJacobsen** [comment]
I'm pretty sure there's no limit. I'll check with the PM to confirm.

**Comment by LolaJacobsen** [comment]
Per PM, limit is 24 hours. I'll update documentation accordingly. Thanks for the inquiry!

**Comment by mark-szabo** [comment]
@LolaJacobsen can you please include the Recording Limit into the documentation as well? There is a 4 hour limit which is not documented anywhere (as far as I found). Thanks!

**Comment by mark-szabo** [comment]
@LolaJacobsen should I open a separate ticket for this?

**Comment by decortech** [comment]
I just did a 5 hour recording and it recorded everything however the video automatically split around the 3 hour mark (filesize was around 1.4GB for the 3 hr video). I noticed some glitches with the audio towards the end of the 3 hour recording and the beginning of the 2 hr recording and then it went back to normal so I'll be doing some more testing. I was using the web client on the computer (Mac Catalina) that was screen sharing. Was using a Mac running 10.13.6 that initiated the screen record using the Teams client. Both machines using wifi to connect and headphones to separate the audio input and output. I was running into audio clarity issues not using headphones when recording.

**Comment by vinayshekhar-github** [comment]
Agree with @redmondChris  - Can we please re-confirm "What is the maximum duration of a recording in a Teams Meeting?". What if there's a day long event and they want it to be recorded completely? Please clarify @LolaJacobsen

**Comment by jepp** [comment]
As we have a type of "portal" meeting connecting remote workers and a specific machine in the office, I can confirm that the meeting ends at just slightly over 24 hours. Has happened multiple times. Wish it was either unlimited, or actually shorter (configurable?). If it was, say, 18 hours, the meeting would automatically end and someone would know they need to establish a new one the next day. As it stands, people rejoin the new one the next day and then it boots everyone off in the middle of the day.

**Comment by mosoftwareenterprises** [comment]
I know this is old, but found that a meeting is limited to 30 hours, documented here: https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams
