### ISSUE TITLE
Clarity on future of hybrid deployments

### ISSUE THREAD

**Issue by dooleydo** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3957]
This article does not make it clear what the impact is on a hybrid deployment.

For example, after  July 31, 2021 does the hybrid need to be split away from SfBO (no longer a split SIP domain) and become on-prem only if you are keeping it?

If that is the case how will those who were homed online in SfBO join an on-premises meeting with a user who is now on-prem only because the hybrid is now split?  What credentials would they be able to use to join a SfB meeting once they are a teamsonly user?  Will they need moving back to the on-prem part of the hybrid deployment?

This statement "Upgrade paths for hybrid configurations built around principles of coexistence and interoperability will remain after the retirement of Skype for Business Online." needs to be clearer as to what that means for users who are now on Teams but still need to use the SfB client to joing SfB meetings they may receive from their on-premises colleagues or federated partners who may continue to use SfB on-premises for many years.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbeb59c4-349f-944c-5183-4fb26a34c22b
* Version Independent ID: 2beb18af-35a6-de0a-d90f-89c94533b8da
* Content: [FAQ — Upgrading from Skype for Business to Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/faq-journey)
* Content Source: [Teams/FAQ-journey.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/FAQ-journey.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@dooleydo  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @dooleydo, thank you for your feedback.

I have added two article where you can find this information. For example:

If that is the case how will those who were homed online in SfBO join an on-premises meeting with a user who is now on-prem only because the hybrid is now split? What credentials would they be able to use to join a SfB meeting once they are a teamsonly user? Will they need moving back to the on-prem part of the hybrid deployment?
https://docs.microsoft.com/microsoftteams/teams-and-skypeforbusiness-coexistence-and-interoperability#interop-escalation-experiences

**Comment by scanum** [comment]
@dooleydo Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
