### ISSUE TITLE
Azure Boards for Microsoft Teams

### ISSUE THREAD

**Issue by sanjeev40084** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#3969]
Any timeline when Azure Boards for Microsoft Teams will be availablen for GCC tenants?
https://appsource.microsoft.com/en-us/product/office/WA200000644?src=wnblogmar2018

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7faee29-6d56-f3bf-766c-6deaefe92e34
* Version Independent ID: 6029b6f8-7d49-6474-fa40-2793000c74a4
* Content: [Plan for Microsoft 365 Government - GCC deployments - Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/plan-for-government-gcc#feedback)
* Content Source: [Teams/plan-for-government-gcc.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-for-government-gcc.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@sanjeev40084  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @sanjeev40084, thank you for your feedback.

The place to check this information is Microsoft 365 Roadmap:
https://www.microsoft.com/microsoft-365/roadmap

For example, I think there is no timeline for Azure Boards as they are working on integration with OneNote:
https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=GCC&searchterms=integration%2Cin%2Cteams

Please filter by GCC. 3rd party Apps or Bots are difficult to enable on GCC due to compliance reason.

**Comment by scanum** [comment]
@sanjeev40084 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
