### ISSUE TITLE
Video links are broken

### ISSUE THREAD

**Issue by olwigs** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4190]
Video links are broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e640245-6d25-2165-3792-9bb386a73184
* Version Independent ID: 28951938-7e00-16fd-c216-a569ba94b041
* Content: [Videos - Audio Conferencing in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-videos#feedback)
* Content Source: [Teams/audio-conferencing-videos.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audio-conferencing-videos.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@olwigs Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@LolaJacobsen Hi Lola, could you please make the video links public as I see they are all marked 'private'. Thank you.

**Comment by SerdarSoysal** [comment]
Thank you for reporting this issue.

It looks like these videos were out of date and retired, but were not removed properly from YouTube. We will redirect this page to the main audio conferencing page (https://docs.microsoft.com/en-us/microsoftteams/audio-conferencing-in-office-365) for now. If/when we create new videos, we will augment that page instead of maintaining a separate page like this one.
