### ISSUE TITLE
Is the Teams service really included in Office 365 ProPlus

### ISSUE THREAD

**Issue by MagnusAlgard** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4335]
Hi,

Can you please clarify this add-on options for Office 365 ProPlus.
As far as I know, the Teams service (the service, not the App) is not included in the Office 365 ProPlus subscription. How can you then purchase this add-ons without having a subscription for the service?

BR, Magnus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db81c7c-eb67-30a3-906b-1cebe7e6983d
* Version Independent ID: d98b0936-b477-3ecd-521b-91fb8b5ffd69
* Content: [Office 365 ProPlus  - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/office-365-premium-pro-plus#feedback)
* Content Source: [Teams/teams-add-on-licensing/office-365-premium-pro-plus.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/office-365-premium-pro-plus.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@MagnusAlgard thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by MagnusAlgard** [comment]
Thanks, would really appritiate an answer here.
I ask for a customer. I don´t have access to the customers tenant.

**Comment by tonysmit** [comment]
Hi @MagnusAlgard - Teams is included in ProPlus.

**Comment by MagnusAlgard** [comment]
Can you please provide me with a link?
Im talking about the service and not the client. 
Its not listed in this article
https://docs.microsoft.com/en-us/microsoftteams/office-365-licensing
In this article its included as an app but not as a feature:
https://products.office.com/en-us/business/office-365-proplus-product?activetab=pivot%3aoverviewtab

**Comment by tonysmit** [comment]
Quick search I found these. For the first link, it's included as part of those licenses. The second link must be out of date, because I personally know that it's included in ProPlus now. Look in the table in the first link. It says "partially", because if you want Cloud Voice, you must purchase Business Voice or add Audio Conferencing, Phone System and a Calling Plan (Domestic or International). 

https://www.microsoft.com/en-us/microsoft-365/business/compare-more-office-365-for-business-plans?rtc=1&OCID=AID2000748_SEM_qn3dq3qQ&MarinID=qn3dq3qQ|79577274239788|office%20proplus|be|c||1273234588008620|kwd-79577224802635:loc-190&lnkd=Bing_O365SMB_Brand&msclkid=4fafa9fbab7c1b8bf352f77c380e35cb&ef_id=W3uVDQAAAMeI6gNC:20200403195014:s

https://support.office.com/en-us/article/How-do-I-get-access-to-Microsoft-Teams-fc7f1634-abd3-4f26-a597-9df16e4ca65b
