### ISSUE TITLE
How long does the trial last? whast is the expiry date?

### ISSUE THREAD

**Issue by Lumute** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4379]
Could you please clarify what is the length of the Trial?

Our company does not have an enterprise agreement, we get our Office 365 licenses from a CSP so how do I know when these people who are currently using the trial "Exploratory Experience" licenses will need a full Office 365 license that includes Teams in order to continue using it? we need to be able to account and budget for that... Looking at the subscription in the Office 365 Admin Center the expiry says "Expires July 1, 2853", somehow I don't think this is the date when the trial itself for each user will run out, that would basically make them perpetual... Looking at how things are going these days I don't think humanity in general will reach that year...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f897ae9b-852a-b617-7de0-d76dbd9f1820
* Version Independent ID: 161b1845-53fd-8912-a5f9-737d3bcdaadc
* Content: [Manage the Microsoft Teams Exploratory experience - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-exploratory#feedback)
* Content Source: [Teams/teams-exploratory.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-exploratory.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Lumute Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Lumute thank you for reaching out and helping improve MS Docs. I'm not seeing where it states "2853"? The article says "The Microsoft Teams Exploratory experience is available at no additional cost until your next enterprise agreement anniversary or renewal on or after January 2021." Let me know if you need further help.

**Comment by Lumute** [comment]
No, it does not say it in the article, the article is lacking information because not everyone has an EA agreement. As I stated in my comment the only indication of when could this expire is the subscription expiry in the company's admin portal, that's where the 2853 comes from and likely not the real trial expiry date.... yes we do need further help, we need to know when this trial really expires for regular /  no EA customers...

**Comment by royalhomemilk** [comment]
@lumute AMEN BROTHER. NOT EVERYBODY HAS EA licenses and they still see the expiration date of 2853 AND EVEN the customers with EA licenses see expiration date of 2853 or something.
Please MAKE IT CLEAR WHEN THE EXPIRATION DATE IS.

**Comment by lindspea** [comment]
@Lumute I'll check with the team and get back to you as soon as I have a definite answer.

**Comment by bkeski** [comment]
I have >600 customers (tenants), none of them have EA - so how long this Teams Exploratory lasts? How is possible to make Teams Exploratory available to all customers but not to know how long this trial lasts (except for EA cutomers)?

**Comment by lindspea** [comment]
@LolaJacobsen could you perhaps assist with the answer please?  Is it the same 1 -year trial as the Microsoft Teams Commercial Cloud Trial was?

**Comment by Richsaunds** [comment]
@lindspea we also need an answer on this for several of our customers who are also all CSP based, with no EA.

Thanks
Rich

**Comment by sm709** [comment]
Hi any update here? i have CSP customers asking the same question!!

**Comment by lindspea** [comment]
@LolaJacobsen under admin portal, billing > Products & Services, Microsoft Teams Exploratory Trial, it says it expires 5/23/53. Please could you let us know how long the trial lasts?

**Comment by turbon13** [comment]
Great, wish this was published around the place more. I would expect that expiration to be accurate.

As an on prem customer and non O365 customer or EA holder, I would expect nothing less when others can access a freemium version.

We're under 100 seat thankfully, but think that user limit should also be given consideration to have another zero added to it or the limit totally removed.

Anything Microsoft can do stop people using other products given the current climate, complexity of Teams signup issues for domain environments and quantity of programs on offer and their ease of use/signup; is worth considering.

**Comment by LolaJacobsen** [comment]
@Balu-msft please review this PR. Let me know if you approve and I'll merge.

**Comment by LolaJacobsen** [comment]
We updated the article in response to the issue yesterday - check it out:
https://docs.microsoft.com/microsoftteams/teams-exploratory

**Comment by bkeski** [comment]
> We updated the article in response to the issue yesterday - check it out:
> https://docs.microsoft.com/microsoftteams/teams-exploratory

I can't see any new information about ending for non-EA customers

**Comment by royalhomemilk** [comment]
Neither do I see anything about non EA subscribers.. Also even the
customers with EA licesenses see 2085 expiration date... Does it mean the
subscription will last until 2085?

**Comment by royalhomemilk** [comment]
Will the EA license customers lose access to Teams Exploratory after January 2021? (Even with the product & services tab showing the expiration year of 2085.) If so, shouldn't it be fixed or something on the portal webpage..... The customers will think the subscription lasts forever.

**Comment by lindspea** [comment]
@Lumute This applies to any agreement or renewal post Jan 2021.

**Comment by Hakuon** [comment]
Thanks for the sharing

**Comment by Hakuon** [comment]
Test

**Comment by ee61re** [comment]
this seems to still be an issue - for example I have a customer with these trial licenses - initial purchase date shows as 26/03/2020 - so according to the article it should have expired 26/03/2021 - but here we are 5 months later, and it shows no signs of expiring.

**Comment by ford-polarwind** [comment]
Its 7th of September 2021 and MS still shows date 2853 in our Portal.
Is this now official? I cannot find anything on the MS websites.

**Comment by GithOmar** [comment]
> acuerdo o renovación posterior a enero de 2021.

Hello, I have a License acquired in October 2020 via portal for Education (free nonprofit Office 365). However, in the terms shown in the administrator it ends in 2854.
I see you comment that Tems exploratory only remains 12 months from Licenses acquired after 2021, my question is if it applies to my license (2020). Honestly, this has caused me horrible discomfort, since I asked Microsoft about this and they answered that it would only last 12 months, however from Microsoft nonprofit they answered that if it came from them it should not expire after 12 months because (and even) not yet They have defined their policy regarding Nonprofit Licenses for Education.
I obtained benefit sending my School documents, a week later recived an approving response from 'Techsoup' partner whit email for create Domain and account (your request has been approved for receive Office 365 Educational account nonprofit). However an Office Ambassador contacted me several times because apparently an internal problem has been generated with Microsoft and Techsoup, according to Microsoft they dont have my documents in database. Again enter my Techsoup account and all documents exist, also send Tecshoup ​​Mail to MS with the 'email approving'. So MS Ambassador asked me 'send all documents directly' which I did. AGAIN Techsoup (mediocre and foolishly) asked me for documents as I new applicant ... IN short, MS never receives documents directly (even when requests) only through Techsoup, i think 'loses them purpose', this despairs users and is possibly a 'harassment or revenge maneuver. ' PLEASE how time for my license (expire in 2854) obtained in 2020? ...

**Comment by SnipexTV** [comment]
> Its 7th of September 2021 and MS still shows date 2853 in our Portal. Is this now official? I cannot find anything on the MS websites.

Still there.
