### ISSUE TITLE
There is big confuse about the Direct Routing Hybrid number

### ISSUE THREAD

**Issue by tangx007** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4384]
There is big confuse about the Direct Routing Hybrid number under step 3. What is Hybrid number? Is it a local DID number or MSFT hosted telephone number? 

I suggest to modify the Hybrid number to local DID number or onpremise DID number is easy to understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0703860-c3db-c723-317f-7fab164c006d
* Version Independent ID: c6384e2b-ac37-265d-8c33-f004eca97673
* Content: [Configure a resource account in Skype for Business Server 2019 - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/configure-onprem-ra#moving-an-exchange-um-auto-attendant-or-call-queue-to-phone-system)
* Content Source: [Skype/SfbHybrid/hybrid/configure-onprem-ra.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/configure-onprem-ra.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@tangx007 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @tangx007, thank you for your feedback.

I couldn't find "Direct Routing Hybrid number" under step 3. I see some related information under step 6. Direct Routing or hybrid number are the same.

**Comment by tangx007** [comment]
OK, "step 3" is my typo. It should under step 6.

So, under step 6 : "To assign a direct routing or hybrid number to a resource account, use the following cmdlet", the hybrid number is confuse for the reader since this article is for Skype for Business Server 2019.

**Comment by dariomws** [comment]
@tangx007, this issue is very similar or even the same as https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4385.

This article is related to SfB Hybrid:
"**Skype for Business Server 2019 hybrid implementations** only use Cloud services provided by Phone System for unified messaging and do not integrate with Exchange Online. In Skype for Business Server 2019 you are now able to use the Cloud call queues and auto attendants described in Here's what you get with Phone System in Office 365.

To use an Phone System auto attendant or call queue with Skype for Business Server 2019, you will need to create resource accounts that act as application endpoints and can be assigned phone numbers, then use the online Teams admin center to configure the call queue or auto attendant. **This resource account can be homed online** (see Manage resource accounts in Microsoft Teams to create resource accounts homed online) or **on premises as described in this article**. Typically you will have multiple Phone System auto attendant or call queue nodes, each of which is mapped to a resource accounts, which can be homed online or in Skype for Business Server 2019."

For more information: https://docs.microsoft.com/skypeforbusiness/hybrid/plan-cloud-auto-attendant. I think the diagram there is self-explanatory.

Anyway, I'm reviewing the document again to see if we can improve it.

**Comment by tangx007** [comment]
Thanks, and pls help to improve it.

**Comment by scanum** [comment]
Hi @tangx007 we thank you for submitting feedback! This issue has been solved. However, for your other questions I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
