### ISSUE TITLE
Missing info on what happens when your record a meeting without pre-requisites

### ISSUE THREAD

**Issue by redmondChris** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4409]
When a user does not have a Stream license and chooses to record the meeting, the meeting still gets recorded and put somewhere. Documentation (perhaps a separate page) is needed to explain how to manage such non-Stream recordings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#feedback)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@redmondChris Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @redmondChris, thank you for your feedback.

I think you have read the following sentence:
"User needs to be licensed to upload/download meetings to/from Microsoft Stream, however they do not need the license to record a meeting. If you wish to block a user from recording a Microsoft Teams Meeting, you must grant a TeamsMeetingPolicy that has AllowCloudRecording set to $False."

@tonysmit could you kindly help to confirm where this is stored? nowhere? Thanks!

**Comment by kw-work** [comment]
Yes, more details would be helpful. We do not have Stream enabled and users are recording in Teams.  Recordings are available in Teams, but for how long?  Where are they stored?  Can they shared/downloaded/moved to OneDrive? If they expire, how long are they available via eDiscovery?

**Comment by O365EDU** [comment]
We only allow a few users to record to Stream, the rest record and download it.     We are unable to delete any of the non Stream recordings.  How do you delete the recording or the message about the recording ?

**Comment by scanum** [comment]
@tonysmit Wondering if there are any updates here? Thanks

**Comment by Markus-Hanisch** [comment]
Hi there, I need to follow this issue as well.
I found the following table: [Microsoft Support: Play and share a meeting recording in Teams > Who can view a meeting recording?](https://support.office.com/en-us/article/Play-and-share-a-meeting-recording-in-Teams-7d7e5dc5-9ae4-4b94-8589-27496037e8fa#bkmk_whocanview)

Is there any option provided for administrators to delete meeting recordings that are not stored in Microsoft Stream? And how can I retrieve these recordings from other meeting organizers?

**Comment by tonysmit** [comment]
@sonu-arora - Please respond.

**Comment by tonysmit** [comment]
Update. I found the new PM owner. A couple things. To produce or present they must have the following
-E1/3/5 or Education A3/A5
- Teams license included in the those plans.
- Steam license is ONLY required if you are planning to share the content to an external app or device. Details here: https://docs.microsoft.com/en-us/stream/license-overview

As you have said above, if the user is assigned E1/3/5, A3/5 then they will store recordings in Stream. And if they have the E1/3/5, A3/5, and want to share content, yes, they will need a Steams license. If they don't have a Steams license (because you don't want to assign one for whatever the reason), then the recordings are stored in Azure Media Services (AMS) with a 30 day limit before it's deleted. It's not something at this point that an admin can control including to delete it. 

@redmondChris and I have a chat going and he had this information. He is tracking a feature request to get controls added. I'm tracking a feature to see if we can get a setting added to Teams live event settings in the Teams Admin Center. I've also reached out the PM owner to see about getting this information added to the article. 

I hope this helps everyone here. And a big thank you to @redmondChris!
