### ISSUE TITLE
Microsoft 365 groups?

### ISSUE THREAD

**Issue by nielsbrinch2** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4460]
It looks like all product suites are now changed to Microsoft 365 and the Office 365 name is going away. I wonder, should the groups not also be renamed to Microsoft 365 groups?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d86301b-ce9c-388c-e563-9e5e5c27132e
* Version Independent ID: 07e4ae23-0966-e8f3-9b7c-4f6c02569eb0
* Content: [Office 365 Groups and Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/office-365-groups#feedback)
* Content Source: [Teams/Office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Office-365-groups.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@nielsbrinch2  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@nielsbrinch2 Thank you for this valid feedback. I would say the answer is yes, but this needs to be a coordinated effort, because all the docs need to be changed to reflect this, not just the doc you mentioned. Keeping this in mind, i don't think it makes sense to change only this doc, since all the others will still talk about Office 365 Groups.

@scanum could we ask the authors if/when there will be a coordinated change from Office 365 Groups to Microsoft 365 Groups?

**Comment by scanum** [comment]
@LolaJacobsen Hi Lola, could you please help with this question: When there will be a coordinated change from Office 365 Groups to Microsoft 365 Groups?Thanks!

**Comment by LolaJacobsen** [comment]
A giant "rebranding" effort is underway now. Stay tuned for all instances to be updated over the upcoming days.
