### ISSUE TITLE
Formatting Issues

### ISSUE THREAD

**Issue by ndambrosio** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#447]
Hello Tony, Looks like there are some formatting/style issues within this article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 402ea6ea-0917-9815-06d7-eaceb592a7b7
* Version Independent ID: bdcb2be8-fc79-d4bf-4b45-2ca0634700e1
* Content: [Data collection practices](https://docs.microsoft.com/en-us/skypeforbusiness/legal-and-regulatory/data-collection-practices)
* Content Source: [Skype/SfbOnline/legal-and-regulatory/data-collection-practices.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/legal-and-regulatory/data-collection-practices.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@ndambrosio - sorry for the delay. Thank you for reporting. The issue was with GitHub merge conflict. I went ahead and resolved and here is the Pull Request with fix. https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/530  If you see anything that was removed in the merge conflict let me know and I can add back. Thanks again for reporting!
