### ISSUE TITLE
Automatically admit people

### ISSUE THREAD

**Issue by taromielnaz** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4522]
Hello, 
Although I set the policy to "Everyone in your organization and federated organizations" in Global(Org-Wide default) policy, individual users see this setting to everyone in their meeting option.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc665475-f843-e4c1-0ca6-0b83873abb54
* Version Independent ID: 95d32598-c920-ed5c-d665-69394528ca27
* Content: [Manage meeting policies - Microsoft Teams](https://docs.microsoft.com/en-US/microsoftteams/meeting-policies-in-teams?WT.mc_id=TeamsAdminCenterCSH#feedback)
* Content Source: [Teams/meeting-policies-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-in-teams.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@taromielnaz Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by clusterb0mb** [comment]
I set AutoAdmittedUsers from EveryoneInCompany to Everyone in the Global(Org-Wide default) policy but nothing changed for external users.

**Comment by michael-clover** [comment]
I've seen both of these
The meeting options seem to took about 24 hours to update to match the assigned policy for the user 

For organisers with on-prem exchange mailboxes external users (particularly dialin users) were left  in the lobby regardless of the setting of AutoAdmittedUsers. This seems to have improved for me.

**Comment by leewegener** [comment]
I am also experiencing these same issues. Regardless of policy settings, external users are unable to bypass the lobby or start the meeting without the meeting organizer admitting them. This prevents users from scheduling a meeting and joining a conference call without an organizer admitting participants from the Teams application.

**Comment by MonroB** [comment]
We gave up waiting on this. 
If you create a new policy (not Org-Wide default), the change will apply.
Alternatively it is possible to create a new policy using PS. But this is a bit difficult in a hybrid environment.

**Comment by VLG17** [comment]
@taromielnaz Just to confirm, are you saying that although you update the "**Who can bypass the lobby**" setting in the **Global (Org-Wide default) policy** to "**Everyone in your organization and federated organizations**", external users (guest users and the users from trusted organizations) are still unable to bypass the lobby?

As mentioned above, there are a few things to keep in mind, which could play a role:

- Is it a hybrid environment where the organizer's mailbox still resides on-premises?
- Have you waited 24 hrs for the change to propagate?
- Does this happen regardless of who the organizer is? Could you test with different organizers just to confirm this is a general issue?

Since we focus on the documentation and updating it when necessary, i would advise you to reach [contact support](https://support.office.com/en-us/home/contact?ContactUsExperienceEntryPointAssetId=S.HP.teams) and let them look into this. If the conclusion is that the documentation needs to be changed, we will glandly do that.

**Comment by leewegener** [comment]
@MonroB This was the solution for us as well. I needed to create a new policy with the bypass settings I wanted and apply that to my users.

**Comment by scanum** [comment]
@michael-clover  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
