### ISSUE TITLE
This page still has conflicting information.

### ISSUE THREAD

**Issue by ZugBug** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4569]
Per the other closed comment this page advises that Audio Conferencing is not available in India but numbers can be automatically assigned in Chennai and Mumbai.

Additionally this page allows Indian customers to buy audio conferencing: https://products.office.com/en-in/microsoft-teams/online-meeting-solutions#customerstoryregion2

But after purchasing Audio Conferencing directly Indian customers are finding that it does not work.  Can we have clarification around whether or not Indian customers should be able to purchase Audio Conferencing directly from us? Currently they can, but it doesn't work, and the documentation says they shouldn't be able to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add0081a-1bc7-51fa-845b-7ed394f16bb6
* Version Independent ID: 111b52ae-0b89-6cca-372c-549f4a7055b5
* Content: [Availability in India - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-india#feedback)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-india.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-india.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@ZugBug  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @ZugBug, thank you for your feedback.

I think you need to buy it through TATA to get it working. But seems strange that you can buy it directly and it doesn´t work.

@rjagiewich @ruizoscar could you kindly help?

**Comment by scanum** [comment]
@rjagiewich @ruizoscar @tiburd Any update here? Thanks!

**Comment by dariomws** [comment]
@rjagiewich @ruizoscar @tiburd Could you kindly help? Thanks!

**Comment by ruizoscar** [comment]
As outlined in the documentation, the following information is accurate in regard to the purchasing availability of the audio conf. service in India:
- Is Audio Conferencing available for purchase? | Microsoft doesn’t sell Audio Conferencing in India. TATA Communications offers a dial-in and dial-out service that is compatible with Microsoft Teams Meetings. For more information, please visit TATA Communications' website.

The part that outlines numbers can be automatically assigned in Chennai and Mumbai, is applicable to customer that purchase the service from one of the countries where the service is available for purchase, i.e. a US customer that purchases Audio Conf. will get a number from Chennai or Mumbai.

The information int he documents is not conflicting with each other since once refers to the availability of phone numbers and the other to where the service is available for purchase

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
