### ISSUE TITLE
Forever, really?

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4670]
I'm out on the frontline and away from all of that Redmond air, but I have to challenge this sentence "By default, Teams chat, channel, and files data are retained forever." Will it still be there after the Channel is deleted? If the Group is deleted? If the tenant is de-provisioned? If you put this sentence in an article, customer will expect that Microsoft will help them to find that one chat where someone mentioned the secret Coke recipe long after Teams has evolved to it's next shifted shape. Please consider deleting this sentence to something less … all encompassing, and more practical.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c52a5-5841-b9c9-1607-2013dc3f2e20
* Version Independent ID: 16d93458-5e01-646f-dac5-31306cc7f3fb
* Content: [Retention policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/retention-policies#feedback)
* Content Source: [Teams/retention-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@Jmartinez589 Thank you for submitting feedback and contributing to the docs. Dario is currently fixing this issue.

**Comment by anwara-ms** [comment]
so what exactly are we doing about it, there was a similar concern here--> https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4591

**Comment by exactmike** [comment]
the word 'indefinitely' might be appropriate here instead of 'forever'.  The context does a good job of clarifying already: "By default, Teams chat, channel, and files data are retained forever, unless there is an attempt to delete the content via retention policies, user deletes, admin deletes etc." so if that were changed to (adding a couple other scenarios to the example): "By default, Teams chat, channel, and files data are retained indefinitely, unless there is an attempt to delete the content via retention policies, user deletes, admin deletes, team deletion, tenant deletion, etc."

**Comment by anwara-ms** [comment]
thanks. made the change. https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/4836

@MicrosoftHeidi

**Comment by scanum** [comment]
@Jmartinez589 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
