### ISSUE TITLE
F1 > F3

### ISSUE THREAD

**Issue by O365scripts** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4671]
Can we add the F3 given it has changed name from it's previous F1 name at the start of this month?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35057f71-792b-a4e2-a2ee-a4908c11f3a4
* Version Independent ID: 7e23f067-1dcd-16f0-3f9a-ff8d13c1f659
* Content: [What is Microsoft 365 Business Voice? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/business-voice/whats-business-voice)
* Content Source: [Teams/business-voice/whats-business-voice.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/business-voice/whats-business-voice.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@O365scripts Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by MaratMussabekov** [comment]
Issue is fixed by https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/3ac32fbb70cf2042e9976c2a973a2feaee458d85#diff-40581e7a4083387551a935e06f8c0646 and https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/commit/117ebf4ba60ad7b5f42d0bc19a3b3dfa81483168#diff-40581e7a4083387551a935e06f8c0646
I believe the ticket could be closed.
Thank you

**Comment by scanum** [comment]
@O365scripts We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
