### ISSUE TITLE
visual c++ 2017 14.10.25008

### ISSUE THREAD

**Issue by rimroot** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#468]
It requires visual c++ 2017 14.10.25008 version. I have 14.14.26429 installed, however it does not accept it. Is it a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27364aed-dc10-dcaf-8446-bc93e39bd4ca
* Version Independent ID: 907a29a6-6ff3-5c91-5c74-cf98cf71ad88
* Content: [Download and install the Skype for Business Online Connector module](https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector)
* Content Source: [Skype/SfbOnline/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by rameshms85** [comment]
Same happens for me. I am sure its a bug.

**Comment by colletolivier** [comment]
Same bug for me. Nobody has idea ?

**Comment by rameshms85** [comment]
Also worked for me. Thank you Matt!

**Comment by JeremyTBradshaw** [comment]
Here's a link to the TechSpot download - https://www.techspot.com/downloads/6776-visual-c-redistributable-package.html
It's a bug for me too.  Seems like a dinky bug for such an important tool.

**Comment by kenwith** [comment]
Thank you for this report. I am opening a bug with the product team to get this resolved. I am going to emphasise how important it is and if everyone experiencing could please open a service request it will add the weight that it is being experienced by many customers.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

Thank you for reporting here. Let me know if there is somethign I can add in the docs once this is resolved.

**Comment by rpstester** [comment]
I still got this error.  
![skype powershell needs visual c](https://user-images.githubusercontent.com/32249806/46211403-74fe3300-c301-11e8-8f4a-90dcf710fd46.png)

**Comment by AndreaBarr** [comment]
@rpstester Thank you for this feedback. 

I want to make sure you get help with this error in the best way possible. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by JeremyTBradshaw** [comment]
@AndreaBarr I know this isn't my issue.  But this is 3 issues in a row within ~5 days where you're telling people to go and open support tickets with Microsoft then come back and update the issues with the answers.  As far as I can tell, this isn't how docs' content is supposed to be getting built and improved.

There's a known issue with the installer for the Skype PowerShell module.  It's Microsoft's problem and you guys (Microsoft) should go and get support internally to fix it.  There is enough evidence in this thread and just on the internet about this issue that it is clear @rpstester opening a case is going to have little value to the real problem.  It might help with with a workaround for him/her, but that's it.

I'm pretty much done contributing to docs anymore because of this.

**Comment by kenwith** [comment]
@JeremyTBradshaw - the reason we are asking anyone with this issue, or any product related support issue, to go to support and open a service ticket is because they are setup with a system to escalate issues to the product team. The support team tracks all of these issues together and escalates to the right teams and has a system in place to keep everyone with the issue updated and moving towards a resolution in the fastest path. 

We are a small team that coordinates the content in the docs but we don't have any system to provide support or escalate issues the way the official support teams do.

We greatly appreciate any help and feedback on the docs and I am sorry you are feeling so frustrated.

I do know @CorbinMeek on the support team and I am sure this is on his teams radar but will tag him here for his visibility too.

I am going to 'close' this issue on GitHub but as you have seen any comment will re-open the issue and it will appear on my radar again so I can answer or provide any more information.

**Comment by 541Matt** [comment]
I had the same issue (and with the same version as the OP). I uninstalled the newer version 14.14.26429. I re-ran the Skype connector installer and it installed the version that it needed (the error says it needed 14.10.25008 , but it installed 14.10.25017). You don't need to download the old version from Techspot since the prerequisite version is included in the module installer.

**Comment by TiloGit** [comment]
Got Error today when installing  **SkypeOnlinePowerShell.Exe 7.0.1994.0**
```
---------------------------
Skype for Business Online, Windows PowerShell Module Setup
---------------------------
Skype for Business Online, Windows PowerShell Module installation or uninstallation requires that Microsoft Visual C++ 2017 x64 Minimum Runtime - 14.10.25008 Package is already installed.
---------------------------
OK   
---------------------------
```

Downloaded here latest **vc_redist.x64.exe (which was 14.22.27821.0)**
https://support.microsoft.com/en-ca/help/2977003/the-latest-supported-visual-c-downloads

now the install completed successfully

**Comment by saderemipcgus** [comment]
This issue still exists almost 2 years after it was initially reported..

**Comment by TiloGit** [comment]
I had the issue on WIn 2019 server

```powershell
PS C:\Users\tilos> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0
```

**Comment by Petri-X** [comment]
@CorbinMeek 
Here is screen capture from Win10 machine;
![image](https://user-images.githubusercontent.com/43988151/76730668-66f5d980-6764-11ea-820a-a61aab62d994.png)

And on the same machine:
![image](https://user-images.githubusercontent.com/43988151/76730692-75dc8c00-6764-11ea-8cd1-962907f731cc.png)

The module I'm installing is: SkypeOnlinePowerShell - Ver. 2046.123.exe

IF you e.g. go to the download page:
[Download: Skype for Business Online, Windows PowerShell Module](https://www.microsoft.com/en-us/download/details.aspx?id=39366)
There is no words about C++ as pre-requisites. Okay, there isn't either anything about W10, so perhaps some updates are still missing :)

**Big question is, does it really need the C++**? Or is this just old habit from Skype on-prem? Could it be so, that module itself is working just fine if you copy it into modules folder?

Then, I did a bit more testing and actually found one workaround. On the logs you could see, the installation process is looking for:
```
MSI (s) (AC:FC) [09:12:14:215]: Note: 1: 2262 2: Signature 3: -2147287038 
MSI (s) (AC:FC) [09:12:14:215]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64 3: 2 
MSI (s) (AC:FC) [09:12:14:215]: Note: 1: 2262 2: Signature 3: -2147287038
```
But I only had (note the "**debug**":
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\debug\x64
    Version    REG_SZ    v14.14.26405.00
    Installed    REG_DWORD    0x1
    Major    REG_DWORD    0xe
    Minor    REG_DWORD    0xe
    Bld    REG_DWORD    0x6725
    Rbld    REG_DWORD    0x0
```
Just for testing purposes I copied the x64 hive under Runtimes also, and voilà, I was able to run the installation and connecting to Skype Online.

Let see if there is coming something else on where I can see this is not working.

**Comment by ckssaas** [comment]
9/23/20 and this bug still hasn't been fixed.

I got SkypeOnlinePowerShell.exe installed by downloading/installing MVC++ 14.27.29016 from [Techspot ](https://www.techspot.com/downloads/6776-visual-c-redistributable-package.html) then restarting. Error went away.
