### ISSUE TITLE
Teams Cloud Storage - TTL on recordings

### ISSUE THREAD

**Issue by danieldhudson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4949]
In the Important note at the beginning of the article, it states:

"Users won't need a Microsoft Stream license assigned if you want users to only record and download the recordings. This will mean that the recordings aren't stored in Microsoft Stream but are instead stored in Azure Media Services (AMS) with a 30 day limit before it's deleted."

But later on in the Where your meeting recordings are stored section, it states:

"If the recording doesn't get uploaded to Stream, it's stored in Teams cloud storage, where it's available for download for 20 days."

So I suppose 2 questions, where is the recording actually stored for non-Stream uploaded videos (AMS or Teams cloud storage) and is it 30 days or 20 days?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 976b8a9b-5a3e-1f3b-b848-d1dfbfd3389d
* Version Independent ID: 2b13a471-3baf-0086-439a-f94abb162fd6
* Content: [Teams cloud meeting recording - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cloud-recording#feedback)
* Content Source: [Teams/cloud-recording.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/cloud-recording.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by scanum** [comment]
@danieldhudson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@danieldhudson thank you for reaching out and helping improve MS Docs. There is another similar related issue https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/4409. Please see the comments: ..."if the user is assigned E1/3/5, A3/5 then they will store recordings in Stream. And if they have the E1/3/5, A3/5, and want to share content, yes, they will need a Steams license. If they don't have a Steams license (because you don't want to assign one for whatever the reason), then the recordings are stored in Azure Media Services (AMS) with a 30 day limit before it's deleted. It's not something at this point that an admin can control including to delete it." The team is working on a tracking feature to have controls added and to get a setting added to Teams live event settings in the Teams Admin Center.

**Comment by scanum** [comment]
@danieldhudson  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
