### ISSUE TITLE
Include MS Teams

### ISSUE THREAD

**Issue by ivanja81** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#4988]
Include that this access policy is also applicable for MS Teams on user level native federation. It's unclear now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59900927-5e5f-77a4-04be-e05a91330fca
* Version Independent ID: 1e4d6b87-f57c-fa45-1630-3c32b821d93c
* Content: [Manage external access (federation) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-external-access?source=docs)
* Content Source: [Teams/manage-external-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-external-access.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@officedocspr  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@ivanja81 thank you for reaching out. Please can you clarify what you are asking to have changed in the article so I can assist further.

**Comment by ivanja81** [comment]
Microsoft Teams needs to be added to applies to field.

**Comment by lindspea** [comment]
@ivanja81 Thank you, but I think this article covers that information already, or am I missing something? Which part of this article are you suggesting updating?

**Comment by ivanja81** [comment]
Set-CsExternalAccessPolicy
Module:
skype
Applies to:
**Lync Server 2010, Lync Server 2013, Skype for Business Online, Skype for Business Server 2015, Skype for Business Server 2019**

It's confusing for customer if they want to know if this also works on Teams.

**Comment by lindspea** [comment]
@ivanja81 thank you. Sorry for the confusion but the article in question where you opened the issue is "Manage external access (federation) - Microsoft Teams" and it already mentions that it applies to Microsoft Teams, so I'm a bit confused about what you're asking to have changed in this article and where?  Are you referring to this specific article or are you perhaps suggesting another article - this one - https://docs.microsoft.com/powershell/module/skype/set-csexternalaccesspolicy?view=skype-ps. If there is an issue in an article it's always best to open the issue under the relevant article in question. Thanks again for your help.

**Comment by ivanja81** [comment]
Ah yes, sorry aboutt hat. I just noticed that. Not sure.

**Comment by scanum** [comment]
@officedocspr  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
