### ISSUE TITLE
Limits for local Teams recording. 

### ISSUE THREAD

**Issue by Lewis-Barry** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5076]
Could there be some information added about the time limits for local Teams meeting recording? There is an MVP that says it gets cut off at 4 hours, but I can't find anything in MS docs to confirm this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams?source=docs)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **lolaj**

**Comment by scanum** [comment]
@Lewis-Barry Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@Lewis-Barry thank you for reaching out. Since recorded videos are stored in Microsoft Stream, the limit mentioned in the article is in terms of data eg. a Microsoft Stream tenant receives a fixed allocation of 500 GB of storage.  The size of a 1-hour recording is approximately 400 MB, but most users have found that the limit is somewhere around 4 hours. Please also see here https://techcommunity.microsoft.com/t5/microsoft-teams/what-is-the-time-limit-of-a-recording-during-a-meeting/m-p/1436310

**Comment by scanum** [comment]
@Lewis-Barry Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
