### ISSUE TITLE
Don't recommend mailbox deprovisioning to hide personal lists

### ISSUE THREAD

**Issue by owenmpls** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5142]
The following content proposes mailbox deprovisioning as a means to hide personal lists, which is impractical. This should be replaced with a statement that personal lists will be visible for any user licensed for Exchange Online, and we don't currently support hiding them.

"If you don't want users to see Personal lists, you can hide it. To do this, remove the user's Exchange Online license. Note that after you remove an Exchange Online license, the user no longer has access to their mailbox. Mailbox data is held for 30 days, after which the data will be removed and can't be recovered unless the mailbox is placed on In-Place Hold or Litigation Hold."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c4aab7-6115-ff27-5538-0a0bf73755de
* Version Independent ID: 3ff038fc-da4d-fdf4-7b5b-071bd25e3047
* Content: [Manage the Tasks app for your organization in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/manage-tasks-app)
* Content Source: [Teams/manage-tasks-app.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-tasks-app.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@owenmpls Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @owenmpls, thank you for your feedback and help us to improve docs.microsoft.com.

I´m suggesting an update to this article, if you can, please check it and let me know if you think there is something else to improve.

And if you have a Microsoft alias you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html.

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=owenmpls

**Comment by LanaChin** [comment]
Followed up with PM.

**Comment by LanaChin** [comment]
Hi @owenmpls - thanks for your feedback. The PM reviewed this and based on his feedback, we've updated the content in this section. While not recommended for information workers, this is technically a supported option.
