### ISSUE TITLE
Teams Only CAN communicate with Skype for Consumer

### ISSUE THREAD

**Issue by sijc** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5157]
I don't believe the statement "Users who are upgraded to Teams Only cannot communicate with users who are using Skype for Consumer." is true anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2fc46c-d6fb-fd8b-e2aa-fdee7c742230
* Version Independent ID: e0d36a99-2823-68a2-7e97-0c1ba66efd51
* Content: [Teams Only mode considerations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-only-mode-considerations)
* Content Source: [Teams/teams-only-mode-considerations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-only-mode-considerations.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@sijc Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by technonath** [comment]
sorry I duplicated this because you no longer display active comments at the bottom of the articles - This information is no longer true with the rollout of consumer skype.  I have raised this point with you before and you closed the previous case without verifying it.  There is one thing worse than no documentation and that is inaccurate documentation! Come on microsoft get your act together.

**Comment by technonath** [comment]
you have published my changes now removing the incorrect information this can be closed now.

**Comment by scanum** [comment]
@technonath Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
