### ISSUE TITLE
Default Install Location

### ISSUE THREAD

**Issue by pctec100** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5496]
The article says "The Teams MSI will place an installer in Program Files."  

The default location is 
C:\Program Files (x86)\Teams Installer
or
C:\Program Files\Teams Installer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@pctec100 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@pctec100 thank you for reaching out and helping improve MS Docs. Are you suggesting adding a note to the article showing the default?

**Comment by pctec100** [comment]
Yes, I recommend specifying the default location.
Since deploying Teams using the msi installer we have had several cases
where teams was not installed to a user's profile and we manually ran
teams.exe from the Teams Installer folder to correct the issue.  It would
have saved me a little time troubleshooting the issue had the default
folder location been specified within this article.

**Comment by bahnjee** [comment]
It appears that the Teams installer is copied to the x86 dir on both architectures.  I just downloaded the "Commercial" 64bit MSI from _https://docs.microsoft.com/en-us/MicrosoftTeams/msi-deployment_ and since I accepted the default file name (Teams_windows_x64.msi) I'm sure I got the right one.  When I installed it to a 64-bit PC,  the Teams installer file (Teams.exe) ended up in "C:\Program Files (x86)\Teams Installer" (along with a setup.json file)

I would suggest if the docs are going to specify the install location, you should perhaps do so in a table:

                                 32-bit PC                                    64-bit PC
32-bit installer      C:\Program Files                    C:\Program Files (x86)
64-bit installer      (not possible)                        C:\Program Files (x86)

I've not tested the 32-bit installer on a 64-bit PC (don't have one) but I think it's safe to assume it would go to the location I've indicated.  You may want to test...

**Comment by LanaChin** [comment]
Thanks for your feedback. We've updated the article to include the install locations and architecture.
