### ISSUE TITLE
Slovenia Calling plans

### ISSUE THREAD

**Issue by doggy-dog** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5546]
[Enter feedback here]
There are available Calling plans in Slovenia, please modify the article. (You can get phone numbers for Slovenia from the Teams Admin center)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87d92b59-7977-5cb0-07b3-ae61d6c6f427
* Version Independent ID: 6bfc8c8e-3ad8-1e98-a0bf-2221173c42ce
* Content: [Availability in Slovenia - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-slovenia?source=docs)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-slovenia.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/availability-in-slovenia.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@doggy-dog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tonysmit** [comment]
There are no subscriber (user) phone numbers available in Slovenia. However, there are phone numbers available for service numbers and toll free phone numbers. In the documentation, if there are all types of numbers (user, service and toll free) available for a specific country/region, then we say that Calling Plans are available. Calling plans are only supported currently in 10 countries/regions because they support user (subscriber) numbers.
