### ISSUE TITLE
Set up your network for Teams live events Points to Review Site

### ISSUE THREAD

**Issue by davidyack** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#559]
The Set up your network for Teams live events link points to a protected review.docs link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: becbf3ca-b88c-b033-a145-9a1af201ced3
* Version Independent ID: 41a6a9b5-d3dd-d8c9-9e97-920ff2fd1a24
* Content: [What are Teams live events?](https://docs.microsoft.com/en-us/microsoftteams/what-are-teams-live-events)
* Content Source: [Teams/what-are-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @tonysmith
* Microsoft Alias: **tonysmit**

**Comment by kenwith** [comment]
@davidyack - thanks for taking the time to post this catch. The review.docs.microsoft.com site pulls from the 'master' branch on GitHub and unfortunately is behind corp net. Which doesn't make a lot of sense for how we use GitHub since the 'master' branch is public on GitHub. The 'live' branch on GitHub is where the docs.microsoft.com site pulls from. We will get this fixed and pointed to the correct URL. Thanks again for taking the time to report!

**Comment by tonysmit** [comment]
It's been removed for now from the content. We will add the link back in once the content is completed. Thanks, Tony
