### ISSUE TITLE
Information around CEC is not complete on this page

### ISSUE THREAD

**Issue by ervinbms** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5644]
The details around CEC support are not clear on this page. If you check the same information under these two pages:

https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/rooms-operations
and
https://docs.microsoft.com/en-us/microsoftteams/rooms/requirements

There is a more complete statement: 

If you desire a front of room display to automatically switch to an active video source (such as an MTR console) when the source wakes from standby mode, certain conditions must be met. This feature is optional but supported by Microsoft Teams Rooms software, provided underlying hardware supports the feature. A consumer TV used as a front of room display needs to support the Consumer Electronics Control (CEC) feature of HDMI. Depending on the dock or console selected (which might not support CEC, refer to manufacturer support documentation), a controller such as an HD-RX-201-C-E from Crestron or Extron HD CTL 100 from Extron may be needed to enable the desired behavior.

This was pointed out by a customer who was looking to use CEC on MTR and by looking at the incomplete statement he understood that we support CEC on all MTRs. 

Thanks,
Ervin (ervinb@microsoft.com)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef5b5fd-5a4e-7957-f23c-724764a7cb4c
* Version Independent ID: 5fe6c3ab-774b-db2f-5b55-9170bdfe5faf
* Content: [Known issues - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/known-issues)
* Content Source: [Teams/rooms/known-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/known-issues.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
@ervinbms Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @ervinbms, thank you for your feedback and help us to improve docs.microsoft.com.

The only difference I see is marked in bold:

"If you desire a front of room display to automatically switch to an active video source (such as an MTR console) when the source wakes from standby mode, certain conditions must be met. This feature is optional but supported by Microsoft Teams Rooms software, provided underlying hardware supports the feature. A consumer TV used as a front of room display needs to support the Consumer Electronics Control (CEC) feature of HDMI.  Depending on the dock or console selected (which might not support CEC, refer to manufacturer support documentation), a **controller** such as an **HD-RX-201-C-E from Crestron or** Extron HD CTL 100 from Extron may be needed to enable the desired behavior. "

Current the article say workspace controller instead of only controller, and it adds the Creston controller.

The second article has this note:

"A consumer TV used as a front of room display needs to support/enable the Consumer Electronics Control (CEC) feature of HDMI so that it can switch automatically to an active video source from standby mode. This feature is not supported on all TVs."

A think this information is included now.

Please let me know if I misinterpreted it. Thanks!
