### ISSUE TITLE
3 recently released features missing

### ISSUE THREAD

**Issue by rdekramer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#5679]
The recently released call merge, safe transfer and multiple number dialing features are missing. Could these be added?

Thanks,
Remco

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cfead3c-b0d8-c22a-aa22-63e79fe53ed3
* Version Independent ID: 10745875-3d3e-42bb-e324-ff4c83968ccf
* Content: [Here's what you get with Phone System - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/here-s-what-you-get-with-phone-system)
* Content Source: [Teams/here-s-what-you-get-with-phone-system.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/here-s-what-you-get-with-phone-system.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@rdekramer Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@rdekramer Thank you for reaching out. 
@CarolynRowe Is this in the pipeline to be added to the article?

**Comment by tiburd** [comment]
@rdekramer - Hi,

This article now includes several updates that have been added since the time that you raised this issue. 

Can you please review [the updated article](https://docs.microsoft.com/MicrosoftTeams/here-s-what-you-get-with-phone-system), and then let us know whether the features you mentioned are now included? 

Please @ mention me in your reply.

Thank you!
