### ISSUE TITLE
Link in eDiscovery section is linked to wrong page

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6024]
In the eDiscovery section the para **We have a Teams-specific article for more information, eDiscovery of guest-to-guest chats**. is linked to the wrong page that does not refer to guest to guest chats. Can it be linked to the correct page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca579d63-182b-d6f5-8777-79248fa27ed9
* Version Independent ID: b4c27d1b-b2f1-41ac-b15c-d12b448a539e
* Content: [Overview of security and compliance - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/security-compliance-overview)
* Content Source: [Teams/security-compliance-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/security-compliance-overview.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@nikki-c  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@nikki-c thank you for reaching out. I'm busy investigating with the team. @dariomws please could you help with this issue. Similar to the one #1846 you were helping with. Does this still apply to guest to guest chats? - "At this time, we don't support eDiscovery of chat messages in scenarios where guest users are the only participants in a 1:1 or 1:N chat. These types of chats are also called guest-to-guest chats because they don't include home tenant users."

**Comment by dariomws** [comment]
@lindspea left a comment in the other issue. We need to confirm if this note should be there or not.

**Comment by scanum** [comment]
@nikki-c Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
