### ISSUE TITLE
Says "static tab"? Do you mean 'personal tab'?

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6123]
The article refers to a "static tab", which a noun used elsewhere in the platform docs. Tabs typically refer to things inside a Channel or Chat. Static also implies that the information can't change.

I'm pretty sure they mean "Personal Tab", as that is was the actual tab is called in App Studio
![image](https://user-images.githubusercontent.com/22797301/98009540-4645c700-1dbb-11eb-9943-0262c7acd066.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611ed1ac-09a9-3491-7fa8-d282b4558fbe
* Version Independent ID: b5a1dba5-beab-7188-fe18-0a045814dde0
* Content: [Create a Teams 'Intranet Portal app' from a SharePoint Online site or page - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/teams-standalone-static-tabs-using-spo-sites)
* Content Source: [Teams/teams-standalone-static-tabs-using-spo-sites.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-standalone-static-tabs-using-spo-sites.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **heidip**

**Comment by scanum** [comment]
@npherson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @npherson Nash, how are you?

I think in this case, the current term is valid, looking into the json example also in the article:


`    "staticTabs": [`  

And also, defined in the [schema file](https://developer.microsoft.com/en-us/json-schemas/teams/v1.7/MicrosoftTeams.schema.json)

> "A set of tabs that may be 'pinned' by default, without the user adding them manually. Static tabs declared in personal scope are always pinned to the app's personal experience. Static tabs do not currently support the 'teams' scope."

Thanks

**Comment by npherson** [comment]
But since the App Studio user interface calls that a 'personal tab', wouldn't it make sense to have the documentation for using AppStudio to publish a 'personal Tab' call it a 'personal tab' even if the JSON file uses a different tag?

**Comment by get-itips** [comment]
@LanaChin Lana, how are you? I'll let you to decide on this. Thanks

**Comment by get-itips** [comment]
@cichur Cindy, can you kindly help on this one? Thank you!

**Comment by lokimeyburg** [comment]
I agree that the documentation should say "personal tab" instead of "static tab". The `staticTab` array in the manifest is an implementation detail, but externally we generally want to refer to these as "personal tabs" instead. Since App Studio calls this section "personal tabs" it only further seems to me this is the way to go. If someone only uses App Studio to create their manifests (which this documentation recommends), then calling something a "static tab" is new and confusing to the reader of this documentation.

Also, I would probably remove the "Mobile support is currently in Developer Preview" caution blurb. I believe it works on mobile in production now.

**Comment by cichur** [comment]
Hi @lokimeyburg, I removed the Mobile support note from the article. - Cindy
