### ISSUE TITLE
Storage quota

### ISSUE THREAD

**Issue by michaelfjohn78** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6140]
There are conflicting statements in this post related to whether the tenant storage will be increased for this. In the benefits section it states "Increased quota" but in the FAQ section it states "Teams meeting recording files live in OneDrive for Business and SharePoint and are included in your quota for those services". Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/tmr-meeting-recording-change)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by haomoy-microsoft** [comment]
> There are conflicting statements in this post related to whether the tenant storage will be increased for this. In the benefits section it states "Increased quota" but in the FAQ section it states "Teams meeting recording files live in OneDrive for Business and SharePoint and are included in your quota for those services". Please clarify.

Thanks for the comment! You're right, the wording is not precise. To clarify:
If a recording is put into ODB, it's way more because customers get effectively "unbounded" storage. That's in quotes because there are technical limitations there. What we can say is that ODB provides much more storage and then provide a link to the page that talks about ODB storage. Then in terms of SPO, the correct thing to say is that the storage is more fungible.

We're gathering the information to change the doc, thanks again!

**Comment by cichur** [comment]
Hi @michaelfjohn
We've updated the article with the information. Thank you. Cindy
