### ISSUE TITLE
recommendeds 

### ISSUE THREAD

**Issue by TobieFysh** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#616]
Spellcheck please :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e342c08-c1d8-8c1d-944d-d6489a17c42b
* Version Independent ID: 5c9987d5-4c98-8115-55c8-f629dbd25799
* Content: [Plan Cloud Voicemail service](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/plan-cloud-voicemail#migration-and-interoperability)
* Content Source: [Skype/SfBServer2019/hybrid/plan-cloud-voicemail.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfBServer2019/hybrid/plan-cloud-voicemail.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by kenwith** [comment]
@TobieFysh - thanks for catching! Fixed with this Pull Request: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/618

By the way, these docs are open source now and if you would be interested you could also make changes and submit a Pull Request. You would show up as a contributor here: [https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/graphs/contributors](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/graphs/contributors). 


Thanks for taking the time to submit this catch. It is much appreciated!
