### ISSUE TITLE
Two different messages about the launch dates

### ISSUE THREAD

**Issue by Lightpeek** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6205]
Hello

I can see that on this page we have the following launch date:
![image](https://user-images.githubusercontent.com/43235569/99066299-0942b700-25a9-11eb-8904-e8314a8d4d34.png)

However, in M365 Message Center the following dates has been published (message MC222640):
![image](https://user-images.githubusercontent.com/43235569/99066525-68a0c700-25a9-11eb-961d-101c0d4af75c.png)

What are the correct dates? I guess one of these sources should be updated with correct information.

Kind regards
Roger Lysnes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8935e913-806f-a92c-d09e-e67df4ffd1b4
* Version Independent ID: c7a41cde-66dd-d7cd-1316-42d20ed4841a
* Content: [Use OneDrive for Business and SharePoint for meeting recordings - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/tmr-meeting-recording-change)
* Content Source: [Teams/tmr-meeting-recording-change.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/tmr-meeting-recording-change.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by cichur** [comment]
Hello @Lightpeek 
Thank you for your comments. I'll ask the SME to clarify. - Cindy

**Comment by dcombes** [comment]
Yes we had spotted this date difference too. It makes quite a difference to how we prepare for the change, so would appreciate clarification also. David.

**Comment by dariomws** [comment]
Hi @Lightpeek and @dcombes, thank you for your feedback.

Please check the message ID MC222640 on the Message Center section of your Microsoft 365 Admin Center, it was updated on November 17 and now you can see the following information:
- October 19, 2020 (Complete) – You can enable the Teams Meeting policy to have meeting recordings saved to OneDrive and SharePoint instead of Microsoft Stream (Classic)
- Rolling out starting January 11th, 2021 (Updated) – All new Teams meeting recordings will be saved to OneDrive and SharePoint unless you delay this change by modifying your organization’s Teams Meeting policies and explicitly setting them to “Stream”. Seeing the policy reporting as Stream is not enough. You need to explicitly set the policy value to “Stream”.
- Rolling out starting March 1st, 2021 to Enterprise Customers (Updated) – No new meeting recordings can be saved to Microsoft Stream (Classic); all customers will automatically have meeting recordings saved to OneDrive and SharePoint even if they’ve changed their Teams meeting policies to “Stream”. We recommend that customers roll this feature out before this date so that they can control the timing of the release.
- Rolling out starting July 7th, 2021 to Education Customers (Updated) – No new meeting recordings can be saved to Microsoft Stream (Classic); all customers will automatically have meeting recordings saved to OneDrive and SharePoint even if they’ve changed their Teams meeting policies to “Stream”. We recommend that customers roll this feature out before this date so that they can control the timing of the release. We have updated this schedule to provide education customers the ability to complete in progress semesters.

@cichur this information is not updated yet in the public roadmap:
https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=67138
Could we warn someone about this?

**Comment by cichur** [comment]
Hi @dariomws 
Yes, I'll let the PM know.
Thanks,
Cindy

**Comment by scanum** [comment]
@Lightpeek  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
