### ISSUE TITLE
We do not capture the Member Added for Group chat

### ISSUE THREAD

**Issue by dipinn26592** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6224]
Added members | MemberAdded | A team owner adds members to a team, channel, or group chat
-- | -- | --

MemberAdded does not capture the activity of a Group chat. If its true the meeting group chat details should also be visible. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e51e97-ff97-c5eb-6517-21ce9a563ca4
* Version Independent ID: d3dc21b2-d90a-fbe7-8473-fff0b55feafb
* Content: [Search the audit log for events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/audit-log-events)
* Content Source: [Teams/audit-log-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/audit-log-events.md)
* Service: **msteams**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@dipinn26592 This be by design, not to have the actual chat message or other details in the audit record on adding a participant to a chat. You might consider using an eDiscovery search tool to search for the chat. You could use details from the audit record (e.g. date, participant) and then use those in a search query to find the chat. Use the kind:microsoftteams property to specifically search for chats. For more info on searching: https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide#searchable-email-properties
