### ISSUE TITLE
Please add a note to explicitly indicate Import Mode in Power BI is not supported.

### ISSUE THREAD

**Issue by lukecarroll** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6254]
Please include a note at the top saying this:

The CQD Power BI Connector only supports DirectQuery in Power BI; Import mode is not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 067e8376-df94-9a44-5263-cd1fc84879bf
* Version Independent ID: 924240c8-52c5-42db-36b8-28751f838784
* Content: [Install Power BI Connector to use CQD query templates - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/cqd-power-bi-connector)
* Content Source: [Teams/CQD-Power-BI-connector.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/CQD-Power-BI-connector.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@lukecarroll  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @lukecarroll, thanks! I applied a pull request to add this note; it should be live in the next couple of days.

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=lukecarroll
