### ISSUE TITLE
Information about meeting expiration is unclear

### ISSUE THREAD

**Issue by JonasDewit** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6345]
The documentation states that regular Teams meetings 'expire' after 60 days (starting at the meeting start or end time). However, it is not clear what 'expire' means in this context. Does it mean that the meeting URL won't work anymore and the meeting cannot be launched? Does it mean the chat history will be removed?

When testing today (14th Dec) with a non-recurring meeting that was scheduled for 6th Jan 2020, it turns out that it is still possible to launch the meeting and the chat is still there. So it would seem nothing happened after the meeting was supposed to expire on the 6th of March.

Is it possible to clarify this ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@JonasDewit  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Emsabare** [comment]
feedback we received so far is that the actual meeting link will always be accessible. The only thing that actually expires is the meeting ID and each time someone clicks on the original meeting link it will create a new ad-hoc meeting with default meeting policies (no longer the ones of the initial organizer) and the new meeting will be inked to the old meeting link. 
Still in the process of understanding if/how chat can be removed from this new meeting.

**Comment by benjaminwchau** [comment]
The reason it works is because when you access an expired meeting with Teams, Teams service will spin up a new meeting, link the old URL/GUID to the next meeting. So the meeting will launch. Even better, other participants accessing the old URL, they will be redirected to the new meeting, so they can meet. But it will have problems:
1. Dial in conference ID will be difference, anyone trying to dial in using the old conference ID will fail. You will see a new conference ID on the meeting detail that is different from the original meeting invite.
2. CVI connect to this expired meeting will not work, as the CVI coordinate is still pointing to the original Teams Meeting GUID.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
