### ISSUE TITLE
What you describe is not actually there

### ISSUE THREAD

**Issue by devbenjamin** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6387]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/42345459/102784672-b52aaf80-436a-11eb-950a-b7c51c871672.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9902e8-a0b7-b6af-4656-2024849a5e8b
* Version Independent ID: 85beb9a7-2682-b52e-210b-20e598e3dab3
* Content: [Create your first teams and channels - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/get-started-with-teams-create-your-first-teams-and-channels)
* Content Source: [Teams/get-started-with-teams-create-your-first-teams-and-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/get-started-with-teams-create-your-first-teams-and-channels.md)
* Service: **msteams**
* GitHub Login: @LanaChin
* Microsoft Alias: **v-lanac**

**Comment by scanum** [comment]
Sales Rep/Business Development Manager for IT Consulting firm 

An enterprise client is looking for a Sales Rep/Business Development Manager for IT Consulting firm.

The client is looking for an experienced business development manager to assist with lead generation, educating prospects on products through calls, training, and presentations, and providing existing customers with exceptional support.

The freelancer will interact with the internal sales team for support.

20 hours a week to start

The client prefers if you've recently worked with an IT Services firm. Looking for somebody who has experience in hospitality, restaurant, convenience.


The freelancer will need to have experience in IT and excellent customer service skills.

Screening Questions -

- What is your your experience in IT?
- Do you have experience in the food and beverage industry?
- Are you located in the U.S?




Freelancers with Food and Beverage industry Experience 


An enterprise client is looking for a group of freelancers with experience in the food and beverage industry to form a focus group of Food & Beverage Coordinators at startups. The client is launching a software for cafeterias and restaurants. Therefore, the client is looking to form this focus groups in order to understand about the subject.

The client needs to understand from a customer point of view what the pinpoints are.

The main goal of the project is to gather as much information from the freelancers. As a chef, cashier, waiter… What is your experience?

The client is looking for several people who have worked in a cafeteria setting/coffee shop for companies under 1,000 employees for a focus group.

- Chefs, facility managers, counter service, food & beverage coordinators are people we will consider.

The client wants your feedback on how you create the menus, possible hazards to avoid, challenges, what works, etc.

The focus group will be three paid hours.

Please state your hourly rate and if you are available to start right away for a 3 hour project.

The client is looking for 10 people for this project?

Screening Questions - 

- What is your experience in the food and beverage industry?
- Are you able to participate in this project for 3 hours?
- What is your hourly rate?



Project Manager with CAD experience 


An enterprise client is looking for a professional and experienced Project Manager with experience in CAD design.  Someone with Civil Engineering or Construction experience to help monitor and coordinate a construction site for a store.

The client is looking for a freelancer who is able to understand and has experience building or participating in the build of a store site.


Technically this position is for someone to be a site coordinator in the construction of a store.  For the freelancer to be in charge of the project on the building site.

The project will consist of traveling to the building site for 10 days a month.


The client is looking for the following:
- 3-5 years of technical experience with everything from servers to CAD Design
- Experience with construction installations
- Light travel will be required for installations
- The freelancer will need to speak English fluently.

Screening Questions -


What is your experience in store building and being a project coordinator/site manager?

Are you able to travel 10 days a month?

Do you have all necessary paperwork to travel outside of the country?

Are you fluent in English and feel comfortable communicating in English with a team?
