### ISSUE TITLE
Presence for federated users in outlook desktop does not work

### ISSUE THREAD

**Issue by XixiHuang333** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6392]
Hi Team,
Customer reported Presence for federated users in outlook desktop does not work. It looks there is no statement for this in below docs.
https://docs.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations
After confirming with teams product engineering, this feature is not supported. Could you please kindly help to document this？
Please contact me via xixih@microsoft.com

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f080a5c-4268-1db4-566f-f1edc27920b5
* Version Independent ID: ac556a92-58af-3e05-f53b-0fc00afc96c0
* Content: [Call and chat with users from other organizations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/communicate-with-users-from-other-organizations)
* Content Source: [Teams/communicate-with-users-from-other-organizations.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/communicate-with-users-from-other-organizations.md)
* Service: **msteams**
* GitHub Login: @serdars
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@XixiHuang333  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @XixiHuang333, thank you for your feedback.

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=XixiHuang333

I tested it in the following version of Outlook, and it works, I can see presence for federated accounts:
![image](https://user-images.githubusercontent.com/33589238/104059208-b0238800-51d3-11eb-93b4-be901ce6e5ef.png)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
