### ISSUE TITLE
Add information about the max time allowed for recording a meeting

### ISSUE THREAD

**Issue by cadasi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6480]
I received this question from customers and internal resources at Microsoft a few times:
Can we add the max recording time for:
Teams Live Events
Teams normal meetings
Just to make it crisp: If a meeting goes on for 24 hours, are we going to record all the 24 hours? Or is there a hard limit where the recording will be interrupted before that?
Same thing for Live Events. Their time limit is usually for 4 hours, but with COVID we expanded their duration to (if I remember well) 16 hours. Are we going to record all of it or just 4 hour? I believe for Live Events we will always record all of it, but for normal meetings, as I exposed above, it is not super clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@cadasi thank you for reaching out. Since recorded videos are stored in Microsoft Stream, the limit mentioned in the article is in terms of data eg. a Microsoft Stream tenant receives a fixed allocation of 500 GB of storage. The size of a 1-hour recording is approximately 400 MB, but most users have found that the limit is somewhere around 4 hours. Please also see here https://techcommunity.microsoft.com/t5/microsoft-teams/what-is-the-time-limit-of-a-recording-during-a-meeting/m-p/1436310. Teams Meeting time limits are 24 hours.

**Comment by scanum** [comment]
@cadasi Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
