### ISSUE TITLE
Parameter Button

### ISSUE THREAD

**Issue by romainrocher** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6642]
Hi all,

since we had our Team Room system on the Active Directory, the button not working. The UAC don't prompt.

Have you an idea about this issue ?.

Thanks

**Comment by nam31** [comment]
Thank you for providing feedback. 
The issues section of this repository is intended for product documentation issues only.
Please consider opening a product support ticket by the following link below for your problem so that it gets resolved quickly.
[Skype for Business Support](https://support.microsoft.com/en-us/skype-for-business)
Thank you.
