### ISSUE TITLE
No mention of LLDP requirements

### ISSUE THREAD

**Issue by TorrenManson** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6807]
There's no mention in this article (or any other that we could find) of the requirement for the switch to have LLDP enabled for the switch chassis/switch port options to work. Can that be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 358dfc73-9414-13e2-4682-c3e82603692f
* Version Independent ID: 3faae1d9-efbe-c20c-6598-a5073c2306e2
* Content: [Configure dynamic emergency calling - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/configure-dynamic-emergency-calling)
* Content Source: [Teams/configure-dynamic-emergency-calling.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/configure-dynamic-emergency-calling.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by scanum** [comment]
@TorrenManson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@TorrenManson thank you for reaching out and helping improve MS Docs. Please let me know if this article helps at all - https://docs.microsoft.com/skypeforbusiness/plan-your-deployment/enterprise-voice-solution/network-location. I see this article has also been updated since your original post. Please let me know if I should add anything else to the article.
