### ISSUE TITLE
Machine Wide Installer MSI - getting notified.

### ISSUE THREAD

**Issue by bojkenoven** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6837]
Hi Microsoft,
I noticed that the machine-wide MSI has updated from version 1.3 to version 1.4, and that the machine-wide MSI 1.3 on existing computers forces users to update. 

Can you please add information to this article that allows us to be informed when:
 - This machine-wide MSI has a new version update.
 - Where we can alternatively be informed about a new MSI update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f71d9c-6b35-72c9-dd94-7f62319c1656
* Version Independent ID: 86172986-6cc8-eee5-1309-704d9de0dcd0
* Content: [Install Teams using Microsoft Endpoint Configuration Manager - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/msi-deployment)
* Content Source: [Teams/msi-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/msi-deployment.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@techangelsau thank you for reaching out. I see this article has been updated since you raised this issue. There is a section that reads - "Do not use the MSI to deploy updates, because the client will auto update when it detects a new version is available from the service. To re-deploy the latest installer use the process of redeploying MSI described below. If you deploy an older version of the MSI package, the client will auto-update (except in VDI environments) when possible for the user. If a very old version gets deployed, the MSI will trigger an app update before the user is able to use Teams." Does this help at all and is there anything else you could suggest to be added to the article?

**Comment by techangelsau** [comment]
Hi @lindspea ,
Thanks for coming back to me so quickly. 
The update is indeed helpful, but does need a little clarification. 
The MSI that can be downloaded was recently updated from version 1.3 to version 1.4. This is the MSI version that is installed into "%ProgramFiles(x86)%\Teams Installer". 

If a computer has the v1.3 MSI installed in the "%ProgramFiles(x86)%\Teams Installer" folder, it installs the old version of Microsoft Teams (v1.3) to the user's AppData folder. The user cannot use Teams until they complete an installation themselves to the v1.4 baseline update. 
[Here is a screenshot of the user experience. ](https://i.imgur.com/f7wczhB.png)

This would mean that the best way to get the MSI to install the later version (so that users would not need to upgrade), is to upgrade the MSI installation to the latest MSI, v1.4, and clear the AppData folder for all users. 

The article doesn't mention when the Teams standalone MSI installer gets updated, and I can't seem to find any version history that reflects when this is changed. It would be really great to even have a date or version of the MSI updated on the page, just as a reference for when it is updated to match a major version update. 
Let us know your thoughts. :)

**Comment by lindspea** [comment]
@cichur please could you assist here?

**Comment by lindspea** [comment]
@cichur please could you assist with this one?

**Comment by scanum** [comment]
Hi @HowlinWolf-92 ! Could you kindly help here? Thanks

**Comment by JoanneHendrickson** [comment]
@tiburd  @MikePlumleyMSFT @scanum This article has been updated with a note to have the user refer to the versioning history article to confirm they have the latest version.  The New Teams client will be releasing the bulk deployment feature in a few weeks, and will become the default app (using a different method).   Closing the issue as resolved.
