### ISSUE TITLE
Regional availability section seems to wrongly states that Stream services are available in Brazil GoLocal DC

### ISSUE THREAD

**Issue by JorgeALeitao** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#6983]
Regional availability section seems to wrongly states that Stream services are available in Brazil GoLocal DC

The section reads, 
"You can use Teams live events in multiple regions across the world. The following information shows availability for event team members and attendees.

 Important

The region for the event is automatically selected depending on the organizer and the Microsoft 365 tenant location.

Available in these regional data centers

North America
Central America
South America
Asia Pacific
Europe/Africa
Data location for these countries/regions (supported)

Australia
Brazil"

However internal Microsoft's documentation contradicts this,

This needs review/update to avoid misleading customers.

TIA!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events?source=docs#regional-availability)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
@JorgeALeitao Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @JorgeALeitao, thank you for your feedback.

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=JorgeALeitao

The article was updated 13 days ago to reflect what you are expressing:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/pull/6986
