### ISSUE TITLE
Individual attendees cannot be managed

### ISSUE THREAD

**Issue by danny030** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#705]
Para https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/conferencing/large-meetings#create-dedicated-moderators describes which functionality a moderator can use to manage a large meeting, that includes "Changing participant roles" and "Muting and unmuting the audience or individual users".

Both does not work when participants are attendees as they are not shown to the moderator/presenter. And therefore one is not able to mute/unmute an individual attendees or make an attendee a presenter while the meeting is in progress.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a732a9f2-97d2-5039-5101-0f7ac9ba9a36
* Version Independent ID: c78e377a-aed5-4f8a-fb22-c3c1565eae25
* Content: [Plan for large meetings in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/conferencing/large-meetings#create-dedicated-moderators)
* Content Source: [Skype/SfbServer/plan-your-deployment/conferencing/large-meetings.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/plan-your-deployment/conferencing/large-meetings.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

**Comment by AndreaBarr** [comment]
@danny030 Thank you for this feedback

I want to make sure that the moderator powers are correct for this so I am sending this to the Teams team so that we can get this updated appropriatly. 

I was able to get this into the backlog for the Teams team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.
