### ISSUE TITLE
Problems with CreateSrsMedia.ps1 script

### ISSUE THREAD

**Issue by florianhulst** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#707]
Seems there are some problems in the script, as it's expecting a language pack, but i'm not adding one...

**********************
Windows PowerShell transcript start
Start time: 20180828104512
Username: UZLEUVEN\fhulst0_a
RunAs User: UZLEUVEN\fhulst0_a
Configuration Name: 
Machine: UZLDT04682 (Microsoft Windows NT 10.0.16299.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 11428
PSVersion: 5.1.16299.547
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.16299.547
BuildVersion: 10.0.16299.547
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\fhulst0_a\Documents\PowerShell_transcript.UZLDT04682.N8fCwOfW.20180828104512.txt
Script version 1.3.2
Downloading CreateSrsMedia...
done
Validating signature for update.ps1...
success.

What type of customer are you?
Please make sure you have all of the following available:

1. A FAT32-formatted USB drive.
   The contents of this drive WILL BE LOST!
2. Windows 10 Enterprise media that matches your SRSv2 deployment kit.
   Enterprise customers can access Windows 10 Enterprise media from the Volume Licensing Service Center:
   http://www.microsoft.com/licensing/servicecenter
3. Any language pack (LP and/or LIP) files to be included.
   MPSA customers:         http://go.microsoft.com/fwlink/?LinkId=125893
   Other volume licensees: http://www.microsoft.com/licensing/servicecenter

Please do not continue until you have all these items in order.

Found deployment kit already downloaded.
Validating signature for SRSDeploymentKit-3.1.115.0.msi...
success.
Extracting the deployment kit...
done.
This deployment kit is built for Windows build 10.0.16299.15.
This deployment kit draws its drivers from %configsetroot%\AutoUnattend_Files\DistShare\Out-of-Box Drivers.

Please indicate what drivers you wish to use with this installation.
[ 0] Logitech SmartDock
[ 1] Crestron SR
[ 2] Polycom MSR
[ 3] Lenovo Hub 500
[ 4] None
Selected option 0.
[ 0] Surface Pro 4
[ 1] Surface Pro (2017)
Selected option 0.
Found driver already downloaded.
Validating signature for SurfacePro4_Win10_16299_1801701_1.msi...
success.
Extracting SurfacePro4_Win10_16299_1801701_1.msi...
done.
Found update kb4056892 already downloaded.
Validating signature for windows10.0-kb4056892-x64_a41a378cf9ae609152b505c40e691ca1228e28ea.msu...
success.
**********************
Windows PowerShell transcript end
End time: 20180828104556
**********************

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51d42140-9f7b-a6f3-7a3e-76cc7331cf22
* Version Independent ID: a7dacc56-c2df-55fb-76a3-ecb194564fae
* Content: [Configure a Skype Room Systems v2 console](https://docs.microsoft.com/en-us/skypeforbusiness/deploy/deploy-clients/console)
* Content Source: [Skype/SfbServer/deploy/deploy-clients/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/deploy/deploy-clients/console.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @Travis-Snoozy
* Microsoft Alias: **jambirk**

**Comment by Travis-Snoozy** [comment]
Language packs are not in any way mandatory. The script will make you very, very aware that you're not using language packs, but you simply need to answer the prompts appropriately to indicate that you really, really do want to make an image with no language pack.

**Comment by florianhulst** [comment]
Travis, Thanks for the response, but as you can see, he's not really asking me anything about language packs...
Last question i have to answer is which device i will be using (surface pro 4).
Any idea?

**Comment by Travis-Snoozy** [comment]
Here's a transcript from a run I performed just now -- same script version, same options selected -- showing the prompt you should receive (I answered "no" to make the script end -- you'd want to answer "yes" to the question):

**********************
Windows PowerShell transcript start
Start time: 20180828074425
Username: REDMOND\v-trsnoo
RunAs User: REDMOND\v-trsnoo
Configuration Name: 
Machine: SNOOZY-DESKTOP (Microsoft Windows NT 10.0.17134.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Process ID: 7316
PSVersion: 5.1.17134.228
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.17134.228
BuildVersion: 10.0.17134.228
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\v-trsnoo\Documents\PowerShell_transcript.SNOOZY-DESKTOP.EomlDljC.20180828074425.txt
Script version 1.3.2
Downloading CreateSrsMedia...
done
Validating signature for update.ps1...
success.

What type of customer are you?
Please make sure you have all of the following available:

1. A FAT32-formatted USB drive.
   The contents of this drive WILL BE LOST!
2. Windows 10 Enterprise media that matches your SRSv2 deployment kit.
   Enterprise customers can access Windows 10 Enterprise media from the Volume Licensing Service Center:
   http://www.microsoft.com/licensing/servicecenter
3. Any language pack (LP and/or LIP) files to be included.
   MPSA customers:         http://go.microsoft.com/fwlink/?LinkId=125893
   Other volume licensees: http://www.microsoft.com/licensing/servicecenter

Please do not continue until you have all these items in order.

Found deployment kit already downloaded.
Validating signature for SRSDeploymentKit-3.1.115.0.msi...
success.
Extracting the deployment kit...
done.
This deployment kit is built for Windows build 10.0.16299.15.
This deployment kit draws its drivers from %configsetroot%\AutoUnattend_Files\DistShare\Out-of-Box Drivers.

Please indicate what drivers you wish to use with this installation.
[ 0] Logitech SmartDock
[ 1] Crestron SR
[ 2] Polycom MSR
[ 3] Lenovo Hub 500
[ 4] None
Selected option 0.
[ 0] Surface Pro 4
[ 1] Surface Pro (2017)
Selected option 0.
Found driver already downloaded.
Validating signature for SurfacePro4_Win10_16299_1801701_1.msi...
success.
Extracting SurfacePro4_Win10_16299_1801701_1.msi...
done.
Identifying language packs...
... done identifying language packs.
Found update kb4056892 already downloaded.
Validating signature for windows10.0-kb4056892-x64_a41a378cf9ae609152b505c40e691ca1228e28ea.msu...
success.
WARNING: THIS IS YOUR ONLY CHANCE TO PRE-INSTALL LANGUAGE PACKS.
Because you are pre-installing an update, you will NOT be able to pre-install language packs to the image at a later point.
You are currently building an image with NO pre-installed language packs.
Are you ABSOLUTELY SURE this is what you intended?
Please place the LP and LIP cab files you wish to use in this directory, and run the script again.

You can download language packs from the following locations:
   MPSA customers:         http://go.microsoft.com/fwlink/?LinkId=125893
   Other volume licensees: http://www.microsoft.com/licensing/servicecenter
**********************
Windows PowerShell transcript end
End time: 20180828074553
**********************

**Comment by Travis-Snoozy** [comment]
I mean, I would need to know why the script exited. I don't see any error output or exception messages from your transcript -- the output just stops, with no indication why, and I run this script many, many, many, _many_ times a day.

The only obvious difference I'm seeing so far is that I'm on the latest Windows, and you're on the previous build. That really shouldn't make a difference, but I'll try running the script on the previous build and see if I can repro the problem you're having.

**Comment by Travis-Snoozy** [comment]
@florianhulst -- your transcript suggests that your script has been modified. Searching for language packs is supposed to occur before downloading/validating the KB. From my transcript:

    Extracting SurfacePro4_Win10_16299_1801701_1.msi...
    done.
    Identifying language packs...
    ... done identifying language packs.
    Found update kb4056892 already downloaded.

But from your transcript:

    Extracting SurfacePro4_Win10_16299_1801701_1.msi...
    done.
    Found update kb4056892 already downloaded.

Furthermore, I was not able to repro the problem even on an earlier Windows build (you'll note that this transcript, too, extracts drivers, then checks for language packs, then downloads the KB):

**********************
Windows PowerShell transcript start
Start time: 20180828075546
Username: DESKTOP-KLGDBB7\Admin
RunAs User: DESKTOP-KLGDBB7\Admin
Configuration Name: 
Machine: DESKTOP-KLGDBB7 (Microsoft Windows NT 10.0.16299.0)
Host Application: powershell -executionpolicy unrestricted .\CreateSrsMedia.ps1
Process ID: 8400
PSVersion: 5.1.16299.98
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.16299.98
BuildVersion: 10.0.16299.98
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\Admin\Documents\PowerShell_transcript.DESKTOP-KLGDBB7._AJHim3r.20180828075546.txt
Script version 1.3.2
Downloading CreateSrsMedia...
done
Validating signature for update.ps1...
success.

What type of customer are you?
Please make sure you have all of the following available:

1. A FAT32-formatted USB drive.
   The contents of this drive WILL BE LOST!
2. Windows 10 Enterprise media that matches your SRSv2 deployment kit.
   Enterprise customers can access Windows 10 Enterprise media from the Volume Licensing Service Center:
   http://www.microsoft.com/licensing/servicecenter
3. Any language pack (LP and/or LIP) files to be included.
   MPSA customers:         http://go.microsoft.com/fwlink/?LinkId=125893
   Other volume licensees: http://www.microsoft.com/licensing/servicecenter

Please do not continue until you have all these items in order.

Downloading deployment kit...
done
Validating signature for SRSDeploymentKit-3.1.115.0.msi...
success.
Extracting the deployment kit...
done.
This deployment kit is built for Windows build 10.0.16299.15.
This deployment kit draws its drivers from %configsetroot%\AutoUnattend_Files\DistShare\Out-of-Box Drivers.

Please indicate what drivers you wish to use with this installation.
[ 0] Logitech SmartDock
[ 1] Crestron SR
[ 2] Polycom MSR
[ 3] Lenovo Hub 500
[ 4] None
Selected option 0.
[ 0] Surface Pro 4
[ 1] Surface Pro (2017)
Selected option 0.
Downloading driver...
done
Validating signature for SurfacePro4_Win10_16299_1801701_1.msi...
success.
Extracting SurfacePro4_Win10_16299_1801701_1.msi...
done.
Identifying language packs...
... done identifying language packs.
Downloading update kb4056892...
done
Validating signature for windows10.0-kb4056892-x64_a41a378cf9ae609152b505c40e691ca1228e28ea.msu...
success.
WARNING: THIS IS YOUR ONLY CHANCE TO PRE-INSTALL LANGUAGE PACKS.
Because you are pre-installing an update, you will NOT be able to pre-install language packs to the image at a later point.
You are currently building an image with NO pre-installed language packs.
Are you ABSOLUTELY SURE this is what you intended?
Please place the LP and LIP cab files you wish to use in this directory, and run the script again.

You can download language packs from the following locations:
   MPSA customers:         http://go.microsoft.com/fwlink/?LinkId=125893
   Other volume licensees: http://www.microsoft.com/licensing/servicecenter
**********************
Windows PowerShell transcript end
End time: 20180828080250
**********************


Could you please delete your current copy of the script, download the script from https://go.microsoft.com/fwlink/?linkid=867842 and confirm whether the issue still repros?

**Comment by florianhulst** [comment]
Downloaded the script again, now it seems to be working, sorry for your trouble!
