### ISSUE TITLE
Teams messages in private channels are currently not supported for retention policies

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7146]
Can you add a note highlighted in purple that states  the following limitation

Teams messages in private channels are currently not supported for retention policies. Code snippets, recorded voice memos from the Teams mobile client, thumbnails, announcement images, and reactions from others in the form of emoticons are not retained when you use retention policies for Teams. Cross reference to https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-teams?view=o365-worldwide for more information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55c52a5-5841-b9c9-1607-2013dc3f2e20
* Version Independent ID: 16d93458-5e01-646f-dac5-31306cc7f3fb
* Content: [Manage retention policies for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/retention-policies)
* Content Source: [Teams/retention-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/retention-policies.md)
* Service: **msteams**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@nikki-c  Thanks for your suggestion. However, when we have detailed technical information that's likely to change (and all these qualify), we aim to publish them in a one place so customers have a single authoritative source of information. Although duplicating technical details starts out with the best of intentions, what inevitably happens when things change is that one version gets updated and others don't, and support statements get out of sync. In fact, this is exactly what has happened with this page in the past. Going forward, technical details like this will be in the article that you found and which we reference on this page in a couple of places.  For example:

For detailed information about how these policies work depending on your policy configuration and user actions, and what message data is included and excluded for Teams retention policies, see [Learn about retention for Microsoft Teams]( https://docs.microsoft.com/microsoft-365/compliance/retention-policies-teams). 

We did make an exception for the private channels limitations, and added this to the configuration instructions so it's included in context (https://docs.microsoft.com/microsoft-365/compliance/create-retention-policies#retention-policy-for-teams-locations ): "For Teams channel messages, message from standard channels but not private channels are included. Currently, private channels aren't supported by retention policies."
