### ISSUE TITLE
When Method1 is used, It's unclear what to do

### ISSUE THREAD

**Issue by yuokochi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7249]
The "Importamt" at the URL below states that in the case of Method 1, you should not follow the steps in this article to remove the server.

https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/decommission-remove-on-prem
Excerpt: If you are using Method 1, do not use the steps described in this article to remove your Skype for Business servers.

As an alternative, there is only a simple description of "you can re-image the servers", and no specific procedure is described.
I'm thinking that I should leave the domain of SfB Server and remove SfB Server, please clearly state how to delete it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 809826d2-e82d-0b31-0c8b-c475db0efbb8
* Version Independent ID: b4e15a5f-8096-21db-c120-63e99d601328
* Content: [Decommission Skype for Business Server - Skype for Business Hybrid](https://docs.microsoft.com/en-us/skypeforbusiness/hybrid/decommission-remove-on-prem)
* Content Source: [Skype/SfbHybrid/hybrid/decommission-remove-on-prem.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/decommission-remove-on-prem.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by get-itips** [comment]
Hello @yuokochi how are you? Hope you are doing good. 👍 

That statement exists because method 1 is _Manage sip addresses and phone numbers for users in Active Directory_ to be able to manage those attributes, they must exist in the Schema, and Method 2, steps 5 and 6 undoes the Skype for Business Server Active Directory Domain forest-level and domain-changes, (the attributes). 
What I think re-image here means is to leave everything as-is and reuse the (maybe physical?) servers, so you do not remove the necessary attributes if method 1 is the chosen one.

@dariomws do you think the same as me? Thanks

**Comment by yuokochi** [comment]
Hi, @get-itips 

Thanks for your response!
I also think that is the content.

However, it seems unclear to the readers of this article, so I think it will be easier to understand if you add the contentsto the document.

**Comment by dariomws** [comment]
@get-itips I understand the steps should be the same except for 5 (Disable-CsAdDomain) and 6 (Disable-CsAdForest).

**Comment by scanum** [comment]
@yuokochi Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
