### ISSUE TITLE
Cannot enable guest access at the tenant level!

### ISSUE THREAD

**Issue by spalmstr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#737]
Turn Microsoft Teams on or off is now greyed out!  So, Guest Access in Teams falls at the first hurdle!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f737e278-7c89-e048-b60b-287615a829fb
* Version Independent ID: 1df35258-7360-74c4-680a-e154c54291fe
* Content: [Microsoft Teams Guest Access checklist](https://docs.microsoft.com/en-gb/microsoftteams/guest-access-checklist)
* Content Source: [Teams/guest-access-checklist.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/guest-access-checklist.md)
* Service: **msteams**
* GitHub Login: @romanma
* Microsoft Alias: **romanma**

**Comment by jackc00** [comment]
I am having the exact same issue as d-tothe-j described. I have fiddled around different settings for the entire day and could not get it working. Please fix the problem. Thank you~

**Comment by d-tothe-j** [comment]
I spent an hour and a half with O365 support last night. They walked me through all the AAD, SharePoint Online, OneDrive, O365 Groups, Teams sharing settings on our production and my lab tenant. All are set properly other than the ability to enable the greyed out Guest access. After about an hour, they mentioned that this option should be deprecated and not needed, but they were unable to explain why adding guests is not working. They wanted the issue to be that I had made a change that would take up to 24 hours to replicate, but I have not made any changes. Sharing has been enabled for months.

They ended the call with running the mythical 'health check that can take 4-6 hours to complete, so I'll need to call you back tomorrow method', which was fine since I was tired anyway.

My assumption is that the feature was deprecated with the ability to add Guests turned off and no GUI method for turning it back on. Hoping their is an undocumented or at least non-public method of enabling guest access via powershell. 

I'll post any resolution I find. Hopefully the creators of the instructions have time to update the steps.

**Comment by jackc00** [comment]
@d-tothe-j Thanks for taking the time to share the troubleshooting experience. I would love to hear the follow-up and hopefully they have a solution for all of us :)

**Comment by d-tothe-j** [comment]
Well...we made the Powershell change explained in the link below, and no luck 2 hours later. Then, we ended up back on a Microsoft support call, happened to check the Services & add-ins Microsoft Teams page, and bam! The option to turn Teams on for Guests was no longer greyed out, and there was no longer a notice about the add-in being deprecated.

I thought that maybe the Powershell change had unlocked the setting, but I have access to 3 other tenants where AllowGuestUser was still set to False, and they are all no longer showing the add-in option to be greyed out. This appears more likely to be a service update made by Microsoft.

Either way, we're now able to add Guests. @NebularCloud , the assistance was much appreciated!

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/739

![image](https://user-images.githubusercontent.com/43017709/45242589-4074f980-b2b6-11e8-9e4e-9eb195805f47.png)

**Comment by Mike-Crowley** [comment]
@d-tothe-j I found the option wasn't greyed out, but the toggle button wouldn't move in edge or firefox, but did in Chrome. Might be some javascript involved as well - try another browser if you hit this issue again.

**Comment by AndreaBarr** [comment]
Closing resolved again.

**Comment by conceicao-christophe** [comment]
Hi, I'm trying to configure the Guest Access feature in Microsoft Teams based on this article: https://docs.microsoft.com/en-us/MicrosoftTeams/guest-access-checklist, but when I got to Step 3, accessing to Teams & Skype for Business Admin Center and configuring the Guest access settings, the page turns blank or I've this message... Can anyone help me with this?!

Thanks in advance,

![image](https://user-images.githubusercontent.com/24508335/49435098-11d3c580-f7b6-11e8-9c60-0481ae394d59.png)
