### ISSUE TITLE
Ability to Turn on Guest user/license type greyed out

### ISSUE THREAD

**Issue by d-tothe-j** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#738]
The article mentions "After the Guest user/license type is turned on". However, the ability to turn on Guest user/license type for Teams is greyed out and shows to be deprecated. This is the only setting I am unable to configure when following these instructions, and I am unable to get the ability to add Guest users in Teams to work.

Please assist. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f1d577c-1360-c2c1-a850-9ac6a941ec2f
* Version Independent ID: 346e43d4-22e0-2800-b80d-9fbdac324f75
* Content: [Manage guest access in Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/manage-guests)
* Content Source: [Teams/manage-guests.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/manage-guests.md)
* Service: **msteams**
* GitHub Login: @LolaJacobsen
* Microsoft Alias: **rramesan**

**Comment by AndreaBarr** [comment]
@ Thank you for submitting this Feedback.

From my understanding this is a duplicate issue from you and the issue of not being able to add guests to teams has been resolved. The duplicate issue is https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/739#issue-357492670 If the issue is not resolved please re-open this issue.
