### ISSUE TITLE
Add statement on various Teams clients' support for providing QoE data

### ISSUE THREAD

**Issue by dwhitney7** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7458]
Many of the specific dimensions and measure mention that they may be missing due to "Data was not reported". The best scenario as an improvement to this page would be if we could document specifically which QoE data is not expected to be reported by a given Teams client across desktop OSes, browser, iOS/Android phones, VDI, Teams phones, and 3rd-party phones.

Understanding that that is a tall ask, can we at least give a statement generally describing what kind of metrics we can expect across these clients? For example, web browsers cannot report on some OS-level metrics, and iOS/Android cannot report on wireless connection details.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a455280-ea8e-2ddf-2965-60d9dcc0e21d
* Version Independent ID: 7fb320d3-fa69-23fa-113c-53e9d2e11ada
* Content: [Dimensions and measurements - Call Quality Dashboard (CQD) - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/dimensions-and-measures-available-in-call-quality-dashboard)
* Content Source: [Teams/dimensions-and-measures-available-in-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dimensions-and-measures-available-in-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @dwhitney7, thank you for your feedback.

I can see that you're a Fastrack engineer. If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=dwhitney7

I don't have the information that you're requesting to add to the article. If you can kindly help me get that information, I can add it to the article, or you can do it by yourself by creating a Pull Request.

Please let me know how you want to proceed. Thanks!

**Comment by dariomws** [comment]
@scanum Could you kindly close it? Thanks!
