### ISSUE TITLE
CreateSrsMedia.ps1 Prompting for Windows Version that isn't available

### ISSUE THREAD

**Issue by bouchardrt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7495]
I'm going through the script and when I get to the step for providing the windows install media its prompting me for a version that isn't available for download.  the script keeps prompting me for 10.0.19041.631, (windows build 2004), but the only 2 versions I can download out of VLSC are .264 and .1052.

**Comment by RAJU2529** [comment]
@bouchardrt  Which article are you referring to

**Comment by bouchardrt** [comment]
Configure a Microsoft Teams Rooms console - Microsoft Teams | Microsoft Docs<https://docs.microsoft.com/en-us/microsoftteams/rooms/console>




Bouchard, Rich
Vice President
B. F. Saul Company & Affiliates

**Comment by RAJU2529** [comment]
I checked windows version is available.

**Comment by bouchardrt** [comment]
What version ate you saying is available? The script is promoting for .631, and that one isn't available in VLSC. Only a 200 one and a 1000 one (don't have the specific numbers on hand).


Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by KristoferOlafsson** [comment]
I feel like this was an issue like 2 years ago, i forgot what the fix was. I'm actually having the issue now also with the two versions of 2004 i have available.  
"
Your Windows installation media is version 10.0.19041.928. Your SRSv2 kit requires version 10.0.19041.631.
Your Windows installation media is version 10.0.19041.388. Your SRSv2 kit requires version 10.0.19041.631
"
These are the versions of windows I can choose from on my VLSC:
Windows 10, version 1909 (released Nov 2019) 64-bit English
Windows 10, version 2004 (released May 2020) 64-bit English
Windows 10, version 20H2 (updated Nov 2020) 64-bit English
Windows 10, version 21H1 (released May 2021) 64-bit English
Windows 10, version 21H1 (updated June 2021) 64-bit English
Windows 10, version 2004 (updated June 2021) 64-bit English
Windows 10, version 20H2 (updated June 2021) 64-bit English
Windows 10, version 1909 (updated June 2021) 64-bit English
According to the Build releases, it looks like the script wants the 2020-11-19 build KB 4594440. 
https://docs.microsoft.com/en-us/windows/release-health/release-information

**Comment by KristoferOlafsson** [comment]
I changed line 248 and it seemed to work. 
if ($img.Version -ne $KitOsRequired) {  
to
if ([version]$img.Version -lt [version]$KitOsRequired){

**Comment by hkystar35** [comment]
Updating for those still running into issues:

We have an open case with Premier Support on this and they've determined the root cause is that the Surface driver URLs in the SRS Deployment Kit are broken and will take **6 weeks** to restore.

You can verify this by opening the extracted SRS Deployment Kit to `SRSv2\Skype Room System Deployment Kit\$oem$\$1\Rigel\x64\Scripts\Provisioning` and opening `config.json`

Find your Surface driver URL listed, in my case it's the Surface Pro (2017):
```json
"Surface Pro 4":{
    "Action":"Download",
    "Targets":["https://download.microsoft.com/download/6/A/C/6ACB37C4-E4C1-4E0E-BBAE-AC7A0C303593/SurfacePro4_Win10_18362_21.040.1168.0.msi"]
},
```

Then try to use that URL in a browser to download the file, or use your favorite curl/webrequest command, and you'll get a big **_404 - File or directory not found_** error

Same now happens with https://go.microsoft.com/fwlink/?linkid=867842, which redirects to https://download.microsoft.com/download/9/0/D/90D4826A-9FD2-47D2-B911-97BF1737F4F7/CreateSrsMedia.ps1 and is 404, too. I'm hoping this is one is related to our support ticket and that MS engineers have taken down the link until it can be fixed.

**Comment by hkystar35** [comment]
Update again:

The SRS Deployment Kit has been updated to 4.9.12.1. For us, this fixed the issue.

I did a file and folder compare and all that was updated were 2 config.json files with new links

```
.\SRSv2\Skype Room System Deployment Kit\Provisioning\20H2\config.json
.\SRSv2\Skype Room System Deployment Kit\$oem$\$1\Rigel\x64\Scripts\Provisioning\config.json
```

and the content was updated:

![image](https://user-images.githubusercontent.com/32749858/130253594-2dd9db58-4a2b-47b5-bfcb-d9b90f4895ab.png)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
