### ISSUE TITLE
What is a template?

### ISSUE THREAD

**Issue by MiyukiAmino** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7509]
---
Approvals that are created from a template still store data in CDS, such as their title, details, template ID, and more. Responses that are submitted on the approval request are stored in Forms. Learn more about  Data storage for Microsoft Forms.
---

What is a template? Like this ; https://techcommunity.microsoft.com/t5/microsoft-forms-blog/microsoft-forms-powers-approvals-templates-in-microsoft-teams/ba-p/2262158 ?

The cx wants to know more specific information, not concepts, so please describe in which case approvals stored in CDS and not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 055b01ff-ee6c-7d5a-74bd-0e8eed7ee6b5
* Version Independent ID: 13c4174f-2a2a-2ef9-14c5-2f10817cc66a
* Content: [Approvals application availability in Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/approval-admin#storage-with-cds)
* Content Source: [Teams/approval-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/approval-admin.md)
* Service: **msteams**
* GitHub Login: @cichur
* Microsoft Alias: **v-cichur**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @MiyukiAmino, thank you for your feedback and help us to improve docs.microsoft.com.

A template is a pre-created approval that already has some formatting. Rather than starting from scratch to create an approval, you can use the formatting of a template.
The tech community article you shared includes information about how the approval templates work. It doesn't specify what a template is because I understand it's a standard concept.

The "Approvals application availability in Teams" includes some more information about where the approvals templates are store:
"The approval templates are stored in Substrate Data Storage (SDS), which is a compliant storage platform used internally only inside Microsoft. The organization-scoped templates are stored in “tenant shard” of SDS, and team-scoped templates are stored in “group shards” of SDS. This means that the org-scoped templates share the same lifetime of the tenant and team-scoped templates share the same lifetime of the team. So, permanently deleting the team deletes the related templates."

**Comment by MiyukiAmino** [comment]
Thank you for taking time to this issue! I can understand what are templates and where are they stored.
But... my essential question is where is approval data stored. Because cx wants to delete approval data manually. 

Docs says , "Approvals that are created from a template still store data in CDS".
 Q1. so since the word "still" is used, is there any case where they are stored outside of Dataverse?If no, every approval data created by template is in Dataverse? Where are approval data that are not created by template stored?
 Q2. What does it mean to be stored in Froms? How do we delete approval data in Forms?

Best Regards.

**Comment by dariomws** [comment]
Thank you for your new comment @MiyukiAmino.

Q1: Approvals created from the Approvals app will be stored in the default CDS environment.

Q2: Responses that are submitted on the approval request are stored in Forms. Learn more about  [Data storage for Microsoft Forms](https://support.microsoft.com/office/data-storage-for-microsoft-forms-97a34e2e-98e1-4dc2-b6b4-7a8444cb1dc3?ui=en-US&rs=en-US&ad=US#:%7E:text=Where%20data%20is%20stored%20for%20Microsoft%20Forms.%20Microsoft,European-based%20tenants%20is%20stored%20on%20servers%20in%20Europe).

Unfortunately, I have no more information at this time.

**Comment by MiyukiAmino** [comment]
Thanks. I understand. If I need more information, I create IcM.
Appreciate your kind response during your busy time.
