### ISSUE TITLE
Article not valid anymore

### ISSUE THREAD

**Issue by jbromelow** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#752]
In legacy SfB Admin portal, is a link for 'change language', but doesn't do anything.
In new portal there seems to be no such option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 506c5e71-cdf1-b3f0-a215-c7709a47bd3a
* Version Independent ID: 0d6918ee-05ec-45cd-c5f0-ea90d1810410
* Content: [Set auto attendant languages for Audio Conferencing in Skype for Business Online](https://docs.microsoft.com/en-us/skypeforbusiness/audio-conferencing-in-office-365/set-auto-attendant-languages-for-audio-conferencing)
* Content Source: [Skype/SfbOnline/audio-conferencing-in-office-365/set-auto-attendant-languages-for-audio-conferencing.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbOnline/audio-conferencing-in-office-365/set-auto-attendant-languages-for-audio-conferencing.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@jbromelow Thank you for this feedback

We apricate you pointing this link issue out to us. I am making sure this gets over to the Teams team so that we can get this addressed properly. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @jbromelow, I am working on it.

**Comment by chuckedmonson** [comment]
@roykuntz -- Can you please reply to this inquiry or direct to someone who can help? Thank you.

**Comment by chuckedmonson** [comment]
@ruizoscar - Can you please reply to this inquiry? Thank you.

**Comment by ruizoscar** [comment]
On the legacy portal:
•	The legacy portal is working fine. The “Set languages” link is disabled when a “Shared” number is selected because it isn’t possible to change the language of a shared number (The tooltip of the disabled link outlines that). If a “Dedicated” number is selected, the languages can be changed. There is a note in the article that outlines that languages can only be changed for "domestic" numbers, that note used to outline that languages could only be changed for “Dedicated” numbers, but someone changed it and the the new note doesn’t make sense at all.

•	I’ll submit the doc. changes to correct the note.

On the new portal: 
•	The control to “Set languages” isn’t there, I’ll need to follow up with the team that owns the portal for them to look into it, but it would be something that won’t be fixed soon.

Conclusion:
•	The article still applies, it is just that it needs some changes.
