### ISSUE TITLE
Why are there no models names in the list, only hardware IDs?

### ISSUE THREAD

**Issue by mm2knet** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7699]
Why are there no models names in the list, only hardware IDs?

It is easier for end users to search for models names instead of hardware IDs when new purchases are made.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e7f4e46-0e6a-3d42-022d-b07fd17792b3
* Version Independent ID: 5217778e-130d-6bed-beb7-f3834331f8ed
* Content: [Hardware decoder and encoder driver recommendations - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/hardware-decoders-and-encoders)
* Content Source: [Teams/hardware-decoders-and-encoders.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/hardware-decoders-and-encoders.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tiburd** [comment]
The product team is aware of this request. They have determined that using device IDs is more convenient because there could be cases where different OEMs ship the same hardware with different drivers. Also, device IDs can be queried/filtered.

They are considering adding a model and device ID cross-reference article.

Closing this issue.
