### ISSUE TITLE
The exact version of the ISO is not described on the article

### ISSUE THREAD

**Issue by peferre** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7823]
[Enter feedback here]
To successfully complete the media creation process, the version must be a specific one: 
The SHA256 of that ISO file MUST BE ‘FE029F3D94FFC3550312BFAC48EAA01A87946A0792F8E34196A6252065E2C5FB’, corresponding to 'Windows 10 (business editions), version 20H2 (updated Nov 2020) (x64)'. 
To confirm that you have downloaded the correct ISO, you can simply run the cmdlet 'Get-FileHash -Path %FileLocation%FileName.iso' - Any other hash result will be rejected by if the script and will not work. 
The host machine used to create the media file must attend a minimal version, checked through the 'HostOSVersion'. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f8b204f-9650-d268-8566-7a75ba0a1b6a
* Version Independent ID: 9a963e63-6716-7522-8abe-c8a407d3a46d
* Content: [Configure a Microsoft Teams Rooms console - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/rooms/console)
* Content Source: [Teams/rooms/console.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/console.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by peferre** [comment]
Thanks Emanuela,

For reference, we have this actionable item from the product group: Incident-255275094 Details - IcM (microsofticm.com)<https://portal.microsofticm.com/imp/v3/incidents/details/255275094/home>
I've personally tested and confirm that the script will only accept the windows 10 (business)(English)(update Nov 2020)(x64) and, the size and SHA256 hash of the correct ISO are as follows:

> Size: 6,015,029,248 bytes
> SHA256: FE029F3D94FFC3550312BFAC48EAA01A87946A0792F8E34196A6252065E2C5FB

No other version can be used with this script, the host machine must be running 20h2 or later.
Incidentally, my last test was on a host machine with the preview build of Windows 11:
[Text  Description automatically generated]
Also worked out great!

Any questions you may have, let me know. I'm entirely available to share the results of the recurrent tests we have done.

Pedro Ferreira
Support Escalation Engineer, Teams & Skype for Business
Empowering, Helping, and Advising Customers

Customer Service & Support
+351 210 602 104/+315 962 093 330
***@***.******@***.***>

[Image result for microsoft logo]

**Comment by dariomws** [comment]
Hi @peferre, thank you for your feedback.

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=peferre

**Comment by dariomws** [comment]
@peferre, Could you kindly provide more detail about what we should add to the document? Or maybe an example.

Do you have approval from the product team?

The script has a function called Test-OsPath which verifies that the media "match the version number the SRSv2 deployment kit requires". I understand that it depends on the SRS Deployment Kit, so I think we cannot detail specific version/build/hash in the article because the SRS DK will have updates.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
