### ISSUE TITLE
conflicting statements in this page

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7855]
In the important info banner you give the hint that it is recommend to have Exchange Full Classic Hybrid configured for the Teams calendar integration, otherwise it wont work.

But in the "Requirements to create and view meetings for mailboxes hosted on-premises" area you write "OAuth authentication is configured preferably via the Exchange Hybrid Configuration Wizard running a full hybrid configuration (Classic or Modern). If you are not able to use the Hybrid Configuration Wizard, configure OAuth as described in Configure OAuth authentication between Exchange and Exchange Online organizations."

What is the correct statement for the current state of implementation in this case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact#requirements-to-create-and-view-meetings-for-mailboxes-hosted-on-premises)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by SRE93** [comment]
Hi, I dont need a support case, I just want a clarification which statement is correct, because I need a valid statement to provide to our customers. So please research in which part of the text it is stated wrong

**Comment by dariomws** [comment]
Hi @SRE93, sorry for the delay.

As per my comment in the other issue, these sentences could be confusing but the second one is talking about OAuth. You can have it configured either using a classic or modern hybrid. If you are using modern, Autodiscover and EWS won't be published externally. You'll have to publish them to support Team calendar integration, not the hybrid configuration, but avoiding publishing services to the Internet is the main advantage of the modern hybrid.

That's why we highly recommend a full classic hybrid to support Teams calendar integration. You'll meet all the requirements under the section "Requirements to create and view meetings for mailboxes hosted on-premises" by default, no additional/manual configurations are required.
