### ISSUE TITLE
Clashing information related to using classic/modern hybrid in the same KB

### ISSUE THREAD

**Issue by Corina-github** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7887]
[Enter feedback here]
I've noticed bits of information clashing in this KB, more exactly : 
 Important

For integration with on-premises, it's highly recommended that you have an Exchange full Classic Hybrid deployment with Exchange Server 2016 or later. Modern Hybrid support is limited to Free/Busy and will not provide calendar integration from Teams to mailboxes on-premises, for example. For more information about setting up a hybrid deployment, see Exchange Server hybrid deployments.

vs

OAuth authentication is configured preferably via the Exchange Hybrid Configuration Wizard running a full hybrid configuration (Classic or Modern). If you are not able to use the Hybrid Configuration Wizard, configure OAuth as described in Configure OAuth authentication between Exchange and Exchange Online organizations.

As far as I know, Teams calendar for on premises mailboxes needs to have Classic hybrid deployed, as the hybrid agent is not able to properly redirect the requests for the calendar. 
As per https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent -  The Hybrid Agent supports free/busy and mailbox migrations; mail flow, directory synchronization, and other hybrid features are not included.

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact#requirements-to-create-and-view-meetings-for-mailboxes-hosted-on-premises)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Corina-github how are you?
Yes, both Classic and Modern are mentioned in the article.
Classic is **highly recommended** as the note says, to ease the process of setting up the integration. And you have to comply with these requirements https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact#requirements-to-create-and-view-meetings-for-mailboxes-hosted-on-premises
Adding @dariomws that worked on the article in the past.

**Comment by dariomws** [comment]
Hi @Corina-github, sorry for the delay.

This sentence could be confusing but the second one is talking about OAuth. You can have it configured either using a classic or modern hybrid. If you are using modern, Autodiscover and EWS won't be published externally. You'll have to publish them to support Team calendar integration, not the hybrid configuration, but avoiding publishing services to the Internet is the main advantage of the modern hybrid.

That's why we highly recommend a full classic hybrid to support Teams calendar integration. You'll meet all the requirements under the section "Requirements to create and view meetings for mailboxes hosted on-premises" by default, no additional/manual configurations are required.
