### ISSUE TITLE
Clarify Teams Communication Admin Role

### ISSUE THREAD

**Issue by cadasi** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7969]
We need to clarify in the article that the Teams Communications Admin Role will allow an Admin to manage and assign Cloud Phone Number/Calling Plan phone numbers to users, but it **won't allow to manage telephone numbers for Direct Routing or SIP Proxy users**, since Set-CsUser cmdlet is available only to Teams Administrators role.

Either that, or we need to change the Teams Communications Admin role to include the ability to use Set-CsUser, since the usage of it in the cloud is already limited to setting phone numbers only and it does not allow other changes to users.

Additional Info:

1) Our article says that Teams Communications Admin manages phone numbers assignment (among all the other things), but that will apply only for Calling Plans.

2)  For customers leveraging Direct Routing or SIP Proxy, since the Set-CsUser command is not available to Teams Communications Admin which is needed to assign numbers in those scenarios, Communication Admin role is useless and customers will be enforced to assign Teams Administrator roles, which gives full control over Teams and Enterprise customers won't like.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b434530-6bf2-6e00-6eae-6fa043d022ce
* Version Independent ID: caab785f-e3a4-831a-87d8-26934a9f834f
* Content: [Use Microsoft Teams administrator roles to manage Teams - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/using-admin-roles)
* Content Source: [Teams/using-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/using-admin-roles.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by ndambrosio** [comment]
You can assign the Skype for Business admin role along with the Teams Communications Admin role to give you the phone number management access you are looking for, but the documentation does need to be updated.

**Comment by dariomws** [comment]
And... What about Operator Connect? I think you can assign phone numbers with the Teams Communications Administrator role, but we need to confirm.

@ndambrosio, I'm not sure if we can or it is a good idea to add the option that you are suggesting to the article (Teams Communications Admin + Skype for Business admin).

Additional tip:
If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=<alias>

**Comment by ndambrosio** [comment]
Let me ping the EM to get their input.

Also, I believe you are addressing @cadasi as I'm pretty sure my alias is linked. I also run an internal GitHub training for field roles and this is the first topic we cover.
