### ISSUE TITLE
Is the Breakout Room limit 299 or 300?

### ISSUE THREAD

**Issue by GitRomney** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#7972]
This page says "Breakout rooms can only be created in meetings that have **fewer than** 300 attendees." (emphasis added). But in the next sentence it says, "creating breakout rooms... limits the number of meeting attendees to 300." 

So is the limit 299 (i.e., "fewer than 300"), or is the limit 300? Should it read "Breakout rooms can only be created in meetings that have **300 attendees or fewer**."?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905e2c09-ef3e-07cc-0809-6ff171157c47
* Version Independent ID: c0d33162-183d-fff8-32e9-a999f391ea51
* Content: [Limits and specifications for Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams)
* Content Source: [Teams/limits-specifications-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/limits-specifications-teams.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by get-itips** [comment]
Hello @GitRomney 

This is what I could find out

You start a meeting and you have <300 attendees. Until you hit that 300 number, – the meeting can scale beyond 300 people as more people can join, and you can also create breakout rooms
Once that 301st participant joins,  then you can no longer have breakout rooms for that meeting. 
Now let’s say that the meeting organizer initiated breakout rooms before the 301st joins. That will cap the meeting at 300 attendees, and then the 301st won’t be able to join the meeting because he’s the 301st.  

Hope this answers your question,

@scanum I think this can be closed now.

**Comment by GitRomney** [comment]
Thanks. So in that case, the article should read "Breakout rooms can only be created in meetings that have 300 attendees or fewer
 instead of "Breakout rooms can only be created in meetings that have fewer than 300 attendees." The current language is incorrect, since you can create breakout rooms in a meeting with 300 attendees.

**Comment by get-itips** [comment]
@GitRomney thanks for your feedback, will pass it on.
