### ISSUE TITLE
Terminology and redundant information.

### ISSUE THREAD

**Issue by davgroom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8106]
Hi, Donna.

Throughout the newly added content, we'll want to make sure that we standardize on the official service name "Microsoft Teams Rooms Managed Services".  The official name is long and "wordy" so it would be great if we could get your (or your team's advice) on the official process for referring to a product or service without repeating the long form every time.  Perhaps we can say "Microsoft Teams Rooms Managed Services hereafter referred to as "the managed service""?

Also, we have some redundant information in this page which is already covered in the public content.  I was expecting that we might find this - so it's not a surprise.  I can start cutting out some of the redundant info in a separate branch and then you can review.  We should discuss further how to tackle the process of removing info next week.

Thanks,
Dave

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 288f3ae5-fc15-194f-20da-743ae23f954a
* Version Independent ID: 288f3ae5-fc15-194f-20da-743ae23f954a
* Content: [Microsoft Teams Rooms Portal - Microsoft Teams](https://review.docs.microsoft.com/en-us/microsoftteams/rooms/managed-meeting-rooms-portal-guide?branch=pr-en-us-8298)
* Content Source: [Teams/rooms/managed-meeting-rooms-portal-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/managed-meeting-rooms-portal-guide.md)
* Service: **msteams**
* GitHub Login: @donnah007
* Microsoft Alias: **v-donnahill**

**Comment by dariomws** [comment]
@donnah007

**Comment by donnah007** [comment]
Thanks for the review and for finding additional redundant content. I removed some redundancy from the RBAC content.

I’ll ask Serdar about terminology.

Donna

From: David Groom ***@***.***>
Sent: Friday, November 5, 2021 2:25 PM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: Donna Hill (Steyer Associates Inc) ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Terminology and redundant information. (Issue #8106)


Hi, Donna.

Throughout the newly added content, we'll want to make sure that we standardize on the official service name "Microsoft Teams Rooms Managed Services". The official name is long and "wordy" so it would be great if we could get your (or your team's advice) on the official process for referring to a product or service without repeating the long form every time. Perhaps we can say "Microsoft Teams Rooms Managed Services hereafter referred to as "the managed service""?

Also, we have some redundant information in this page which is already covered in the public content. I was expecting that we might find this - so it's not a surprise. I can start cutting out some of the redundant info in a separate branch and then you can review. We should discuss further how to tackle the process of removing info next week.

Thanks,
Dave

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 288f3ae5-fc15-194f-20da-743ae23f954a
  *   Version Independent ID: 288f3ae5-fc15-194f-20da-743ae23f954a
  *   Content: Microsoft Teams Rooms Portal - Microsoft Teams<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Freview.docs.microsoft.com%2Fen-us%2Fmicrosoftteams%2Frooms%2Fmanaged-meeting-rooms-portal-guide%3Fbranch%3Dpr-en-us-8298&data=04%7C01%7Cv-donnahill%40microsoft.com%7C60b00d50459a4842c56d08d9a0a2acde%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637717442828954401%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fwfdhjueU8RIQR2mZzqC9no0Oc%2F3i77MyXtYeKhTTtM%3D&reserved=0>
  *   Content Source: Teams/rooms/managed-meeting-rooms-portal-guide.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fblob%2Flive%2FTeams%2Frooms%2Fmanaged-meeting-rooms-portal-guide.md&data=04%7C01%7Cv-donnahill%40microsoft.com%7C60b00d50459a4842c56d08d9a0a2acde%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637717442828964369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DapQ3%2Bt0xYpklG5P7FZqQhxmb%2FfvZ%2FJgSwFR%2BjNajWQ%3D&reserved=0>
  *   Service: msteams
  *   GitHub Login: @donnah007<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdonnah007&data=04%7C01%7Cv-donnahill%40microsoft.com%7C60b00d50459a4842c56d08d9a0a2acde%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637717442828964369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ltATSIjR1X1t7waXCE0CLEwqSwayH9JqhxynR00js3c%3D&reserved=0>
  *   Microsoft Alias: v-donnahill

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SkypeForBusiness%2Fissues%2F8106&data=04%7C01%7Cv-donnahill%40microsoft.com%7C60b00d50459a4842c56d08d9a0a2acde%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637717442828974314%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sVJgp1Wxs7URrIKFQD1OSJuWyc6%2FQBo6x7CNT3IMQMM%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWCD436ZACVBNEXIZYCW3CTUKRKSPANCNFSM5HOXH57A&data=04%7C01%7Cv-donnahill%40microsoft.com%7C60b00d50459a4842c56d08d9a0a2acde%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637717442828974314%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xlwJKSIZE%2B%2Bif5U6MS0qzDH7ftfyaafAT0Vqb3lslxA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cv-donnahill%40microsoft.com%7C60b00d50459a4842c56d08d9a0a2acde%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637717442828984279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UwMJkv9I%2B%2FNtATMM5Nbv2g6Md6nG8HPT7vQJccBoNPc%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cv-donnahill%40microsoft.com%7C60b00d50459a4842c56d08d9a0a2acde%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637717442828984279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Uy8v7eSC0lUzOVjlFET4zYCivGYvFOZYBFLz8o4%2F414%3D&reserved=0>.
