### ISSUE TITLE
Microsoft Teams App Installation (Option 2: Configure via MDM such as Intune)

### ISSUE THREAD

**Issue by nicolonsky** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#817]
Is it necessary to assign the teams app in Microsoft Intune to the Surface Hub or will the teams app automatically install when the "./Vendor/MSFT/SurfaceHub/Properties/VtcAppPackageId" is configured for the surface hub? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f256cd5b-3ec8-2d55-9ae4-ff9849d52eae
* Version Independent ID: 52c2271b-df38-5dc9-c2a1-553cdf3b5496
* Content: [Deploy Microsoft Teams for Surface Hub](https://docs.microsoft.com/en-us/microsoftteams/teams-surface-hub)
* Content Source: [Teams/teams-surface-hub.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-surface-hub.md)
* Service: **msteams**
* GitHub Login: @chuckedmonson
* Microsoft Alias: **chucked**

**Comment by AndreaBarr** [comment]
@nicolonsky Thank you for this feedback

I am honestly not sure. I will get this over to someone who can answer this for you. If you need an expedited answer though contact Support since they can also handle this to resolution. 

I was able to get this into the backlog for the Teams/Skype for Business team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by danieldhudson** [comment]
Yes, you do have to install the Teams app on Surface Hub in order for it to work.

**Comment by get-itips** [comment]
Hi @nicolonsky thanks for your feedback and comments, we really appreciate them.
As @danieldhudson says, you do need to install the Teams app as the document says before setting it to default calling and meeting application. You could also use intune to assign it and push it. Hope this information helped you so we can safely close this issue.

**Comment by yogkumgit** [comment]
@get-itips  Thank you very much for the contribution and sharing this explanation. @ nicolonsky
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
