### ISSUE TITLE
policy sync may require reboot

### ISSUE THREAD

**Issue by DanStevensonMSFT** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8202]
under certain conditions that impact some users, the messaging and meeting policies will not sync, and thus after every policy change, they should advise impacted users to reboot

impacts all tenants

fix ETA maybe February 2022

see ICM https://portal.microsofticm.com/imp/v3/incidents/details/270279237/home

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 813bcae6-1c45-1d12-6652-de7d0986edfa
* Version Independent ID: fe0b1991-f210-bf08-850a-487f4c9b1b8e
* Content: [Manage meeting policies in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-policies-overview)
* Content Source: [Teams/meeting-policies-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-policies-overview.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @DanStevensonMSFT, than you for your feedback.

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=DanStevensonMSFT

**Comment by dariomws** [comment]
@CarolynRowe, I do not have access to the link. Could you kindly help me to confirm the information there? Thank you!

**Comment by CarolynRowe** [comment]
Hi @dariomws:  Are you asking me to check the links?  Yes, both worked for me.  Although the second did not find a search result for danStevenson...

**Comment by dariomws** [comment]
Hi @CarolynRowe,

I'm asking for the following link:
https://portal.microsofticm.com/imp/v3/incidents/details/270279237/home

I want to confirm this information and maybe we should (I can do it) add a note to this article with the information that Dan is sharing.

Thanks.

**Comment by tiburd** [comment]
@DanStevensonMSFT 
Hi, Dan,

Thank you for your submission.

Because you are an internal Microsoft contributor, we recommend finishing your GitHub setup:
- [Set up your accounts](https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-github-ro?branch=main)

And then you can submit a PR in the private repo to add the information:
- [Quickly update an article by using GitHub.com](https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-quick-update?branch=main)

As mentioned at the end of the article, @ mention the article author so that she can approve your changes.

Thanks!
