### ISSUE TITLE
Update Limitations

### ISSUE THREAD

**Issue by ncoimbra** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8276]
[Enter feedback here]
Hello Team, as far I know, some of the limitations of Teams for VDI are FIXED in the last releases of Teams for VDI + WebRTC. Also for Mac clients.

Please update the page with that improvements.
Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/teams-for-vdi)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @serdars
* Microsoft Alias: **v-mahoffman**

**Comment by dariomws** [comment]
Hi @ncoimbra, thank you for your feedback.

@v-mahoffman, could you kindly help here? Thanks.

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved. Some updates were applied to "Known issues and limitations" section since you opened this issue.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
