### ISSUE TITLE
Double normalization does not occur

### ISSUE THREAD

**Issue by ilovebacon** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8279]
The doc says that if a tenant dial plan matches a translation rule which does not produce a leading +, the result will be processed again by the country specific dial plan. This in fact does not happen, as shown by Test-CsEffectiveTenantDialPlan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 847c0505-3441-b5db-1f81-c7759bffd1e3
* Version Independent ID: 3c6b3820-349f-caf5-c510-a771a3b7a770
* Content: [What are dial plans? - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/what-are-dial-plans)
* Content Source: [Teams/what-are-dial-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/what-are-dial-plans.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @ilovebacon, thank you for your feedback.

I'll try to confirm this information.

**Comment by dariomws** [comment]
@ilovebacon, this is the information I have got from the person who added that sentence:

"The Test-CsEffectiveDialPlan only tests against customer's Tenant Dial Plan, which is a gap in this test cmdlet.

The change to the documentation was driven by Incident reported by customer when Tenant normalization rule they created did not result in number routed outbound to match the number translation. The problem was that the number translated by tenant rule did not result in E.164 number and the pattern matched the user's regional CSDialPlan and was then normalized by Call Controller."
