### ISSUE TITLE
Islands mode with Teams as default for receiving PSTN calls

### ISSUE THREAD

**Issue by Dominik-D** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#830]
We do want to receive PSTN calls in Teams. Currently this is only possible by setting the TeamsUpgradePolicy to TeamsOnly. By that we limit the Skype for Business client functionalities down to joining meetings. However we still have business cases that require full Skype for Business client functionality.

Please create a TeamsUpgradePolicy that allows setting Teams as default for receiving PSTN calls, while maintaining full Skype for Business client functionality (except PSTN calling).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49921e8a-55ac-f547-d4e2-d329f5089c2e
* Version Independent ID: 91c3433a-3684-95cd-3426-4a5877b33106
* Content: [Migration and interoperability guidance for organizations using Teams together with Skype for Business](https://docs.microsoft.com/en-us/microsoftteams/migration-interop-guidance-for-teams-with-skype)
* Content Source: [Teams/migration-interop-guidance-for-teams-with-skype.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/migration-interop-guidance-for-teams-with-skype.md)
* Service: **msteams**
* GitHub Login: @arachmanGitHub
* Microsoft Alias: **MyAdvisor**

**Comment by AndreaBarr** [comment]
@Dominik-D Thank you for this suggestion

I know the product teams are always looking for user feedback and how to make the OneDrive / SharePoint better. They keep a close tab on User Voice [https://sharepoint.uservoice.com](https://sharepoint.uservoice.com). I found a User Voice item that I have upvoted and suggest you do as well so that we can get this looked at quicker as an addition to Teams. https://microsoftteams.uservoice.com/forums/555103-public/suggestions/34310035-receive-inbound-calls-in-teams-via-calling-plan

Thank you for your contribution to make the docs better! Much appreciated!
