### ISSUE TITLE
Information on new command to set hostedvoicemail to true/false?

### ISSUE THREAD

**Issue by jlon125** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8415]
It looks like the old command is gone - Can we get documentation on how you would enable hostedVoicemail, or how to disable it, if the default is enabled?

**Comment by JensTrier** [comment]
@jlon125 Thanks for the feedback!

I think you are referring to Set-CsUser as the old cmdlet? The cmdlet is still available, but it's usage for Microsoft Teams will be deprecated in the future and the guidance is to use Set-CsPhoneNumberAssignment.

Set-CsPhoneNumberAssignment does not expose the HostedVoicemail parameter, because Cloud Voicemail is automatically enabled for all users. If you want to disable Voicemail for a given user, you can use Set-CsOnlineVoicemailUserSettings -VoicemailEnabled $false
