### ISSUE TITLE
Skype for Business Administrator role is also required

### ISSUE THREAD

**Issue by SvenBell** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8567]
We have found that currently the Skype for Business Administrator role is also required to assign PSTN numbers to resource accounts when you do not have the Global Administrator role.

Also worth noting, to assign Teams licenses like Teams Phone Standard license to a user/resource account requires User Administrator role.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b434530-6bf2-6e00-6eae-6fa043d022ce
* Version Independent ID: caab785f-e3a4-831a-87d8-26934a9f834f
* Content: [Use Microsoft Teams administrator roles to manage Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/using-admin-roles)
* Content Source: [Teams/using-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/using-admin-roles.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @SvenBell, thank you for your feedback.

This issue is the same as:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5978
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5980

@CLYVR do you know what role is required to assign a number to a resource account? It seems that Teams Service Admin is not enough. Thanks!

**Comment by dariomws** [comment]
Hi @SvenBell, I remembered something.

Are you using Set-CsUser or Set-CsPhoneNumberAssignment?
