### ISSUE TITLE
Issue Uploading Location Data

### ISSUE THREAD

**Issue by AndyH16** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#858]
Unfortunately I've followed the guide and the sample data and I can't seem to upload our data. When I try I just get the message 'We couldn't upload location data. Please verify the contents of the file and try again.'

It's a CSV, with the data separated by commas (the sample data was a CSV with tabs separating). Not all the fields contain data but the relevant number of empty fields have been entered. An example of one of our entries is below:

10.100.0.0,ISP-London,16,,,,,London,,,,,1,0

We only really need the location at city level, so address/building information is not relevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f8119c9-61af-b469-af98-ddd37764c0ca
* Version Independent ID: 7d829a74-9df7-5b6f-8e1c-44d3e5d38f75
* Content: [Adding and updating Locations data](https://docs.microsoft.com/en-US/microsoftteams/learn-more-about-site-upload?WT.mc_id=TeamsAdminCenterCSH)
* Content Source: [Teams/learn-more-about-site-upload.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/learn-more-about-site-upload.md)
* Service: **msteams**
* GitHub Login: @tonysmit
* Microsoft Alias: **lolaj**

**Comment by AndreaBarr** [comment]
@AndyH16 Thank you for your feedback

I am not sure why the location data isn't uploading. I want to make sure this gets documented and addressed promptly. Support has more resources to assist with this issue then we do here. I would like to have you open a Support ticket so that we can get this looked at and resolved for you. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by AndyH16** [comment]
Just to update this post. After contacting support, they initially suggested filling all the data in which worked. However some was not relevant, so I populated these fields as "N/A". Doing this on the 'Building Name' field caused the locations to be grouped as a single location - so this field needed to be unique. Support then followed up to say that they had found that I could have an empty field by adding a space.
