### ISSUE TITLE
Shared Channels should work with regular Guests as otherwise useless

### ISSUE THREAD

**Issue by gvSmartEnergy** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8745]
[Enter feedback here]
This feature is entirely useless for us as an SME. We work with many diverse Teams from numerous organisations often without MS Azure. Shared Channels should work with Guests as Teams do. Creating Teams for every small proposal is overkill and hard to keep track off. This feature promised to be the solution but it is only designed for big companies. Please open it up or think of something else. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Version Independent ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Content: [Shared channels in Microsoft Teams (Preview) - Microsoft Teams](https://docs.microsoft.com/en-us/MicrosoftTeams/shared-channels)
* Content Source: [Teams/shared-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/shared-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by thuntkt** [comment]
I agree with the comment above. Not all of our consultants use Azure AD or have dedicated IT support. Even for those that do, having to ask them to configure access before being able to share a channel is cumbersome and unnecessary, and doesn't allow our project teams the flexibility to set this up for themselves. This is a much-needed feature, but useless unless guests can access. If there is a better place to submit this feedback so that it will actually garner consideration for changing the product, please advise.
