### ISSUE TITLE
GCCH Specific details

### ISSUE THREAD

**Issue by J227668** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8766]
This feature is not currently available in GCCH to all tenants. Can you please add specific information about this features availability in GCCH? 

Here is the link to the roadmap entry for this. https://www.microsoft.com/en-us/microsoft-365/roadmap?featureid=86311 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470478ed-3b4e-ced8-0e28-6cda545b8400
* Version Independent ID: 95b4044b-3a47-a511-c726-b5ee75863441
* Content: [Manage meeting settings - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams#feedback)
* Content Source: [Teams/meeting-settings-in-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/meeting-settings-in-teams.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @J227668, thank you for your feedback.

I think this feature should be available now for GCCH.

**Comment by J227668** [comment]
@dariomws it is currently being rolled out and should be available to all tenants by the end of the month is my current understanding. Customers often look to the docs page for guidance on if the feature is available in GCCH and if the set up/configuration the process is the same. Can we call out in the document any known parity? https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams. 
Alternatively can we call out specifically that anonymous meeting join is available to GCCH customers? 
https://docs.microsoft.com/en-us/microsoftteams/meeting-settings-in-teams#allow-anonymous-users-to-join-meetings

**Comment by dariomws** [comment]
@J227668, please check the note I'm adding.

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: [https://repos.opensource.microsoft.com/people?q=<alias>](https://repos.opensource.microsoft.com/people?q=J227668)
