### ISSUE TITLE
Teams Calendar showing in Modern Hybrid

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#8882]
Hello, we are having customers which are getting the Teams Calendar function in Teams App, but they are using Exchange Modern Hybrid (Hybrid Agent) with Onpremises mailboxes.

Is this expected? Maybe a design change?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8456689d-6f04-fa5e-4f51-f413cb0b9d89
* Version Independent ID: e9b85126-0db7-4378-ad44-514e52f9fde1
* Content: [How Exchange and Microsoft Teams interact - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact)
* Content Source: [Teams/Exchange-Teams-interact.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/Exchange-Teams-interact.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by SRE93** [comment]
Any updates on this?

**Comment by dariomws** [comment]
Hi @SRE93, thank you for your feedback.

A full classic hybrid is not a requirement but a recommendation to simplify the configuration. If you have a hybrid modern configuration and the Teams calendar is working, you might have the Autodiscover and Exchange Web Services published externally.

**Comment by SRE93** [comment]
Hi @dariomws, understood. But for my understanding it should work for all or no users. In this case the calendar in Teams is showing up for a little subset of Exchange OnPrem Mailboxes without any config change (excluded CU updates) since month!

**Comment by dariomws** [comment]
Hi @SRE93,

Hard to help you here as we are limited to documentation issues. The best way to get help is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information provided at [Get support](https://docs.microsoft.com/microsoft-365/business-video/get-help-support). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).
