### ISSUE TITLE
Visio not available when client is in public preview mode

### ISSUE THREAD

**Issue by DevJonBirkett** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9022]
Hi, 
For completeness, it would be worth adding a note that when the Team client is put into public preview mode the option to add Visio as a tab will disappear and any already added Visio tabs in a channel will be hidden. 

I have spoken the MSFT Support and they have confirmed this is expected behavior/by design. 

**Support case for reference:** Case #:31350712

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5f1cdd1-09ff-f95d-6d50-e7880d34020f
* Version Independent ID: 59219640-305b-30c1-bc10-87e2633d95db
* Content: [Public preview in Microsoft Teams - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/public-preview-doc-updates)
* Content Source: [Teams/public-preview-doc-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/public-preview-doc-updates.md)
* Service: **msteams**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @DevJonBirkett, thank you for your feedback.

From this article:
For a list of what's available in the Teams public preview, visit [Microsoft Teams Public Preview tech notes](https://techcommunity.microsoft.com/t5/microsoft-teams-public-preview/bd-p/MicrosoftTeamsPublicPreview), [Release Notes for Teams Admin Features](/OfficeUpdates/teams-admin), and [What's new in Teams](https://support.microsoft.com/office/what-s-new-in-microsoft-teams-d7092a6d-c896-424c-b362-a472d5f105de).

Because it does not include what is available or not in the Teams public preview, I think the best place to have the visio tab missing item is Microsoft Teams Public Preview tech notes. I added a discussion there:
https://techcommunity.microsoft.com/t5/microsoft-teams-public-preview/visio-tab-not-available-in-public-preview/m-p/3592286#M903
