### ISSUE TITLE
Modify monitoring reports

### ISSUE THREAD

**Issue by georgerozgonyigmailcom** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#916]
I was requested to modify the MS standard reports of S4B 2015 at a customer. Does someone have experience how to locate the datasets of the reports? I mean any other than the Monitoring cockpit. The report start page points to crafted URLs and I struggle to find the rdl source.
THX, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2209aab2-38e0-a948-52fc-d5da3cca0dfa
* Version Independent ID: 2fe17cfb-9e86-846e-2832-cb8c72312f33
* Content: [Using Monitoring Reports in Skype for Business Server](https://docs.microsoft.com/en-us/skypeforbusiness/manage/health-and-monitoring/monitoring-reports#feedback)
* Content Source: [Skype/SfbServer/manage/health-and-monitoring/monitoring-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbServer/manage/health-and-monitoring/monitoring-reports.md)
* Product: **skype-for-business-itpro**
* GitHub Login: @jambirk
* Microsoft Alias: **jambirk**

**Comment by AndreaBarr** [comment]
@georgerozgonyigmailcom  Thank you for this feedback

I am not sure how to locate Data sets. Let me get this over to the Teams/Skype for Business team for investigation.  If you need this expedited please contact Support. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jambirk** [comment]
@georgerozgonyigmailcom If i understand this correctly, since the reports are generated from data in a database set up and associated for that purpose, it's not possible to give an answer that will always be correct, since it was user-configured at creation. Your best bet mat be to use the powershell command documented at https://docs.microsoft.com/en-us/powershell/module/skype/get-csreportingconfiguration?view=skype-ps which should return the information for a specific instance. Hope that solves your problem.

**Comment by yogkumgit** [comment]
@jambirk  Thank you very much for the contribution and sharing this explanation. @georgerozgonyigmailcom   Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
