### ISSUE TITLE
Set-CsPhoneNumberAssignment -Identity "" -EnterpriseVoiceEnabled $true is not working

### ISSUE THREAD

**Issue by waelschakaki** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9232]
Hello
there is an issue in running this command in the latest Teams Powershell module

--------
If you're managing the user's phone number on-premises, you need to ensure that the user is Enterprise Voice enabled online by using the following command:

Set-CsPhoneNumberAssignment -Identity "<User name>" -EnterpriseVoiceEnabled $true
------
the powershell is always asking for phone number, and if it is assigned from on-prem you can't assign a number in the cloud, how to fix it ?
Regards,
Wael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2a9717-6565-8443-8833-f7fdce562781
* Version Independent ID: db88c4d6-5864-a481-86cf-465feb452d75
* Content: [Enable users for Direct Routing - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/direct-routing-enable-users)
* Content Source: [Teams/direct-routing-enable-users.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/direct-routing-enable-users.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by JG-Robo** [comment]
I'm having this issue as well.

**Comment by JG-Robo** [comment]
For me it started working again the day after this issue was reported.

**Comment by JensTrier** [comment]
Yes, turns out there was an incident reported to affected tenants under MO419852 that match the timing of this report.

Feel free to close this issue.

**Comment by JensTrier** [comment]
@waelschakaki That error is by design, if the user has the msRTCSIP-Line attribute set in the on-premises AD and it is synched to Microsoft 365. When you do Get-CsOnlineUser for the user, you should see the attribute OnPremLineUri having a value. Try to see here https://docs.microsoft.com/en-us/microsoftteams/manage-phone-numbers-landing-page#where-phone-numbers-are-managed

If you are getting this error AND the user hasn't the msRTCSIP-Line set in the on-premises AD, please open a Microsoft support case and they will work with you to investigate it.

**Comment by waelschakaki** [comment]
ok sorry my mistake in the second comment i should have use -EnterpriseVoiceEnabled and not -PhoneNumberType , so my first comment was correct, but in the second one i have used a wrong parameter, i will close the issue now and thanx for support.
