### ISSUE TITLE
ediscovery/content search is able to get edited messages without a hold, not just the last edited message

### ISSUE THREAD

**Issue by Teamsgineer** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9295]
Hi,
the statement:
Edited messages | If the user is on hold, previous versions of edited messages are also preserved.

is not too accurate as when performing a Content Search without a Hold, all the edited messages in a channel/chat are able to be found , and not just the last edited message.

feedback is to provide better written clarity in this doc, of what is able to be discovered in Content Search without the Hold for edited/deleted chat/channel messages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 840dd36b-8c29-9738-4adc-ea9a7d277fd0
* Version Independent ID: b12c43c3-ed81-ace5-dfeb-77cac0f97fe9
* Content: [Conduct an eDiscovery investigation of content - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/ediscovery-investigation)
* Content Source: [Teams/eDiscovery-investigation.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/eDiscovery-investigation.md)
* Service: **msteams**
* GitHub Login: @v-tophillips
* Microsoft Alias: **v-tophillips**

**Comment by dariomws** [comment]
Hi @Teamsgineer, thank you for your feedback.

When you edit or delete a message in Teams and there is no retention policy to preserve it, it is permanently deleted typically between 1-7 days, not immediately. That's why you can find it using eDiscovery. But after 7 days it's permanently deleted.

For more information:
https://learn.microsoft.com/microsoft-365/compliance/retention-policies-teams
