### ISSUE TITLE
Incorrect License Information

### ISSUE THREAD

**Issue by LtCmdrKeene** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9305]
This page says agents answering calls in the call queue require "An Audio Conferencing license", which they do have. But yet still aren't in the queue. It turns out the users are not enterprise-voice enabled, and this page doesn't explain that this is a requirement or how to accomplish it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23ff8713-7e33-ad8e-99df-9308a7c006d7
* Version Independent ID: c9263eba-599b-831b-37fb-837046df9d6a
* Content: [Plan for Teams auto attendants and call queues - Microsoft Teams](https://docs.microsoft.com/en-us/microsoftteams/plan-auto-attendant-call-queue)
* Content Source: [Teams/plan-auto-attendant-call-queue.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/plan-auto-attendant-call-queue.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @LtCmdrKeene, thank you for your feedback.

My apologies but I don't understand what is missing in the article. Currently, it contains the following information:

"Agents who receive calls from the call queues **must be Enterprise Voice enabled online** or on-premise users. In addition, if the call queues are using Direct Routing numbers, agents who need to conference or transfer calls also require:

- An online voice routing policy assigned if the call queue uses transfer mode
- An Audio Conferencing license or online voice routing policy assigned if the call queue uses conference mode"

**Comment by dariomws** [comment]
Ok, but I think that was not requested in the original comments.

Your new comment was answered here:
https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9121

**Comment by LtCmdrKeene** [comment]
That page doesn’t seem to answer the question. Please help me understand what I’m missing, but it appears to me that:


  1.  The initial post on that page has a user who shares an anecdote that simply setting a user to voiceEnabled=True by PowerShell “works fine”, but that is not true for us. Yes I can successfully set a user’s EnterpriceVoiceEnabled status in PowerShell, but a user configured this way does not show up in a Call Queue until/unless we also purchase and assign a PTSN phone number (exactly opposite of this user’s anecdote).



  1.  The referenced page (Here's what you get with Phone System - Microsoft Teams | Microsoft Learn<https://learn.microsoft.com/en-us/microsoftteams/here-s-what-you-get-with-phone-system>) doesn’t classify the situation and never specifies if the user needs a PTSN phone number assigned to be able to participate in a call queue and/or have a PTSN phone number assigned to be properly “Enterprise Voice Enabled”.

We’ve had to purchase and assign many phone numbers for some agents. We don’t want these agents to make/take calls to/from those local DID numbers, but we had choice: the users could not be in the Call Queue without assigning the numbers.

**Comment by dariomws** [comment]
@LtCmdrKeene, my apologies but I only can help with article updates here.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by LtCmdrKeene** [comment]
Alright I can do that. Honestly I thought what we observed was “working correctly” and just couldn’t find documentation that was definitive.

So I can tell support that an agent without a PTSN should be able to join a call queue, and this doc confirms that?

**Comment by TeamsTechBear** [comment]
@dariomws 

https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/9121

Me and @LtCmdrKeene are discussing this on my issue that you linked and that I relinked above. It's kind of a very gray area that I'm not sure is called out anywhere. Using this method it gets around having to purchase anything extra besides a master license that includes a Teams license, "Phone System license" (No Calling Plans, Communication Credits, Phone Number, etc.), and using PowerShell to "Enterprise Voice Enable" "True" a user. Plus it seems to act very weird/not fully active and isn't fully explored in the way it works with using a teams' channel for a "Calling Queue" membership. 

The question should be phrased **_"I'm using a teams' channel membership based call queue to have people call directly via its name and not a number becuase it doesn't have one and we don't want the call queue to be reachable from outside the company.  We are not able to get people added to the call queue without giving them a master license that includes the "Phone System" sub license AND assign them a phone number. We would like for these call queue members to be able to recive calls from the "teams' channel membership based call queue" without having to assign a phone number to them because these users don't need a direct number and we don't want them to be able to call from or get calls to thier numbers. How can I accomplish this?"_**

**_(The reason I asked for what Microsoft's Documentation means/says about their meaning of "Enterprise Voice Enabled" is because I don't want anyone getting into trouble via Microsoft's Terms and License usage agreements via this method. I would ask your Microsoft rep if this is acceptable and ok. I accept no responsibility and use at your own risk. I was just testing to see if we could technically do this.)_**

**Comment by scanum** [comment]
Hi @dariomws hope all is well. Can this be considered as resolved? Thanks!

**Comment by dariomws** [comment]
Hi @LtCmdrKeene and @TeamsTechBear,

Here is the answer:
"When you assign a phone number the EnterpriseVoiceEnabled flag is automatically set to True."
https://learn.microsoft.com/powershell/module/teams/set-csphonenumberassignment

**Comment by LtCmdrKeene** [comment]
> 

I need to have people be in a queue without assigning a phone number to them personally. I don't want to assign a phone number to call center agents, they aren't to be dialed personally/directly by PTSN, but they need to answer the queue calls.

**Comment by dariomws** [comment]
@LtCmdrKeene,

I know the product teams are always looking for user feedback and how to make Microsoft products better. They keep a close tab on user feedback and it would be awesome if you could add your voice to the Microsoft Feedback Portal: https://feedbackportal.microsoft.com/feedback/. 

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request. 

Thank you for your contribution to making the docs better! Much appreciated!

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
