### ISSUE TITLE
Poor Customer Service

### ISSUE THREAD

**Issue by ebmgithub** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9363]
The response below has been poorly handled.   I've just wasting half a day testing the advice in the main article to find out that it blocks calls/meetings globally.  This should be clearly spelled out in documentation with the appropriate work around to limit only the RDS environment.  Limiting calls/meetings only in the RDS environment (by machine) should have been the primary method.  Limiting calls/meetings globally is likely not a good solution for anyone.

        Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

_Originally posted by @scanum in https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/7879#issuecomment-924518182_

**Comment by dariomws** [comment]
Hi @ebmgithub, thank you for your feedback.

I'm not aware of a way to disable these features only for specific computer (RDS). Here we are limited to documentation issues, and I cannot provide (add to the article) the information that you are requesting.

That's why my colleague suggested to try with support. Or maybe you can contact your technical account.

**Comment by scanum** [comment]
Hi @ebmgithub Hope all is well. Please let us know if there are any additional questions.
