### ISSUE TITLE
In the "change a license" section, suggest to also add best practice for license changes in a group-based licensing scenario

### ISSUE THREAD

**Issue by davidjfriedman** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9369]
In the "change a license" section, suggest to also add best practice for license changes in a group-based licensing scenario

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3275e03f-6c8e-a61f-2d0b-52b0bc45e0d7
* Version Independent ID: 3275e03f-6c8e-a61f-2d0b-52b0bc45e0d7
* Content: [Phone numbers and licensing changes - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/phone-numbers-licensing-changes)
* Content Source: [Teams/phone-numbers-licensing-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/phone-numbers-licensing-changes.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by adrianfleisch** [comment]
When can we expect the expansion with "best practice for license changes in a group-based licensing scenario"?

**Comment by dariomws** [comment]
Hi @davidjfriedman, thank you for your feedback.

I'll forward your feedback, but I cannot promise that the content will be added to the article because this is a very specific situation. May I suggest you contact support or your TAM for more proactive help with this issue.

**Comment by scanum** [comment]
Hi @adrianfleisch Hope all is well. Please let us know if there are any additional questions.

**Comment by adrianfleisch** [comment]
> Hi @davidjfriedman, thank you for your feedback.
> 
> I'll forward your feedback, but I cannot promise that the content will be added to the article because this is a very specific situation. May I suggest you contact support or your TAM for more proactive help with this issue.

Thanks. but it's not a issue. It's just a suggestion to enhance the documentation with additional information, because a customer asked about it. 
@scanum It's ok for me. Have no additional questions.

**Comment by dariomws** [comment]
@davidjfriedman and @adrianfleisch,

I think the important information for your topic is:

- From this article: "If you need to change a license for a user that involves one of the prerequisite licenses, you should ensure that the licensing changes are made and saved at the same time. This method will ensure that the user keeps their assigned phone number and can continue making and receiving PSTN calls in Microsoft Teams."
- From https://learn.microsoft.com/microsoftteams/phone-numbers-licensing-changes, "When you update license assignments for a user or group, the license assignment removals and new assignments are made simultaneously so that users do not lose access to their services during license changes or see license conflicts between plans."
