### ISSUE TITLE
Add details about when an expiration date is updated during autorenewal

### ISSUE THREAD

**Issue by simpkinspete** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9440]
It would be helpful to include details about when a Team's expiration date will update if the group meets the conditions for autorenewal. Proactive Team Owners might be concerned when they see a date and want to know when it will reflect the accurate expiration based on the group's activity. 

I'm assuming that the date updates 30 days before expiration to align with the trigger to notify an inactive group's owners to renew. If so, will it set the new expiration to the (expiration period)+(expiration date) or (expiration period)+(notification date)?

For example, if an active group with an expiration period of 90 days has an expiration date of 12/31/2022, will it auto-renew on 12/01/2022 with a new expiration date of **03/01/2023** or **03/31/2023**.

If it doesn't update 30 days before expiration, will it update **on** or **after** the expiration date? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b41d63bc-26f4-fd50-adc4-f665c1a4cd88
* Version Independent ID: 24248b2d-79a1-98a7-86dd-f6dbcf9e2ab3
* Content: [Team expiration and renewal in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/team-expiration-renewal)
* Content Source: [Teams/team-expiration-renewal.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/team-expiration-renewal.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by dariomws** [comment]
Hi @simpkinspete, thank you for your feedback.

I think you can find all the answers to your question in the following articles:
https://learn.microsoft.com/azure/active-directory/enterprise-users/groups-lifecycle
https://learn.microsoft.com/microsoft-365/solutions/microsoft-365-groups-expiration-policy

For example:
- For example, if an owner or a group member does something like upload a document to SharePoint, visit a Teams channel, send an email to the group in Outlook, or view a post in Yammer, the group is automatically renewed around 35 days before the group expires and the owner does not get any renewal notifications.
- From the Renew group notification email, group owners can directly access the group details page in the Access Panel. There, the users can get more information about the group such as its description, when it was last renewed, when it will expire, and also the ability to renew the group. The group details page now also includes links to the Microsoft 365 group resources, so that the group owner can conveniently view the content and activity in their group.

**Comment by scanum** [comment]
Hi @simpkinspete Hope all is well. Does this answer your question? Thanks.
