### ISSUE TITLE
custom background not showing

### ISSUE THREAD

**Issue by Elgwada01** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9493]
It would be good to also track when the ability to set up custom backgrounds on MTRoA will also be available as a lot of compagnies are waiting on it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 64cc650b-b313-cfab-9f45-190b94c128f4
* Version Independent ID: 9e93ac07-3f1b-9fd4-1907-17f0075bd837
* Content: [Teams Rooms for Windows and Android feature comparison - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/rooms/teams-devices-feature-comparison)
* Content Source: [Teams/rooms/teams-devices-feature-comparison.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/rooms/teams-devices-feature-comparison.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @Elgwada01, thank you for your feedback.

Custom backgrounds are available in personal mode since April 2021:
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/microsoft-teams-rooms-on-android-april-2021-updates/ba-p/2259772

You can track all the features updates for MTR in the following places:
https://techcommunity.microsoft.com/t5/microsoft-teams-blog/bg-p/MicrosoftTeamsBlog/label-name/Microsoft%20Teams%20Rooms
https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Microsoft%20Teams%2CAndroid#owRoadmapMainContent

**Comment by Elgwada01** [comment]
Hi Dario,

Thank you for your reply. Sorry for not being clear, but i was talking about the actual consistent background, not the one related to video meetings. We would like to be able to use our company background instead of the 5 backgrounds that you get as default with Android. On an MTR on Windows, we are able to upload our own background using an XLM script, but this option is currently not yet available on Android.

Kind Regards,
ritchie

________________________________

**Comment by dariomws** [comment]
Hi @Elgwada01, thank you for your reply.

In addition to the links I sent you, you can vote and track the ability of custom wallpaper/background for MTRoA in the following site:
https://feedbackportal.microsoft.com/feedback/idea/ae6c0195-8b6c-ec11-a81b-000d3ae5ad05

**Comment by scanum** [comment]
Hi @Elgwada01 Hope all is well. Could you confirm this answers your questions? Thanks.
