### ISSUE TITLE
Pricing links don't have pricing

### ISSUE THREAD

**Issue by mrbuckingham** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#956]
You pricing links go sites for teams that give pricing general Office 365 subscriptions but not the Audio Conferencing add in. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b07cfcf-8f31-91ed-b1de-c7826a1ab91d
* Version Independent ID: dfbc4212-8f47-326a-f872-8186a915ae1e
* Content: [Country and region availability for Audio Conferencing and Calling Plans](https://docs.microsoft.com/en-us/microsoftteams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans#feedback)
* Content Source: [Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/country-and-region-availability-for-audio-conferencing-and-calling-plans/country-and-region-availability-for-audio-conferencing-and-calling-plans.md)
* Service: **skype-for-business-online**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by AndreaBarr** [comment]
@mrbuckingham Thank you for pointing this out to us

I will get the information for this link issue to the Teams/Skype for Business team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by LolaJacobsen** [comment]
The pricing information is in a cross-linked article: https://docs.microsoft.com/en-us/SkypeForBusiness/skype-for-business-and-microsoft-teams-add-on-licensing/skype-for-business-and-microsoft-teams-add-on-licensing

**Comment by mrbuckingham** [comment]
There's no pricing on that page or the cross linked pages. There is pricing
for Office 365 but the add on.

That's why I posted this. If you found the pricing, what is it?

**Comment by mrbuckingham** [comment]
The whole point is the cross link that claims to have pricing doesn't.

**Comment by mrbuckingham** [comment]
Ok. If you click on a link on the page linked to and scroll down a few
pages it's in there.  Why wouldn't the link to pricing in this article take
you to the page that has the pricing?

**Comment by AndreaBarr** [comment]
@heyadamGIT Could you please investigate this issue?

**Comment by heyadamGIT** [comment]
On it. I will respond today.--Adam
-------- Original message --------From: AndreaBarr <notifications@github.com> Date: 12/26/18  11:53 AM  (GMT-08:00) To: MicrosoftDocs/OfficeDocs-SkypeForBusiness <OfficeDocs-SkypeForBusiness@noreply.github.com> Cc: heyadamGIT <adam@hellofromhere.com>, Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Pricing links don't have pricing (#956) 
@heyadamGIT Could you please investigate this issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MicrosoftDocs/OfficeDocs-SkypeForBusiness","title":"MicrosoftDocs/OfficeDocs-SkypeForBusiness","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AndreaBarr in #956: @heyadamGIT Could you please investigate this issue? "}],"action":{"name":"View Issue","url":"https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/956#issuecomment-450016563"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/956#issuecomment-450016563",
"url": "https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/956#issuecomment-450016563",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by heyadamGIT** [comment]
@mrbuckingham Agree.

The pricing link should point directly to https://products.office.com/en-US/business/compare-more-office-365-for-business-plans with a special call out saying "This pricing information is for enterprises. To get additional pricing, please click on the links on the left of the destination page. Voice capabilities (domestic and/or international calling) require a voice add-on for E5 only."

@AndreaBarr Can we commit these changes to docs.microsoft.com?
