### ISSUE TITLE
Out of date text regarding meeting recordings

### ISSUE THREAD

**Issue by JAndre7** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9601]
Can this page be updated for our customers, please? This phrase is way out of date, being well page "early 2021":

 At launch you'll be able to opt-in to this experience, in November you'll have to opt-out if you want to continue using Stream, and some time in early 2021 we'll require all customers to OneDrive for Business and SharePoint for meeting recordings.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b679199-caa5-4cc5-27e5-60a2cf999f69
* Version Independent ID: 6878c954-e248-94c2-7602-47437ec7a2dd
* Content: [Plan for live events in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events)
* Content Source: [Teams/teams-live-events/plan-for-teams-live-events.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-live-events/plan-for-teams-live-events.md)
* Service: **msteams**
* GitHub Login: @MicrosoftHeidi
* Microsoft Alias: **heidip**

**Comment by dariomws** [comment]
If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html 


Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=JAndre7

**Comment by dariomws** [comment]
@JAndre7, that note was removed from the article.
