### ISSUE TITLE
Change grace period from duration to date

### ISSUE THREAD

**Issue by shtakeda** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9706]
Can you change the grace period from duration (i.e. 30/60 days) to date (i.e. March/April 1st)? It's easier to understand when the features will be unavailable without Teams Premium.

https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/licensing-enhance-teams#are-there-current-teams-features-that-will-move-to-teams-premium

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c100aa6e-f8a3-053f-f5c6-d3e543dea5a0
* Version Independent ID: c100aa6e-f8a3-053f-f5c6-d3e543dea5a0
* Content: [Microsoft Teams Premium licensing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/licensing-enhance-teams#are-there-current-teams-features-that-will-move-to-teams-premium)
* Content Source: [Teams/teams-add-on-licensing/licensing-enhance-teams.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/licensing-enhance-teams.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@shtakeda We intentionally used the language of "30-day" and "60-day" because not all Teams Premium features will be releasing at the same time. Additionally, each vertical, like GCC, GCC High, and DoD, are releasing at different times. Lastly, although we have rough estimates of when specific features will release, there are instances when a feature release may be delayed. By using specific months or dates, we would be guaranteeing that features will release at that time. This is something that we won't do in our articles.

**Comment by shtakeda** [comment]
@DaniEASmith , thanks you for your comment. I understand the reason.
