### ISSUE TITLE
Unclear licensing guidance

### ISSUE THREAD

**Issue by Richard-Barr3tt** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9819]
Hi there, 

I had a customer comment to me today that the section which says:

_The Microsoft Teams Shared Devices license supports:_

could possible say

_The Microsoft Teams Shared Devices license includes:_

They were unsure if this license includes intune and AADP1 and this article confused them. 

Just a thought

Rich
alias - ribarret if you wanted to discuss 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9a9a9e9-73ee-8b05-9086-3d4b3116eb4e
* Version Independent ID: f9a9a9e9-73ee-8b05-9086-3d4b3116eb4e
* Content: [Microsoft Teams Shared Devices licensing - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-add-on-licensing/teams-shared-device-license?source=docs)
* Content Source: [Teams/teams-add-on-licensing/teams-shared-device-license.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-add-on-licensing/teams-shared-device-license.md)
* Service: **msteams**
* GitHub Login: @DaniEASmith
* Microsoft Alias: **danismith**

**Comment by DaniEASmith** [comment]
@Richard-Barr3tt Thank you for the feedback! The reason why the word "supports" is used instead of "includes" is because the Teams Shared Devices license doesn't actually include those products. For some readers, the word "includes" may indicate that by purchasing a Teams Shared Devices license they will also receive licenses for those other products, which isn't the case. "Supports" better indicates that the Teams Shared Devices license can be used with those products, or rather supports those products.

**Comment by Richard-Barr3tt** [comment]
Thanks Dani, appreciate it.

Rich
________________________________

**Comment by DaniEASmith** [comment]
@Richard-Barr3tt The doc has been updated, so I'm closing this issue now. Thanks!
