### ISSUE TITLE
I could not get B2B Direct Connect working for 'Calendar Pro' Teams app in shared channel tab.

### ISSUE THREAD

**Issue by Ty-fxtech** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9856]
I could not get B2B Direct Connect working for 'Calendar Pro' teams tab.

Steps for reproduction:

-Setup B2B direct connect inbound / Outbound allow all between 2 tenants.
-Create a shared Microsoft Teams channel in 'Home' tenant, invite users from both tenants.
-Add 'Calendar Pro' app and tab to shared channel from 'home' tenant.
-in 'Home' tenant, in Azure AD admin center invite external tenant users to Calendar pro App.
-Calendar Pro tab will appear for all users in teams now.

Issue:

When external user clicks Calendar Pro tab they get an error message:

"We're having issues reaching this app"

Home users can view Calendar Pro tab without issues.

Let me know if you have any questions about this, thanks!

-Tyler

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Version Independent ID: 82e6deaf-68f5-e3c9-7259-775ed7662d85
* Content: [Shared channels in Microsoft Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/shared-channels#supported-apps-in-shared-channels)
* Content Source: [Teams/shared-channels.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/shared-channels.md)
* Service: **msteams**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by Ty-fxtech** [comment]
![image](https://user-images.githubusercontent.com/115636194/227611142-47254b1b-75ec-40fb-bc28-8ad10022aa5a.png)

**Comment by Ty-fxtech** [comment]
If you want more details on the specific tenants etc I'm testing with I can provide those in a DM or something more secure.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Xyvir** [comment]
I followed up with Microsoft Support, who led me to Calendar Pro. They said it seemed to be a software issue.

 Calendar Pro support said it was development issue they were working on and then immediately ghosted me and stopped providing updates. I haven't heard back from them since Aril 7th 2023.

I request to update this page to remove the 'Calendar Pro'  app from the list of apps supported by 'Shared Channels' until Witvio can get their act together and update their software to work properly.
 
Let me know if you have any questions, thanks.

-Tyler

![image](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/assets/23508213/3d187247-1a68-486e-90f6-a065687041aa)
