### ISSUE TITLE
Set-CsTenantFederationConfiguration command to disable shared sip failed with not supported anymore

### ISSUE THREAD

**Issue by benoithamet** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9881]
Hi there

the command provided to disable shared sip space failed with the below error
Set-CsTenantFederationConfiguration : Processing data from remote server api.interfaces.records.teams.microsoft.com
failed with the following error message: ⁠This scenario is not supported anymore. Please try with the latest Teams
PowerShell Module version or different parameter sets or refreshing Connect-MicrosoftTeams or refer to the public
documentation. For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ Set-CsTenantFederationConfiguration -SharedSipAddressSpace $false
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Set-CsTenantFederationConfiguration], PSRemotingTransportExcep
   tion
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Teams.C
   onfigApi.Cmdlets.SetCsTenantFederationConfiguration

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ce37c7f-6f13-8442-bfdb-47065a7339b3
* Version Independent ID: 9a2b5082-369d-7c04-4fa8-81c1440ea119
* Content: [Disable hybrid to complete migration to Teams Only - Skype for Business Hybrid](https://learn.microsoft.com/en-us/skypeforbusiness/hybrid/cloud-consolidation-disabling-hybrid)
* Content Source: [Skype/SfbHybrid/hybrid/cloud-consolidation-disabling-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Skype/SfbHybrid/hybrid/cloud-consolidation-disabling-hybrid.md)
* Service: **skype-for-business-server**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by dariomws** [comment]
Hi @benoithamet, thank you for your feedback.

I have tested it and worked:
![image](https://user-images.githubusercontent.com/33589238/228963467-5d064500-28a0-4713-897d-d5faf56052a6.png)

Please check that you are using the latest version of the Teams PowerShell module.

If you still have problems, the best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information provided at [Get support](https://docs.microsoft.com/microsoft-365/business-video/get-help-support). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).

**Comment by benoithamet** [comment]
Thanks
It worked; it is failing when running from the Skype for Business server
