### ISSUE TITLE
SfB Server 2019 Environmental requirements for Skype for Business Server link incorrect 

### ISSUE THREAD

**Issue by Markusott7** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#990]
Environmental requirements for Skype for Business Server link incorrectly points to 2015 requrements instead of 2019 requirements:

At: Create a file share in Skype for Business Server
https://docs.microsoft.com/en-us/skypeforbusiness/deploy/install/create-a-file-share

Incorrect: Environmental requirements for Skype for Business Server
https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/requirements-for-your-environment/environmental-requirements

Correct: System requirements for Skype for Business Server
https://docs.microsoft.com/en-us/skypeforbusiness/plan/system-requirements

**Comment by AndreaBarr** [comment]
@Markusott7 Thank you for this feedback

I will get this information about the wrong links to the Skype for Business team for investigation.

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@kellipav could you please make the changes listed above?

**Comment by MicrosoftHeidi** [comment]
Environmental requirements is a 2015 article. System Requirements is the 2019 article. There should be nothing in the 2015 article that references 2019.

**Comment by jambirk** [comment]
@MicrosoftHeidi , this is a deploy article that is shared by both versions. There needs to be a link to both articles.

@Markusott7 the links provided correctly point to different articles: one for server 2015 requirements and one for server 2019 requirements. This is because the article is shared by both versions, and the process is only different in cases like this, when separate links are needed to get to version-dependant requirements. Docs.microsoft.com lets us do certain things that weren't possible on Technet.microsoft.com, and this is one of them.
