### ISSUE TITLE
Polycom X30 and X50 inaccurate for Certified Teams Rooms on Android

### ISSUE THREAD

**Issue by davebirr** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9950]
[Enter feedback here]
Polycom X30 and X50 are not longer certified for firmware 4.0.0.100885 and it has been removed from Teams Admin Center. We currently support 3.12.0.366027 for the X30 and 3.12.0.210716 for the TC8 device.

https://www.poly.com/ch/fr/support/knowledge-base/kb-article-page?type=Support+Information&lang=en_US&urlName=PolyOS-4-0-0-removed-from-MS-TAC&t=all&k=Poly%C2%A0Studio%C2%A0X70

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aaaef9e1-8f1c-ebf0-7856-4c007342a2c3
* Version Independent ID: 3eaf671f-375e-8787-9c66-3947c3606559
* Content: [Devices for Teams - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/devices/teams-ip-phones?source=docs#certified-teams-rooms-on-android)
* Content Source: [Teams/devices/teams-ip-phones.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/devices/teams-ip-phones.md)
* Service: **msteams**
* Sub-service: **itpro-devices**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @davebirr, thank you for your feedback.

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears on any PRs or issues you submit—guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html. 

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=davebirr

**Comment by dstrome** [comment]
The article is correct. We're submitting a request to Poly to update or remove their post. Closing this issue.
