### ISSUE TITLE
Concurrent streams

### ISSUE THREAD

**Issue by Petri-X** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9965]
Hi,

When looking for this page and statistics on CQD I have got feeling that CQD is showing streams incorrectly. Or the page does not make this so clearly. So I though to ask from here if someone could share more details to this, then I perhaps could even update the document for this.

My statement is, CQD does not shows the concurrent streams.

Here are few calls from my test tenant:
![image](https://user-images.githubusercontent.com/43988151/233606151-229f54be-9b00-4693-bd70-bcf0bdf9600a.png)
These time stamps are only from times when the calls has end. So basically if the stream has been taken 10 minutes, The CQD shows only that call has took one minute.

I can even open the support case to this, but there is risk that the answer is "this is by design".

So question is, is this how CQD should be working?

@ParkesJ I believe you have some deeper knowledge on this, if you like to comment?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a455280-ea8e-2ddf-2965-60d9dcc0e21d
* Version Independent ID: 7fb320d3-fa69-23fa-113c-53e9d2e11ada
* Content: [Dimensions and measurements - Call Quality Dashboard (CQD) - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/dimensions-and-measures-available-in-call-quality-dashboard)
* Content Source: [Teams/dimensions-and-measures-available-in-call-quality-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dimensions-and-measures-available-in-call-quality-dashboard.md)
* Service: **msteams**
* GitHub Login: @CarolynRowe
* Microsoft Alias: **crowe**

**Comment by ParkesJ** [comment]
This is indeed ”by design”. This report does not show concurrent streams nor is it meant to.

We’re working on a report for Power BI that will show concurrent streams (and by extension, be able to show the concurrent bandwidth use) using CQD’s data, but this work is ongoing as there are a few blockers we need to overcome first to accurately represent concurrent streams and concurrent bandwidth.


James Parkes
Senior Product Manager – IC3
Microsoft Teams Call Quality Management
Microsoft Corporation

From: Petri-X ***@***.***>
Sent: Friday, April 21, 2023 4:00 AM
To: MicrosoftDocs/OfficeDocs-SkypeForBusiness ***@***.***>
Cc: James Parkes ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/OfficeDocs-SkypeForBusiness] Concurrent streams (Issue #9965)


Hi,

When looking for this page and statistics on CQD I have got feeling that CQD is showing streams incorrectly. Or the page does not make this so clearly. So I though to ask from here if someone could share more details to this, then I perhaps could even update the document for this.

My statement is, CQD does not shows the concurrent streams.

Here are few calls from my test tenant:
[image]<https://user-images.githubusercontent.com/43988151/233606151-229f54be-9b00-4693-bd70-bcf0bdf9600a.png>
These time stamps are only from times when the calls has end. So basically if the stream has been taken 10 minutes, The CQD shows only that call has took one minute.

I can even open the support case to this, but there is risk that the answer is "this is by design".

So question is, is this how CQD should be working?

@ParkesJ<https://github.com/ParkesJ> I believe you have some deeper knowledge on this, if you like to comment?

________________________________
Document Details

⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

  *   ID: 1a455280-ea8e-2ddf-2965-60d9dcc0e21d
  *   Version Independent ID: 7fb320d3-fa69-23fa-113c-53e9d2e11ada
  *   Content: Dimensions and measurements - Call Quality Dashboard (CQD) - Microsoft Teams<https://learn.microsoft.com/en-us/microsoftteams/dimensions-and-measures-available-in-call-quality-dashboard>
  *   Content Source: Teams/dimensions-and-measures-available-in-call-quality-dashboard.md<https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/dimensions-and-measures-available-in-call-quality-dashboard.md>
  *   Service: msteams
  *   GitHub Login: @CarolynRowe<https://github.com/CarolynRowe>
  *   Microsoft Alias: crowe

**Comment by Petri-X** [comment]
@ParkesJ 
Big thanks for your quick answer. Wish you and your team find the solution for the blockers, as this information would be nice to have. CQD knows already the end time for stream, and duration. So it should be doable, but obviously it is not that simple :D

Have a great weekend!
