### ISSUE TITLE
"Reply with IM" and "Reply All with IM" functionality within VDI

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [MicrosoftDocs/OfficeDocs-SkypeForBusiness#9966]
First, we have a question regarding if this is truly a limitation on VDI. We recently discovered that these options are not available despite us having "Register Teams as the chat app for Office" enabled and verifying the [registry key](https://learn.microsoft.com/en-us/outlook/troubleshoot/user-interface/some-instant-messaging-client-features-not-available#resolution) is in place.

If it is a limitation, we are requesting that it be added to this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17880b9d-6b98-3194-cc33-fe8067ce241e
* Version Independent ID: 643bcf2f-507b-e449-73db-923d8a368ad9
* Content: [Teams for Virtualized Desktop Infrastructure - Microsoft Teams](https://learn.microsoft.com/en-us/microsoftteams/teams-for-vdi#known-issues-and-limitations)
* Content Source: [Teams/teams-for-vdi.md](https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/blob/live/Teams/teams-for-vdi.md)
* Service: **msteams**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws** [comment]
Hi @FMCUSystemAdmins, thank you for your feedback.

It's not a VDI limitation. Do you have the option for non-VDI machines?

**Comment by FMCUSystemAdmins** [comment]
Yes, those options are available on non-VDI machines

**Comment by dariomws** [comment]
I understand that this is not a limitation of VDI. The best way to get your issue resolved is to contact Microsoft Support. If you’re a Microsoft 365 or Office 365 admin, use the information provided at [Get support](https://docs.microsoft.com/microsoft-365/business-video/get-help-support). Otherwise, you can create a support ticket at [Microsoft Support for business](https://support.serviceshub.microsoft.com/supportforbusiness).

We'll include this limitation if they say it is a VID limitation. My apologies, but I cannot provide you with more assistance through this channel.

**Comment by FMCUSystemAdmins** [comment]
We will open a ticket with Microsoft and let you know the outcome. Thank you.
